In [4]:
from pathlib import Path
import polars as pl
import tiktoken

DATA_DIR = Path("/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/") / "data"
(DATA_DIR / "processed").mkdir(parents=True, exist_ok=True)

encoding = tiktoken.encoding_for_model("gpt-4o")

In [ ]:
from datasets import load_dataset

ds = load_dataset("Salesforce/wikitext", "wikitext-103-v1")

README.md: 0.00B [00:00, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/722k [00:00<?, ?B/s]

train-00000-of-00002.parquet:   0%|          | 0.00/156M [00:00<?, ?B/s]

train-00001-of-00002.parquet:   0%|          | 0.00/156M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/655k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/1801350 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

In [2]:
import polars as pl

df = pl.scan_ndjson("~/Downloads/v1.0 simplified nq dev all.jsonl")
df.head(2).collect()

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ annotatio ┆ document_ ┆ document_ ┆ document_ ┆ … ┆ example_i ┆ long_answ ┆ question_ ┆ question │
│ ns        ┆ html      ┆ title     ┆ tokens    ┆   ┆ d         ┆ er_candid ┆ text      ┆ _tokens  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ates      ┆ ---       ┆ ---      │
│ list[stru ┆ str       ┆ str       ┆ list[stru ┆   ┆ i64       ┆ ---       ┆ str       ┆ list[str │
│ ct[4]]    ┆           ┆           ┆ ct[4]]    ┆   ┆           ┆ list[stru ┆           ┆ ]        │
│           ┆           ┆           ┆           ┆   ┆           ┆ ct[5]]    ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [{null,{9 ┆ <!DOCTYPE ┆ Therefore ┆ [{101,fal ┆ … ┆ 691560647 ┆ [{66428,8 ┆ what do   ┆ ["what", │
│ 2,67824,9 ┆ html>     ┆ sign      ┆ se,92,"Th ┆   ┆ 766896339 ┆ 08,41427, ┆ the 3     ┆ "do", …  │
│ 25,66429, ┆ <HTML     ┆           ┆ erefore"} ┆   ┆ 9         ┆ 14,true}, ┆ dots mean ┆ "math"]  │
│ 808…      ┆ class="c… ┆           ┆ , {…      ┆   ┆           ┆ {4…       ┆ in mat…   ┆          │
│ [{null,{- ┆ <!DOCTYPE ┆ Watchman  ┆ [{100,fal ┆ … ┆ -45059718 ┆ [{43267,1 ┆ when was  ┆ ["when", │
│ 1,-1,-1,- ┆ html>     ┆ (law enfo ┆ se,92,"Wa ┆   ┆ 231740849 ┆ 15,41595, ┆ the writ  ┆ "was", … │
│ 1,-1},[], ┆ <HTML     ┆ rcement)  ┆ tchman"}, ┆   ┆ 26        ┆ 30,true}, ┆ watch     ┆ "who"]   │
│ "NO…      ┆ class="c… ┆           ┆ {1…       ┆   ┆           ┆ {4…       ┆ invent…   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
counts = (
    df.select(pl.col("document_url").value_counts()).collect().unnest("document_url").sort("count", descending=True)
)
counts

shape: (7_369, 2)
┌─────────────────────────────────┬───────┐
│ document_url                    ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ …                               ┆ …     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
└─────────────────────────────────┴───────┘

In [ ]:
counts.sort("count", descending=True)

shape: (7_369, 2)
┌─────────────────────────────────┬───────┐
│ document_url                    ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ https://en.wikipedia.org//w/in… ┆ 8     │
│ https://en.wikipedia.org//w/in… ┆ 7     │
│ https://en.wikipedia.org//w/in… ┆ 6     │
│ https://en.wikipedia.org//w/in… ┆ 6     │
│ https://en.wikipedia.org//w/in… ┆ 5     │
│ …                               ┆ …     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
│ https://en.wikipedia.org//w/in… ┆ 1     │
└─────────────────────────────────┴───────┘

In [3]:
token_counts = (
    df.with_columns(
        pl.col("document_html")
        .map_elements(lambda x: len(encoding.encode(x)), return_dtype=pl.Int64)
        .alias("document_tokens")
    )
    .select("document_tokens")
    .collect()
)
token_counts

shape: (7_830, 1)
┌─────────────────┐
│ document_tokens │
│ ---             │
│ i64             │
╞═════════════════╡
│ 34241           │
│ 43051           │
│ 82144           │
│ 59866           │
│ 46280           │
│ …               │
│ 58626           │
│ 83301           │
│ 78043           │
│ 112316          │
│ 73662           │
└─────────────────┘

In [ ]:
token_counts.select(
    pl.col("document_tokens").min().alias("min"),
    pl.col("document_tokens").max().alias("max"),
    pl.col("document_tokens").mean().alias("mean"),
)

shape: (1, 3)
┌───────┬────────┬──────────────┐
│ min   ┆ max    ┆ mean         │
│ ---   ┆ ---    ┆ ---          │
│ i64   ┆ i64    ┆ f64          │
╞═══════╪════════╪══════════════╡
│ 15146 ┆ 548918 ┆ 76573.488378 │
└───────┴────────┴──────────────┘

In [ ]:
import altair as alt

alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [ ]:
hist_values = (
    token_counts["document_tokens"]
    .hist(bins=[0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000])
    .with_columns(pl.col("category").cast(pl.Utf8))
)
hist_values

shape: (10, 3)
┌────────────┬──────────────────────┬───────┐
│ breakpoint ┆ category             ┆ count │
│ ---        ┆ ---                  ┆ ---   │
│ f64        ┆ str                  ┆ u32   │
╞════════════╪══════════════════════╪═══════╡
│ 50000.0    ┆ [0.0, 50000.0]       ┆ 3050  │
│ 100000.0   ┆ (50000.0, 100000.0]  ┆ 3024  │
│ 150000.0   ┆ (100000.0, 150000.0] ┆ 1081  │
│ 200000.0   ┆ (150000.0, 200000.0] ┆ 381   │
│ 250000.0   ┆ (200000.0, 250000.0] ┆ 156   │
│ 300000.0   ┆ (250000.0, 300000.0] ┆ 81    │
│ 350000.0   ┆ (300000.0, 350000.0] ┆ 37    │
│ 400000.0   ┆ (350000.0, 400000.0] ┆ 7     │
│ 450000.0   ┆ (400000.0, 450000.0] ┆ 1     │
│ 500000.0   ┆ (450000.0, 500000.0] ┆ 3     │
└────────────┴──────────────────────┴───────┘

In [24]:
hist_values.plot.bar(y="count", x=alt.X("category", sort=None))

alt.Chart(...)

In [19]:
len([x for x in samples[0]["long_answer_candidates"] if x["top_level"] == True])

14

In [ ]:
samples = df.head().collect().to_pandas().to_dict(orient="index")
samples

In [15]:
len(samples[0]["document_html"])

103968

In [ ]:
tokens = encoding.encode(samples[0]["document_html"])

len(tokens)

34241

In [ ]:
# Alternative simpler approach for mode calculation
from collections import Counter


def get_mode_tokens(annotations):
    """Get mode of start and end tokens from annotations, excluding -1 values"""
    start_tokens = []
    end_tokens = []

    for annotation in annotations:
        if "long_answer" in annotation:
            start_token = annotation["long_answer"].get("start_token", -1)
            end_token = annotation["long_answer"].get("end_token", -1)

            if start_token != -1:
                start_tokens.append(start_token)
            if end_token != -1:
                end_tokens.append(end_token)

    if not start_tokens or not end_tokens:
        return [-1, -1]

    # Get mode (most common value) or None if no valid tokens
    mode_start = Counter(start_tokens).most_common(1)[0][0] if start_tokens else -1
    mode_end = Counter(end_tokens).most_common(1)[0][0] if end_tokens else -1

    return mode_start, mode_end


# Apply to DataFrame using map_elements (for complex operations)
df_with_simple_mode = (
    df.with_columns(
        [
            pl.col("annotations")
            .map_elements(lambda x: get_mode_tokens(x), return_dtype=pl.List(pl.Int64))
            .alias("mode_tokens")
        ]
    )
    .with_columns(
        [
            pl.col("mode_tokens").list.first().alias("mode_start_token"),
            pl.col("mode_tokens").list.last().alias("mode_end_token"),
        ]
    )
    # .with_columns(
    #     [
    #         pl.col("mode_start_token").map_elements(lambda x: print(f"start: {x}, type: {type(x)}") or x),
    #         pl.col("mode_end_token").map_elements(lambda x: print(f"end: {x}, type: {type(x)}") or x),
    #         pl.col("document_tokens").map_elements(lambda x: print(f"len: {len(x)}, {x[:3]}")),
    #     ]
    # )
    .with_columns(
        [
            # Create sliced tokens using mode values
            pl.when((pl.col("mode_start_token") != -1) & (pl.col("mode_end_token") != -1))
            .then(
                pl.col("document_tokens").list.slice(
                    pl.col("mode_start_token"), pl.col("mode_end_token") - pl.col("mode_start_token")
                )
            )
            .otherwise(None)
            .alias("sliced_document_tokens_simple_mode")
        ]
    )
    .with_columns(
        pl.col("sliced_document_tokens_simple_mode")
        .list.eval(pl.element().struct.field("token"))
        .list.join(" ")
        .alias("long_answer_text")
    )
)

print("DataFrame with simple mode calculation:")
df_with_simple_mode.select("document_url", "question_text", "long_answer_text", "document_html").sink_parquet(
    DATA_DIR / "processed/nq_question_answer.parquet"
)

DataFrame with simple mode calculation:

In [55]:
df_with_simple_mode.select("document_url", "question_text", "long_answer_text", "document_html").collect()

KeyboardInterrupt:

## Create Embeddings

In [1]:
%load_ext autoreload
%autoreload 2
import sys

sys.path.append("/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/generative-benchmarking")

import chromadb
import pandas as pd
import numpy as np
import json
import os
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
from openai import OpenAI as OpenAIClient

from functions.llm import *
from functions.embed import *
from functions.chroma import *
from functions.evaluate import *
from functions.visualize import *
from rag_pipeline import DATA_DIR
import polars as pl
import polars as pl
from langchain_text_splitters import RecursiveCharacterTextSplitter
from bs4 import BeautifulSoup

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
assert OPENAI_API_KEY is not None, "OPENAI_API_KEY is not set"

chroma_client = chromadb.PersistentClient(path=DATA_DIR / "chroma")
openai_client = OpenAIClient(api_key=OPENAI_API_KEY)

2025-08-25 17:24:58.899 | DEBUG    | rag_pipeline:<module>:29 - DATA_DIR=PosixPath('/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data')

In [2]:
wiki_qa = pl.scan_parquet(DATA_DIR / "processed/nq_question_answer.parquet")
wiki_qa.head().collect()

shape: (5, 4)
┌──────────────────────────┬──────────────────────────┬──────────────────────────┬─────────────────┐
│ document_url             ┆ question_text            ┆ long_answer_text         ┆ document_html   │
│ ---                      ┆ ---                      ┆ ---                      ┆ ---             │
│ str                      ┆ str                      ┆ str                      ┆ str             │
╞══════════════════════════╪══════════════════════════╪══════════════════════════╪═════════════════╡
│ https://en.wikipedia.org ┆ what do the 3 dots mean  ┆ <P> In logical argument  ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ in mat…                  ┆ and ma…                  ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ when was the writ watch  ┆ null                     ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ invent…                  ┆                          ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ who wrote the song       ┆ <P> `` Photograph '' is  ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ photograph …             ┆ a song…                  ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ who is playing the       ┆ <P> The Super Bowl 50    ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ halftime sh…             ┆ Halftime…                ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ star wars the clone wars ┆ <P> Matthew MacKendree   ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ anaki…                   ┆ `` Matt…                 ┆ <HTML class="c… │
└──────────────────────────┴──────────────────────────┴──────────────────────────┴─────────────────┘

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=100)
wiki_qa.with_columns(
    pl.col("document_html")
    .map_elements(lambda x: BeautifulSoup(x, "html.parser").get_text(), return_dtype=pl.String)
    .map_elements(lambda x: text_splitter.split_text(x), return_dtype=pl.List(pl.String))
    .alias("chunked_prompt")
).sink_parquet(DATA_DIR / "processed/nq_question_answer_chunked.parquet")

In [3]:
wiki_chunked = pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked.parquet")
wiki_chunked.head(1).collect()

shape: (1, 5)
┌────────────────────┬───────────────────┬───────────────────┬─────────────────┬───────────────────┐
│ document_url       ┆ question_text     ┆ long_answer_text  ┆ document_html   ┆ chunked_prompt    │
│ ---                ┆ ---               ┆ ---               ┆ ---             ┆ ---               │
│ str                ┆ str               ┆ str               ┆ str             ┆ list[str]         │
╞════════════════════╪═══════════════════╪═══════════════════╪═════════════════╪═══════════════════╡
│ https://en.wikiped ┆ what do the 3     ┆ <P> In logical    ┆ <!DOCTYPE html> ┆ ["Therefore sign  │
│ ia.org//w/in…      ┆ dots mean in mat… ┆ argument and ma…  ┆ <HTML class="c… ┆ - Wikipedia       │
│                    ┆                   ┆                   ┆                 ┆                   │
│                    ┆                   ┆                   ┆                 ┆ …                 │
└────────────────────┴───────────────────┴───────────────────┴─────────────────┴───────────────────┘

In [4]:
from uuid import uuid4


def generate_ids(n: int) -> list[str]:
    return [str(uuid4()) for _ in range(n)]


documents = (
    pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked.parquet")
    # .limit(50)
    .select("chunked_prompt", "document_url")
    .explode("chunked_prompt")
).collect()
documents = documents.with_columns(pl.Series(generate_ids(documents.height)).alias("unique_id"))
print(documents.shape)
print(documents.select(pl.col("chunked_prompt").str.len_chars().mean()))
documents.head()

(1074844, 3)
shape: (1, 1)
┌────────────────┐
│ chunked_prompt │
│ ---            │
│ f64            │
╞════════════════╡
│ 298.442895     │
└────────────────┘

shape: (5, 3)
┌────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ chunked_prompt             ┆ document_url                    ┆ unique_id                       │
│ ---                        ┆ ---                             ┆ ---                             │
│ str                        ┆ str                             ┆ str                             │
╞════════════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ Therefore sign - Wikipedia ┆ https://en.wikipedia.org//w/in… ┆ 89a43d2f-254a-47dc-9571-9f29a1… │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ …                          ┆                                 ┆                                 │
│ exclamation mark           ┆ https://en.wikipedia.org//w/in… ┆ b85bf13a-59ca-440b-8e47-96d017… │
│  !                         ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ full sto…                  ┆                                 ┆                                 │
│ asterisk                   ┆ https://en.wikipedia.org//w/in… ┆ 93159d2d-f1aa-47bb-a7fb-ac1271… │
│ *                          ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ at sign                    ┆                                 ┆                                 │
│ @                          ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ backs…                     ┆                                 ┆                                 │
│ percent, per mil           ┆ https://en.wikipedia.org//w/in… ┆ c0fe553f-0b51-41eb-9b08-2705a2… │
│  % ‰                       ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ plus a…                    ┆                                 ┆                                 │
│ service mark               ┆ https://en.wikipedia.org//w/in… ┆ dede3019-9bd3-422b-8fb3-bf3578… │
│ ℠                          ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ trademark                  ┆                                 ┆                                 │
│ ™                          ┆                                 ┆                                 │
│                            ┆                                 ┆                                 │
│ …                          ┆                                 ┆                                 │
└────────────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [8]:
corpus_ids = documents.select("unique_id").to_numpy().reshape(-1).tolist()
corpus_documents = documents.select("chunked_prompt").to_numpy().reshape(-1).tolist()
# metadatas = documents.select("document_url").to_dicts()
# print(type(corpus_ids), type(corpus_documents), type(metadatas))

for batch in range(0, len(corpus_documents), 100_000):
    selected_documents = documents.filter(pl.col("unique_id").is_in(corpus_ids[batch : batch + 100_000]))
    corpus_embeddings = openai_embed_in_batches(
        openai_client=openai_client,
        model="text-embedding-3-small",
        texts=selected_documents.select("chunked_prompt").to_numpy().reshape(-1).tolist(),
        batch_size=200,
    )
    selected_documents = selected_documents.with_columns(pl.Series(corpus_embeddings).alias("embedding")).write_parquet(
        DATA_DIR / f"processed/nq_question_answer_chunked_embeddings_{batch}.parquet"
    )

Processing OpenAI batches: 100%|██████████| 500/500 [09:43<00:00,  1.17s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [1:41:17<00:00, 12.16s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [09:03<00:00,  1.09s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [09:16<00:00,  1.11s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [16:46<00:00,  2.01s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [44:35<00:00,  5.35s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [10:47:27<00:00, 77.70s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [09:47<00:00,  1.18s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [09:10<00:00,  1.10s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [09:12<00:00,  1.10s/it]
Processing OpenAI batches: 100%|██████████| 375/375 [07:17<00:00,  1.17s/it]

In [2]:
lazy_docs = pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked_embeddings_*.parquet")
lazy_docs.collect_schema()

Schema([('chunked_prompt', String),
        ('document_url', String),
        ('unique_id', String),
        ('embedding', List(Float64))])

In [3]:
# Find strings with invalid characters
import re

pattern = r"[^a-zA-Z0-9._-]"
strings = documents.select("document_url").unique().to_numpy().reshape(-1).tolist()
# Test examples
invalid = []
for s in strings:
    x = extract_title_from_path(s)
    if re.search(pattern, x):
        invalid.append(x)
invalid

NameError: name 'documents' is not defined

In [ ]:
import re

strings = documents.select("document_url").unique().to_numpy().reshape(-1).tolist()


def extract_title_from_path(url):
    pattern = r"title=([^&]+)"
    match = re.search(pattern, url)
    return match.group(1).translate({ord(c): None for c in "!@#$():%,^&!/+=."}) if match else None


for doc in strings:
    print(extract_title_from_path(doc))

1_2B_2_2B_3_2B_4_2B_E28BAF
Lay_Your_Hands_on_Me_Boom_Boom_Satellites_song
High-level_radioactive_waste_management
Sport_utility_vehicle
List_of_Super_Bowl_champions
United_States_declaration_of_war_on_Japan
Spilling_water_for_luck
San_Joaquin_County_California
List_of_Rajya_Sabha_members_from_Assam
An_Officer_and_a_Gentleman
Fender_amplifier
Names_of_the_days_of_the_week
Hard_water
List_of_PokC3A9mon_Advanced_Battle_episodes
Civilian_Conservation_Corps
Kristen_Bell
The_Young_and_the_Restless_cast_members
Sputnik_crisis
Recording_Industry_Association_of_America_certification
Jordan_River
Cast_Away
Forest
IndiGo
I27ll_Name_the_Dogs
Arsenal_FC
Ratatouille_film
The_Pilgrim27s_Progress
Go_Outside_in_the_Rain
Trafalgar_Square_Christmas_tree
Beyond_the_Sea_film
Arms_and_the_Man
List_of_highest-grossing_films
List_of_Miraculous_Tales_of_Ladybug_26_Cat_Noir_episodes
Papa27s_Got_a_Brand_New_Bag
Timothy_McGee
Joseph_Kearns
Grand_slam_baseball
I27m_Just_a_Kid
Life
Gimme_Shelter
History_of_South_America
AMX
Those_who_live_in_glass_houses_should_not_throw_stones
Brian_O27Conner
Dominican_Republic
Routing_table
Baby_It27s_Cold_Outside
Rock_Chalk_Jayhawk
Comes_a_Time
Who_Let_the_Dogs_Out3F
History_of_democracy
Glory_religion
World27s_tallest_thermometer
Nodar_Kumaritashvili
Galvanic_cell
Over_the_Limit_2012
A_Pretty_Little_Liars
Yeh_Raaste_Hain_Pyaar_Ke
Polycythemia
List_of_current_Indian_chief_ministers
The_Whiskey_Ain27t_Workin27
Alaska_Time_Zone
Nature_center
Merry_Clayton
Henry-Russell_Hitchcock
Roxette
History_of_rugby_union_matches_between_England_and_Scotland
Northwest_Passage
List_of_earthquakes_in_the_United_States
Michael_Clarke_Duncan
Nursing_and_Midwifery_Council
Pam_Beesly
Conscription_in_the_United_Kingdom
Jugantar_Patrika
This_Ain27t_My_First_Rodeo
The_World_Is_Not_Enough
Atmosphere_of_Earth
Sewage
Take_My_Breath_Away
The_Lego_Batman_Movie
Chief_Election_Commissioner_of_India
Philippine_Amusement_and_Gaming_Corporation
List_of_New_Brunswick_provincial_highways
McKinley_Tariff
Dust_Bowl
Regions_of_Italy
When_the_Stars_Go_Blue
List_of_Dragon_Ball_Z_episodes
Game_of_Thrones_season_7
On_Golden_Pond_1981_film
High_Middle_Ages
Jesuit_missions_in_North_America
Taurus_Mountains
List_of_Prime_Ministers_of_India
Age_of_Enlightenment
John_Scully_American_football
Royal_Rumble
Great_Depression_in_the_United_States
Walter_Egan
Mark_Sloan_Grey27s_Anatomy
Breakup_of_Yugoslavia
Help_album
Falcon_Heavy
Batman_Gotham_by_Gaslight
List_of_protected_areas_of_the_Philippines
Taj_Mahal
Canada_small_business_tax_rate
Manchester_by_the_Sea_film
Tony_Stonem
Crepuscular
The_Post_film
French_Revolution
Octet_rule
Maria_West_Side_Story
Mark_Shuttleworth
List_of_New_England_Patriots_seasons
Made_in_Chelsea
Radio_wave
Chess_World_Cup_2017
Balls_to_the_Wall_song
History_of_the_Byzantine_Empire
Extinction
War_of_1812
Subsistence_agriculture
Jaipur
History_of_laws_concerning_immigration_and_naturalization_in_the_United_States
LASIK
List_of_Cleveland_Browns_head_coaches
Vikram_Samvat
Christmas_Kettle
Negan
El_deity
World_Wide_Web
O_Brother_Where_Art_Thou3F
George_Barnes_musician
School_holidays_in_the_United_States
List_of_Super_Bowl_broadcasters
Brown
Nervous_system
Spinal_fusion
Death_in_Paradise_TV_series
Kick_the_bucket
List_of_most-viewed_YouTube_videos
Rocket_League
Hit_the_Road_Jack
Major_depressive_disorder
Their_Eyes_Were_Watching_God
Premier_League_records_and_statistics
Weather_vane
High_School_Musical_3_Senior_Year
Marquis_St_EvrC3A9monde
Supreme_Court_of_Illinois
Johnny_Bravo
Airway_resistance
Call_of_Duty_WWII
Age_of_marriage_in_the_United_States
List_of_Stanley_Cup_champions
Timeline_of_the_National_Football_League
Dave_Gahan
Itai-itai_disease
Finger
All_These_Things_That_I27ve_Done
Fourteenth_Amendment_to_the_United_States_Constitution
Walk_the_Line
Li_Song
Muscle
Judiciary_of_Scotland
Response_to_the_State_of_the_Union_address
Welfare_definition_of_economics
Trinitarian_formula
Relax_song
Jack_Taylor_TV_series
List_of_US_states_by_date_of_admission_to_the_Union
Rock_and_Roll_All_Nite
The_Imp_of_the_Perverse_short_story
We27re_Going_on_a_Bear_Hunt
Mandy_Moore_choreographer
World_Series
Kanye_West_production_discography
Carbonic_acid
List_of_best-selling_music_artists
List_of_Criminal_Minds_characters
Evolutionary_developmental_biology
Communications_satellite
Thomas_and_the_Magic_Railroad
List_of_Disney_Princess_firsts
Age_of_Discovery
Dove27s_dung
Results_of_the_War_of_1812
FA_Cup_semi-finals
Duluth_model
Dark_Side_of_the_Rainbow
Economy_of_the_United_States
Yom_Kippur
Ellen_Harvelle
List_of_languages_by_number_of_native_speakers
The_Presidents_of_the_United_States_of_America_band
Province_of_New_Hampshire
Fatestay_night_Unlimited_Blade_Works
Types_of_volcanic_eruptions
Smart_card
When_a_Snail_Falls_in_Love
African_Union
Brenda27s_Got_a_Baby
Let_My_Love_Open_the_Door
The_Good_Place
Declaration_of_war_by_the_United_States
Indonesia
Saltine_cracker_challenge
The_King_and_I_1956_film
One_Tree_Hill_New_Zealand
Lists_of_schools_in_New_Zealand
DNA
Director_of_football
NCAA_Division_I_Men27s_Basketball_Tournament
List_of_NHL_franchise_post-season_droughts
King_surname
Brown_v_Board_of_Education
Costa_Rica_at_the_FIFA_World_Cup
Holiday_Road
Just_Dropped_In_To_See_What_Condition_My_Condition_Was_In
The_Client_1994_film
Engagement_ring
Walk_Hard_The_Dewey_Cox_Story
Root_chord
Historian
Star_Trek_Discovery
List_of_most_streamed_artists_on_Spotify
Oakland_Raiders_relocation_to_Las_Vegas
History_of_Mexico_City
Rachel_Bilson
List_of_Jesuit_educational_institutions
Brendan_Gleeson
Good_Night_Beatles_song
Sara_Harvey_Pretty_Little_Liars
Chapter_8_album
Disaster_recovery_plan
Sokka
2017_Major_League_Baseball_All-Star_Game
2018_NBA_All-Star_Game
Pulse
Cerebrum
United_States
Ring_Up
List_of_DreamWorks_Dragons_episodes
I_Can_Only_Imagine_MercyMe_song
Fargo_season_2
Stop_and_identify_statutes
90210_season_1
Bengali_novels
Toilet_room
American_Horror_Story_Cult
God_in_Judaism
Mitral_valve
North_India
Governor_of_the_Bank_of_England
Category1960s_video_games
Call_Me_Maybe
John_Carpenter_game_show_contestant
Bledisloe_Cup
Disk_Cleanup
Zone_defense
Whale_shark
Citric_acid_cycle
That_2770s_Show
Geothermal_energy_in_the_United_States
President_of_the_Republic_of_Texas
History_of_democracy
Privileges_or_Immunities_Clause
List_of_One_Piece_episodes_seasons_15E28093current
Kite_geometry
Flash_vs_Arrow
Battle_of_Carnifex_Ferry
List_of_World_Organization_of_the_Scout_Movement_members
Ferris_Bueller27s_Day_Off
Word_of_Wisdom
SAT
Quit_India_Movement
Battle_of_Tippecanoe
90210_season_3
Glycogenin
Inventory_turnover
Natural_and_legal_rights
Naruto_the_Movie_Ninja_Clash_in_the_Land_of_Snow
Climate_of_Dubai
Phonograph
2018_Major_League_Baseball_season
List_of_Wales_national_rugby_union_team_records
Visa_requirements_for_United_States_citizens
The_Man_in_the_High_Castle_TV_series
Hairpin_turn
Audit_committee
Mary_Mack
Dichotic_listening_test
I_Drive_Your_Truck
Red_Wing_Shoes
Lymphocyte
Across_the_River_and_into_the_Trees
Fertile_Crescent
Chicago_PD_season_5
United_States_Air_Force_Academy
Reservation_in_India
Rashidun
Super_Bowl_XXXIX
The_Goat_How_I_Met_Your_Mother
Diamond_cubic
As_We_Know_It
Mission_Impossible_film_series
Taurine
Cell_division
To_God_Be_the_Glory
Presbyopia
Beauty_and_the_Beast_2017_soundtrack
Andersen
Plague_of_Athens
Surrender_of_Japan
It27s_a_Jungle_Out_There
Industrial_Revolution
Environmental_issues_in_the_United_States
List_of_Olympic_medalists_in_figure_skating
Epididymis
Disney_Channel
Vredefort_crater
Population_health
Computer_program
Pangaea
Move_Your_Feet
Hawaii_Five-0_2010_TV_series_season_8
Mammas_Don27t_Let_Your_Babies_Grow_Up_to_Be_Cowboys
Public_transport
Jeepers_Creepers_3
Cracking_joints
Venus
Pericardium
Bartholomew_the_Apostle
He_Thinks_He27ll_Keep_Her
Red_giant
Blister_pack
Ride-along
Equal_Credit_Opportunity_Act
List_of_Super_Bowl_records
Teotihuacan
Fargo_TV_series
List_of_The_Vampire_Diaries_episodes
Catch-22
Prisons_in_India
Tyrosine_kinase
MSC_Cruises
Thriller_song
List_of_Coronation_Street_actors
Avon_Park_Florida
American_Airlines_destinations
Boston_Massacre
Police_caution
Agnosticism
Ember
Climate_of_Florida
Hurricane_cocktail
The_Crossing_TV_series
Abigail_Hawk
List_of_United_States_hurricanes
Puppy
A_Walk_to_Remember_novel
Cell_nucleus
Snow_in_Florida
StraussE28093Howe_generational_theory
The_Last_Time_I_Saw_Paris
The_X-Files_season_2
Oakland_Raiders
The_Wrong_Side_of_Heaven_and_the_Righteous_Side_of_Hell_Volume_1
Tug_of_war_at_the_Summer_Olympics
List_of_McLeod27s_Daughters_characters
List_of_American_Revolutionary_War_battles
2017_ACC_Championship_Game
Joseph_N_Welch
Ashley_Abbott
Social_Security_number
Madrid_Derby
United_States_presidential_line_of_succession
Comma_Johanneum
Dallas_Cowboys_Cheerleaders_Making_the_Team
Serial_literature
Prime_Minister_of_France
Royal_Rumble_2018
Ductus_arteriosus
Hold_Back_the_River_James_Bay_song
Dirty_Dancing
Can27t_Pay3F_We27ll_Take_It_Away
Salah
Project_Mc2
Mercedes_Benz_song
List_of_Ohio_High_School_Athletic_Association_championships
Doug_Ross
Business_intelligence
List_of_the_tallest_statues_in_India
Urinary_bladder
Cracker_Barrel
Ideology
Borders_of_India
Major_airlines_of_the_United_States
Sea_captain
Belle_Beauty_and_the_Beast
United_States_House_Committee_on_Rules
Buckingham_Palace
Five_themes_of_geography
List_of_earthquakes_in_New_Zealand
President27s_Daily_Brief
Natural_hazard
Supernatural_season_13
Polar_bear
Japanese_pagoda
Demi-Leigh_Nel-Peters
The_Geographical_Pivot_of_History
Fortnite
Trump_Tower
Super_Bowl_XXXIX
Olivia_Rose_Keegan
Inner_core
Runaways_TV_series
United_States_Chamber_of_Commerce
Angela_Martin
Chris_Gauthier
Mixture
Gene
The_Heart_of_Saturday_Night
Simon_Commission
Real_Ispat_and_Power
William_The_X-Files
Southern_United_States
Poverty_alleviation_programmes_in_India
Mohammad_bin_Salman
Hardball_film
Sugar_Sugar
Seven_deadly_sins
M_S_Swaminathan
Best_Thing_I_Never_Had
Safety_coffin
Classical_order
First_Transcontinental_Railroad
Adventure_Time_season_9
Battle_of_Issus
Neuropsychology
Academy_Award_for_Best_Original_Score
Battle_of_the_Sexes_film
Founding_Fathers_of_the_United_States
Walking_Dead
Purpose_Justin_Bieber_album
Thai_alphabet
John_Dalberg-Acton_1st_Baron_Acton
Table_of_contents
University_of_Michigan_School_of_Public_Health
The_Lion_King_II_Simba27s_Pride
Tachycardia
Los_Angeles_Stadium_at_Hollywood_Park
Rib_vault
I_Don27t_Feel_at_Home_in_This_World_Anymore
Enabling_Act_of_1933
Indian_Ocean
Nucleotide
Bernward_Doors
Mars
Silk_Road
Veto
List_of_the_largest_fast_food_restaurant_chains
The_Curse_of_Oak_Island
Sword_Art_Online_The_Movie_Ordinal_Scale
Crane_machine
Jacques_Cartier
Google_Chrome_version_history
War_ina_Babylon
2014_Winter_Paralympics
Carbon_dioxide
John_Cooper_Clarke
History_of_Germany_during_World_War_I
United_Nations_Security_Council_veto_power
Celsius
Lovin27_You
Gold_reserve
How_to_Make_an_American_Quilt
Ori_and_the_Will_of_the_Wisps
The_Book_Thief_film
Jeannette_Walls
List_of_Nobel_laureates
Private_pilot
South_Korean_won
One_Ring
That27s_So_Raven_season_4
Pure_tone_audiometry
Fibula
Computer_access_control
List_of_40-plus_point_games_by_LeBron_James
List_of_best-selling_girl_groups
Virginia_Dare
Confederate_States_of_America
Big_Five_personality_traits
Ministry_of_Textiles
Philadelphia
Nationalist_faction_Spanish_Civil_War
Raindrops_Keep_Fallin27_on_My_Head
Great_Lakes
Potentiality_and_actuality
Climate_of_South_Carolina
The_Skye_Boat_Song
American_Civil_War
I_Walk_the_Line
Citrate_test
The_Canterbury_Tales
When_Calls_the_Heart
Prescott_Fire_Department
Model_person
Royal_Proclamation_of_1763
Megan_Park
SanterC3ADa
First_Epistle_of_John
De_Beers
Early_skyscrapers
Just_Add_Magic_TV_series
Agamemnon
Great_Barrier_Reef_Marine_Park
Houston_Astros
Ulnar_nerve
Mason_Verger
Can27t_Help_Falling_in_Love
Chief_business_development_officer
Field_of_Dreams
United_States_free_speech_exceptions
2018_Winter_Olympics
Call_Me_by_Your_Name_film
Merit_badge_Boy_Scouts_of_America
Demand_curve
Microsporidia
Philadelphia_Eagles
I_Hear_You_Knocking
Maintenance_and_Welfare_of_Parents_and_Senior_Citizens_Act_2007
Music_history_of_France
Threshold_potential
Newspaper_circulation
Iss_Pyaar_Ko_Kya_Naam_Doon3FEk_Baar_Phir
Minicomputer
Philadelphia_Eagles
Horton_Hears_a_Who_film
History_of_US_foreign_policy
2018_Winter_Olympics_opening_ceremony
Age_of_candidacy
When_Calls_the_Heart
13_Reasons_Why
Sing_2016_American_film
Statute_of_frauds
And_Now_His_Watch_Is_Ended
The_Doris_Day_Show
Lloyds_Bank
List_of_punishments_for_murder_in_the_United_States
Flag_of_Romania
Golden_Nugget_Atlantic_City
Venus
Tobacco_advertising
Honda_CR-V
Economy_of_Youngstown_Ohio
List_of_Prime_Ministers_of_Canada
When_We_First_Met
Health_care_in_the_United_States
Euro
Holland
Obstructing_the_field
American_entry_into_Canada_by_land
Beauty_and_the_Beast_2017_soundtrack
Stream_load
Hypertext_Transfer_Protocol
J_Wellington_Wimpy
Limiting_factor
Lover27s_Leap
Mesosome
Adnan_name
Lenape
Joie_de_vivre
Elections_in_Canada
Patriot_American_Revolution
Gear_train
Wizards_of_Waverly_Place_soundtrack
Hittites
Italy_Everybody_Loves_Raymond
World_Trade_Center_station_PATH
Wave_Hill_walk-off
America27s_Got_Talent_season_5
Lobbying_in_the_United_States
Cytoskeleton
Congressional_oversight
Speed_limits_in_the_United_States
Many_happy_returns_greeting
Fly_Me_to_the_Moon
California_Gold_Rush
Eighth_Amendment_to_the_United_States_Constitution
International_rankings_of_India
History_of_Cape_Town
List_of_people_on_United_States_banknotes
First_Amendment_to_the_United_States_Constitution
The_Last_Man_on_Earth_TV_series
DNA_replication
Capsid
A_Portrait_of_the_Artist_as_a_Young_Man
Hollywood_Video
Say_You_Won27t_Let_Go
Jumping_the_broom
Romance_of_the_Three_Kingdoms_XI
Vice_President_of_the_United_States
When_the_Going_Gets_Tough_the_Tough_Get_Going_song
Gold_mining_in_the_United_States
Panama_Canal
List_of_volcanoes_in_the_United_States
Articles_of_Confederation
Premier_of_the_Northern_Cape
Public_Provident_Fund_India
Periodic_table
Legends_of_Chamberlain_Heights
James_Earl_Jones
English_defamation_law
Dresden_Codex
Glycogen
Arthur_Phillip
Director_of_the_Federal_Bureau_of_Investigation
Uttar_Pradesh_Lokayukta
Malcolm_in_the_Middle
New_England_Patriots
Ocala_Demands
New_Japan_Pro-Wrestling
You_Get_Me_film
Tornadoes_in_the_United_States
Kate_O27Mara
Around_the_Horn
Now_That27s_What_I_Call_Country
User_State_Migration_Tool
List_of_proverbial_phrases
Star_formation
Agonist-antagonist
Judicial_independence
Wit_Studio
The_Man_Who_Invented_Christmas_film
Voyager_1
Net_profit
Leaning_Tower_of_Pisa
Junior_doctor
Continuous_and_Comprehensive_Evaluation
From_Russia_with_Love_soundtrack
The_Chronicles_of_Narnia_The_Lion_the_Witch_and_the_Wardrobe
1946_Cabinet_Mission_to_India
Book_of_Esther
Glory_Glory_Lay_My_Burden_Down
Syrian_Civil_War
PewDiePie
Christmas_dinner
Digital_Revolution
Angel_of_the_North
Sangam_period
The_Son_of_Neptune
National_Stock_Exchange_of_India
The_Smurfs_TV_series
Geothermal_power
Communications_satellite
Bird_nest
Batting_average
Shofar
Calx
God_of_War_Ghost_of_Sparta
Bailee_Madison
Rational_Dress_Society
Bachelor_of_Liberal_Studies
List_of_Presidents_of_Zambia
It_Ain27t_Over_27til_It27s_Over
Golden_State_Warriors
Nancy_Cartwright
Climate_of_North_Dakota
Charlotte_Lucas
The_Shape_of_Water
Where_the_Sidewalk_Ends_poem
Hullabahoos
Unification_of_Karnataka
Dalveer_Bhandari
Love_26_Basketball
List_of_European_countries_by_area
Tad_The_Lost_Explorer
Italian_fashion
Agents_of_SHIELD_season_5
The_One_with_Monica_and_Chandler27s_Wedding
Second_line_parades
Mount_Everest
Ecdysozoa
George_Gray_television_personality
Primary_Rate_Interface
Total_cost
An_Historical_Account_of_Two_Notable_Corruptions_of_Scripture
Second_Great_Awakening
Tabby_cat
Ida_B_Wells
Italian_beef
Gimme_Gimme_Gimme_TV_series
List_of_New_England_hurricanes
List_of_Asian_countries_by_area
Tarapur_Atomic_Power_Station
Rolling_Stone27s_500_Greatest_Albums_of_All_Time
Celebrity_Big_Brother_US_TV_series
Housewarming_party
V_sign
Into_the_Woods_film
Ye_Hai_Mohabbatein
I27m_Gonna_Sit_Right_Down_and_Write_Myself_a_Letter
Inflation
Tyrant
Battle_of_the_Sexes_tennis
Caste
401k
List_of_Canadian_television_stations_available_in_the_United_States
Symbiosis
Federal_government_of_the_United_States
American_Pie_song
Lucknam_Park
List_of_love_and_lust_deities
Microchip_implant_animal
List_of_Premier_League_clubs
Artery
Renaissance
North_KoreaE28093South_Korea_relations
Five_Go_to_Smuggler27s_Top
River_delta
French_colonization_of_Texas
Poverty_in_the_United_States
The_Taming_of_the_Shrew
Qing_dynasty
Arabic_language_influence_on_the_Spanish_language
CategoryFilipino_sociologists
Rockefeller_Center_Christmas_Tree
Treaty_of_Versailles
United_States_budget_process
47th_Academy_Awards

In [52]:
for x in [x for x in chroma_client.list_collections() if "wikiqa" in x.name]:
    chroma_client.delete_collection(x.name)

In [7]:
done = []

In [ ]:
collections = [x.name for x in chroma_client.list_collections()]
for file in Path(DATA_DIR / "processed").glob("nq_question_answer_chunked_embeddings_*.parquet"):
    documents = pl.read_parquet(file)
    for id in tqdm(documents.select("document_url").unique().to_numpy().reshape(-1).tolist()):
        collection_name = f"wikiqa_{extract_title_from_path(id)}"
        # logger.info(collection_name, collection_name in collections)
        if collection_name in collections:
            # logger.info(f"Collection {collection_name} already exists")
            continue
        if file.name + collection_name in done:
            continue
        # logger.info(f"Processing {collection_name}")
        corpus_collection = chroma_client.get_or_create_collection(
            name=collection_name, metadata={"hnsw:space": "cosine"}
        )
        selected_docs = documents.filter(pl.col("document_url") == id)
        corpus_ids = selected_docs.select("unique_id").to_numpy().reshape(-1).tolist()
        corpus_documents = selected_docs.select("chunked_prompt").to_numpy().reshape(-1).tolist()
        metadatas = selected_docs.select("document_url").to_dicts()
        embeddings = selected_docs.select("embedding").to_numpy().reshape(-1).tolist()

        # print(len(corpus_ids), len(corpus_documents), len(metadatas), len(selected_docs))

        collection_add_in_batches(
            collection=corpus_collection,
            ids=corpus_ids,
            texts=corpus_documents,
            embeddings=embeddings,
            metadatas=metadatas,
            batch_size=500,
        )
        done.append(file.name + collection_name)

100%|██████████| 733/733 [00:00<00:00, 118896.47it/s]
100%|██████████| 731/731 [00:00<00:00, 175683.95it/s]
100%|██████████| 707/707 [24:47<00:00,  2.10s/it]
 48%|████▊     | 276/580 [35:00<37:02,  7.31s/it]