In [3]:
from pathlib import Path
import polars as pl
import tiktoken

%load_ext autoreload
%autoreload 2
import sys

sys.path.append(
    "/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/chroma_research_repos/generative-benchmarking"
)

import json
import os
from datetime import datetime
from pathlib import Path

import chromadb
import numpy as np
import pandas as pd
import polars as pl
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from functions.visualize import *
from functions.chroma import *
from functions.embed import *
from functions.evaluate import *
from functions.llm import *
from langchain_text_splitters import RecursiveCharacterTextSplitter
from openai import OpenAI as OpenAIClient
from tqdm.auto import tqdm

from context_is_king.rag_pipeline import DATA_DIR

load_dotenv()
# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
# assert OPENAI_API_KEY is not None, "OPENAI_API_KEY is not set"

ORQ_API_KEY = os.getenv("ORQ_API_KEY")
assert ORQ_API_KEY is not None, "ORQ_API_KEY is not set"

chroma_client = chromadb.PersistentClient(path="../chroma_wikitext")
openai_client = OpenAIClient(api_key=ORQ_API_KEY, base_url="https://api.orq.ai/v2/proxy")

DATA_DIR = Path("/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/") / "data"
(DATA_DIR / "processed").mkdir(parents=True, exist_ok=True)

encoding = tiktoken.encoding_for_model("gpt-4o")

2025-09-14 21:01:02.422 | DEBUG    | context_is_king.rag_pipeline:<module>:32 - DATA_DIR=PosixPath('/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/src/data')

In [4]:
chroma_client.list_collections()

[Collection(name=longmemeval_conversations)]

In [7]:
client = chromadb.PersistentClient(path="../data/chroma_db")
client.list_collections()

[Collection(name=wikitext_nq_question_answer)]

In [6]:
collection = client.get_collection("wikitext_nq_question_answer")

In [13]:
from openai import OpenAI
openai_client = OpenAI(
      api_key=os.getenv("ORQ_API_KEY"),
      base_url="https://api.orq.ai/v2/proxy"
  )
def get_768_embedding(text: str):
      response = openai_client.embeddings.create(
          model="azure/text-embedding-3-small",
          input=text,
          dimensions=768  # Match collection expectation
      )
      return response.data[0].embedding

query_embedding = get_768_embedding("your query")

In [9]:
print(collection.count())
results = collection.query(query_embeddings=query_embedding, n_results=5, where={"quality_filtered": True})

NameError: name 'collection' is not defined

In [15]:
results

{'ids': [[]],
 'embeddings': None,
 'documents': [[]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[]],
 'distances': [[]]}

In [ ]:
from dotenv import load_dotenv
import os

# Load environment properly
load_dotenv()
os.environ['OPENAI_API_KEY'] = os.getenv('ORQ_API_KEY', '')

from context_is_king.models import ModelInterface

# Test with a working GPT model
interface = ModelInterface()
await interface.query_model_async(
    model_name='gemini-2.5-flash',
    prompt='test',
    system_prompt='',
    temperature=0.1,
    max_tokens=100,
    timeout=30,
    max_retries=1,
    base_delay=0,
)

🔗 Initialized Model Interface
📡 API Base URL: https://api.orq.ai/v2/proxy
🤖 Available Models: 13
🔄 Rate Limiting: 5 retries, 1.0s base delay

QueryResult(model_name='gemini-2.5-flash', prompt='test', response='Hello! How can I help you today?', success=True, error_message=None, response_time=0.7588567733764648, prompt_tokens=1, completion_tokens=9, total_tokens=10, estimated_cost=5e-05, temperature=0.1, max_tokens=100, context_size=1, timestamp=1757071541.936629)

In [ ]:
# client.delete_collection("longmemeval_conversations")

In [ ]:
from datasets import load_dataset

ds = load_dataset("Salesforce/wikitext", "wikitext-103-v1")

In [2]:
import polars as pl

df = pl.scan_ndjson("~/Downloads/v1.0 simplified nq dev all.jsonl")
df.head(2).collect()

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ annotatio ┆ document_ ┆ document_ ┆ document_ ┆ … ┆ example_i ┆ long_answ ┆ question_ ┆ question │
│ ns        ┆ html      ┆ title     ┆ tokens    ┆   ┆ d         ┆ er_candid ┆ text      ┆ _tokens  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ates      ┆ ---       ┆ ---      │
│ list[stru ┆ str       ┆ str       ┆ list[stru ┆   ┆ i64       ┆ ---       ┆ str       ┆ list[str │
│ ct[4]]    ┆           ┆           ┆ ct[4]]    ┆   ┆           ┆ list[stru ┆           ┆ ]        │
│           ┆           ┆           ┆           ┆   ┆           ┆ ct[5]]    ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [{null,{9 ┆ <!DOCTYPE ┆ Therefore ┆ [{101,fal ┆ … ┆ 691560647 ┆ [{66428,8 ┆ what do   ┆ ["what", │
│ 2,67824,9 ┆ html>     ┆ sign      ┆ se,92,"Th ┆   ┆ 766896339 ┆ 08,41427, ┆ the 3     ┆ "do", …  │
│ 25,66429, ┆ <HTML     ┆           ┆ erefore"} ┆   ┆ 9         ┆ 14,true}, ┆ dots mean ┆ "math"]  │
│ 808…      ┆ class="c… ┆           ┆ , {…      ┆   ┆           ┆ {4…       ┆ in mat…   ┆          │
│ [{null,{- ┆ <!DOCTYPE ┆ Watchman  ┆ [{100,fal ┆ … ┆ -45059718 ┆ [{43267,1 ┆ when was  ┆ ["when", │
│ 1,-1,-1,- ┆ html>     ┆ (law enfo ┆ se,92,"Wa ┆   ┆ 231740849 ┆ 15,41595, ┆ the writ  ┆ "was", … │
│ 1,-1},[], ┆ <HTML     ┆ rcement)  ┆ tchman"}, ┆   ┆ 26        ┆ 30,true}, ┆ watch     ┆ "who"]   │
│ "NO…      ┆ class="c… ┆           ┆ {1…       ┆   ┆           ┆ {4…       ┆ invent…   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
token_counts = (
    df.with_columns(
        pl.col("document_html")
        .map_elements(lambda x: len(encoding.encode(x)), return_dtype=pl.Int64)
        .alias("document_tokens")
    )
    .select("document_tokens")
    .collect()
)
token_counts

shape: (7_830, 1)
┌─────────────────┐
│ document_tokens │
│ ---             │
│ i64             │
╞═════════════════╡
│ 34241           │
│ 43051           │
│ 82144           │
│ 59866           │
│ 46280           │
│ …               │
│ 58626           │
│ 83301           │
│ 78043           │
│ 112316          │
│ 73662           │
└─────────────────┘

In [ ]:
token_counts.select(
    pl.col("document_tokens").min().alias("min"),
    pl.col("document_tokens").max().alias("max"),
    pl.col("document_tokens").mean().alias("mean"),
)

shape: (1, 3)
┌───────┬────────┬──────────────┐
│ min   ┆ max    ┆ mean         │
│ ---   ┆ ---    ┆ ---          │
│ i64   ┆ i64    ┆ f64          │
╞═══════╪════════╪══════════════╡
│ 15146 ┆ 548918 ┆ 76573.488378 │
└───────┴────────┴──────────────┘

In [ ]:
import altair as alt

alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [ ]:
hist_values = (
    token_counts["document_tokens"]
    .hist(bins=[0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000])
    .with_columns(pl.col("category").cast(pl.Utf8))
)
hist_values

shape: (10, 3)
┌────────────┬──────────────────────┬───────┐
│ breakpoint ┆ category             ┆ count │
│ ---        ┆ ---                  ┆ ---   │
│ f64        ┆ str                  ┆ u32   │
╞════════════╪══════════════════════╪═══════╡
│ 50000.0    ┆ [0.0, 50000.0]       ┆ 3050  │
│ 100000.0   ┆ (50000.0, 100000.0]  ┆ 3024  │
│ 150000.0   ┆ (100000.0, 150000.0] ┆ 1081  │
│ 200000.0   ┆ (150000.0, 200000.0] ┆ 381   │
│ 250000.0   ┆ (200000.0, 250000.0] ┆ 156   │
│ 300000.0   ┆ (250000.0, 300000.0] ┆ 81    │
│ 350000.0   ┆ (300000.0, 350000.0] ┆ 37    │
│ 400000.0   ┆ (350000.0, 400000.0] ┆ 7     │
│ 450000.0   ┆ (400000.0, 450000.0] ┆ 1     │
│ 500000.0   ┆ (450000.0, 500000.0] ┆ 3     │
└────────────┴──────────────────────┴───────┘

In [24]:
hist_values.plot.bar(y="count", x=alt.X("category", sort=None))

alt.Chart(...)

In [19]:
len([x for x in samples[0]["long_answer_candidates"] if x["top_level"] == True])

14

In [ ]:
samples = df.head().collect().to_pandas().to_dict(orient="index")
samples

In [15]:
len(samples[0]["document_html"])

103968

In [ ]:
tokens = encoding.encode(samples[0]["document_html"])

len(tokens)

34241

In [ ]:
# Alternative simpler approach for mode calculation
from collections import Counter


def get_mode_tokens(annotations):
    """Get mode of start and end tokens from annotations, excluding -1 values"""
    start_tokens = []
    end_tokens = []

    for annotation in annotations:
        if "long_answer" in annotation:
            start_token = annotation["long_answer"].get("start_token", -1)
            end_token = annotation["long_answer"].get("end_token", -1)

            if start_token != -1:
                start_tokens.append(start_token)
            if end_token != -1:
                end_tokens.append(end_token)

    if not start_tokens or not end_tokens:
        return [-1, -1]

    # Get mode (most common value) or None if no valid tokens
    mode_start = Counter(start_tokens).most_common(1)[0][0] if start_tokens else -1
    mode_end = Counter(end_tokens).most_common(1)[0][0] if end_tokens else -1

    return mode_start, mode_end


# Apply to DataFrame using map_elements (for complex operations)
df_with_simple_mode = (
    df.with_columns(
        [
            pl.col("annotations")
            .map_elements(lambda x: get_mode_tokens(x), return_dtype=pl.List(pl.Int64))
            .alias("mode_tokens")
        ]
    )
    .with_columns(
        [
            pl.col("mode_tokens").list.first().alias("mode_start_token"),
            pl.col("mode_tokens").list.last().alias("mode_end_token"),
        ]
    )
    # .with_columns(
    #     [
    #         pl.col("mode_start_token").map_elements(lambda x: print(f"start: {x}, type: {type(x)}") or x),
    #         pl.col("mode_end_token").map_elements(lambda x: print(f"end: {x}, type: {type(x)}") or x),
    #         pl.col("document_tokens").map_elements(lambda x: print(f"len: {len(x)}, {x[:3]}")),
    #     ]
    # )
    .with_columns(
        [
            # Create sliced tokens using mode values
            pl.when((pl.col("mode_start_token") != -1) & (pl.col("mode_end_token") != -1))
            .then(
                pl.col("document_tokens").list.slice(
                    pl.col("mode_start_token"), pl.col("mode_end_token") - pl.col("mode_start_token")
                )
            )
            .otherwise(None)
            .alias("sliced_document_tokens_simple_mode")
        ]
    )
    .with_columns(
        pl.col("sliced_document_tokens_simple_mode")
        .list.eval(pl.element().struct.field("token"))
        .list.join(" ")
        .alias("long_answer_text")
    )
)

print("DataFrame with simple mode calculation:")
df_with_simple_mode.select("document_url", "question_text", "long_answer_text", "document_html").sink_parquet(
    DATA_DIR / "processed/nq_question_answer.parquet"
)

DataFrame with simple mode calculation:

In [55]:
df_with_simple_mode.select("document_url", "question_text", "long_answer_text", "document_html").collect()

KeyboardInterrupt:

## Create Embeddings

In [32]:
wiki_qa = pl.scan_parquet(DATA_DIR / "processed/nq_question_answer.parquet")
print(wiki_qa.select(pl.len()).collect())
wiki_qa.head().collect()

shape: (1, 1)
┌──────┐
│ len  │
│ ---  │
│ u32  │
╞══════╡
│ 7830 │
└──────┘

shape: (5, 4)
┌──────────────────────────┬──────────────────────────┬──────────────────────────┬─────────────────┐
│ document_url             ┆ question_text            ┆ long_answer_text         ┆ document_html   │
│ ---                      ┆ ---                      ┆ ---                      ┆ ---             │
│ str                      ┆ str                      ┆ str                      ┆ str             │
╞══════════════════════════╪══════════════════════════╪══════════════════════════╪═════════════════╡
│ https://en.wikipedia.org ┆ what do the 3 dots mean  ┆ <P> In logical argument  ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ in mat…                  ┆ and ma…                  ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ when was the writ watch  ┆ null                     ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ invent…                  ┆                          ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ who wrote the song       ┆ <P> `` Photograph '' is  ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ photograph …             ┆ a song…                  ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ who is playing the       ┆ <P> The Super Bowl 50    ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ halftime sh…             ┆ Halftime…                ┆ <HTML class="c… │
│ https://en.wikipedia.org ┆ star wars the clone wars ┆ <P> Matthew MacKendree   ┆ <!DOCTYPE html> │
│ //w/in…                  ┆ anaki…                   ┆ `` Matt…                 ┆ <HTML class="c… │
└──────────────────────────┴──────────────────────────┴──────────────────────────┴─────────────────┘

In [47]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1900, chunk_overlap=200)
wiki_qa.with_columns(
    pl.col("document_html")
    .map_elements(lambda x: BeautifulSoup(x, "html.parser").get_text(), return_dtype=pl.String)
    .map_elements(lambda x: text_splitter.split_text(x), return_dtype=pl.List(pl.String))
    .alias("chunked_prompt")
).sink_parquet(DATA_DIR / "processed/nq_question_answer_chunked.parquet")

In [48]:
wiki_chunked = pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked.parquet")

In [49]:
from uuid import uuid4
import re


def generate_ids() -> str:
    return str(uuid4())


documents = (
    pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked.parquet")
    # .limit(50)
    .select("chunked_prompt", "document_url")
    .explode("chunked_prompt")
    .with_columns(
        pl.col("chunked_prompt").str.len_chars().alias("context_length"),
        pl.col("chunked_prompt")
        .map_elements(lambda x: len(encoding.encode(x)), return_dtype=pl.Int64)
        .alias("token_count"),
        pl.col("chunked_prompt").map_elements(lambda x: re.sub(r"\n{3,}", "\n\n", x), return_dtype=pl.String()),
        pl.col("chunked_prompt").map_elements(lambda _: generate_ids(), return_dtype=pl.String()).alias("unique_id"),
    )
).collect()
# documents = documents.with_columns(pl.Series(generate_ids(documents.height)).alias("unique_id"))
print(documents.shape)
print(documents.select(pl.col("context_length").mean()))
print(documents.select(pl.col("token_count").mean().alias("avg_tokens")))
documents.head()

fn_target = DATA_DIR / "processed/nq_question_answer_chunked_exploded.delta"

documents.write_delta(fn_target, mode="overwrite")

(212044, 5)
shape: (1, 1)
┌────────────────┐
│ context_length │
│ ---            │
│ f64            │
╞════════════════╡
│ 1382.830153    │
└────────────────┘
shape: (1, 1)
┌────────────┐
│ avg_tokens │
│ ---        │
│ f64        │
╞════════════╡
│ 355.43375  │
└────────────┘

In [3]:
documents = pl.read_delta(DATA_DIR / "processed/nq_question_answer_chunked_exploded.delta")

In [8]:
corpus_ids = documents.select("unique_id").to_numpy().reshape(-1).tolist()
corpus_documents = documents.select("chunked_prompt").to_numpy().reshape(-1).tolist()
# metadatas = documents.select("document_url").to_dicts()
# print(type(corpus_ids), type(corpus_documents), type(metadatas))

batch_size = 50_000
for batch in range(0, len(corpus_documents), batch_size):
    selected_documents = documents.filter(pl.col("unique_id").is_in(corpus_ids[batch : batch + batch_size]))
    corpus_embeddings = openai_embed_in_batches(
        openai_client=openai_client,
        model="azure/text-embedding-3-small",
        texts=selected_documents.select("chunked_prompt").to_numpy().reshape(-1).tolist(),
        batch_size=100,
    )
    selected_documents = selected_documents.with_columns(pl.Series(corpus_embeddings).alias("embedding")).write_delta(
        DATA_DIR / f"processed/nq_question_answer_chunked_embeddings.delta", mode="append"
    )

Processing OpenAI batches: 100%|██████████| 500/500 [17:30<00:00,  2.10s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [17:28<00:00,  2.10s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [17:45<00:00,  2.13s/it]
Processing OpenAI batches: 100%|██████████| 500/500 [17:33<00:00,  2.11s/it]
Processing OpenAI batches: 100%|██████████| 121/121 [04:08<00:00,  2.06s/it]

In [23]:
lazy_chunks = pl.scan_delta(DATA_DIR / f"processed/nq_question_answer_chunked_embeddings.delta")

In [24]:
lazy_chunks.with_columns(
    pl.col('document_url')
    .map_elements(lambda x: extract_title_from_path(x), return_dtype=pl.String())
    .alias('collection_suffix')
).sink_parquet(DATA_DIR / "processed/nq_question_answer_chunked_embeddings_with_suffix.parquet")

In [4]:
pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked_embeddings_with_suffix.parquet").collect_schema()

Schema([('chunked_prompt', String),
        ('document_url', String),
        ('context_length', Int32),
        ('token_count', Int64),
        ('unique_id', String),
        ('embedding', List(Float64)),
        ('collection_suffix', String)])

In [5]:
import re

def extract_title_from_path(url):
    pattern = r"title=([^&]+)"
    match = re.search(pattern, url)
    return (
        match.group(1).translate({ord(c): None for c in "!@#$():%,^&!/+=."}).strip("!@#$():%,^&!/+=._")
        if match
        else None
    )


# strings = documents.select("document_url").unique().to_numpy().reshape(-1).tolist()

# for doc in strings:
#     print(extract_title_from_path(doc))
#     break

In [10]:
for x in [x for x in chroma_client.list_collections() if "wikiqa" in x.name]:
    chroma_client.delete_collection(x.name)

In [12]:
done = set()

In [8]:
import polars as pl
allowed_df = pl.scan_parquet(DATA_DIR / "processed/nq_question_answer_chunked_embeddings_with_suffix.parquet")
approved_url = allowed_df.group_by('document_url').len().filter(pl.col('len') > 100).collect()['document_url'].to_list()

In [17]:
import gc
collections = [x.name for x in chroma_client.list_collections()]
# for file in Path(DATA_DIR / "processed").glob("nq_question_answer_chunked_embeddings_*.parquet"):
nq_with_embeddings = pl.read_delta(DATA_DIR / "processed/nq_question_answer_chunked_embeddings.delta")
for i, (name, chunk) in tqdm(enumerate(nq_with_embeddings.group_by('document_url')), total=nq_with_embeddings.select(pl.col('document_url').n_unique()).collect().item()):
    doc_url = name[0]

    # for id in tqdm(chunk.select("document_url").unique().to_numpy().reshape(-1).tolist()):
    if doc_url not in approved_url:
        continue
    print('Processing ', doc_url)
    collection_name = f"wikiqa_{extract_title_from_path(doc_url)}"
    cache_name = f"{collection_name}_{i}"
    # logger.info(collection_name, collection_name in collections)
    if collection_name in collections:
        chroma_client.delete_collection(collection_name)

    # logger.info(f"Processing {collection_name}")
    corpus_collection = chroma_client.get_or_create_collection(
        name=collection_name, metadata={"hnsw:space": "cosine"}
    )
    if collection_name in collections:
        existing_ids = corpus_collection.get()['ids']
    selected_docs = chunk.filter(pl.col("document_url") == doc_url).filter(~pl.col("unique_id").is_in(existing_ids))
    corpus_ids = selected_docs.select("unique_id").to_numpy().reshape(-1).tolist()
    corpus_documents = selected_docs.select("chunked_prompt").to_numpy().reshape(-1).tolist()
    metadatas = [{**x, 'cache_name': cache_name, 'collection_name': collection_name} for x in selected_docs.select("document_url").to_dicts()]
    embeddings = selected_docs.select("embedding").to_numpy().reshape(-1).tolist()

    # print(len(corpus_ids), len(corpus_documents), len(metadatas), len(selected_docs))

    collection_add_in_batches(
        collection=corpus_collection,
        ids=corpus_ids,
        texts=corpus_documents,
        embeddings=embeddings,
        metadatas=metadatas,
        batch_size=500,
    )
    done.add(f"{collection_name}_{i}")
    del embeddings, corpus_documents, corpus_ids, metadatas
    gc.collect()

Processing  https://en.wikipedia.org//w/index.php?title=History_of_the_United_States&amp;oldid=822282210
Processing  https://en.wikipedia.org//w/index.php?title=List_of_performances_on_Top_of_the_Pops&amp;oldid=818121506
Processing  https://en.wikipedia.org//w/index.php?title=Christmas&amp;oldid=822099419
Processing  https://en.wikipedia.org//w/index.php?title=Solar_eclipse_of_August_21,_2017&amp;oldid=807052172
Processing  https://en.wikipedia.org//w/index.php?title=Human_evolution&amp;oldid=821005897
Processing  https://en.wikipedia.org//w/index.php?title=RMS_Titanic&amp;oldid=805999140
Processing  https://en.wikipedia.org//w/index.php?title=I_Can_Only_Imagine_(MercyMe_song)&amp;oldid=837313786
Processing  https://en.wikipedia.org//w/index.php?title=The_Curse_of_Oak_Island&amp;oldid=832882458
Processing  https://en.wikipedia.org//w/index.php?title=Star_Trek:_Discovery&amp;oldid=838430258
Processing  https://en.wikipedia.org//w/index.php?title=Cell_nucleus&amp;oldid=811624751
Processing  https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882
Processing  https://en.wikipedia.org//w/index.php?title=Age_of_Enlightenment&amp;oldid=819535951
Processing  https://en.wikipedia.org//w/index.php?title=I%27m_a_Celebrity...Get_Me_Out_of_Here!_(UK_TV_series)&amp;oldid=816633278
Processing  https://en.wikipedia.org//w/index.php?title=Atomic_bombings_of_Hiroshima_and_Nagasaki&amp;oldid=838327110
Processing  https://en.wikipedia.org//w/index.php?title=History_of_the_Philadelphia_Eagles&amp;oldid=833514063
Processing  https://en.wikipedia.org//w/index.php?title=Christmas_traditions&amp;oldid=821913308
Processing  https://en.wikipedia.org//w/index.php?title=State_of_the_Union&amp;oldid=836214476
Processing  https://en.wikipedia.org//w/index.php?title=Second_Amendment_to_the_United_States_Constitution&amp;oldid=838227052
Processing  https://en.wikipedia.org//w/index.php?title=Captain_America:_Civil_War&amp;oldid=819487324
Processing  https://en.wikipedia.org//w/index.php?title=List_of_DreamWorks_Dragons_episodes&amp;oldid=835974760
Processing  https://en.wikipedia.org//w/index.php?title=FA_Cup&amp;oldid=838026457
Processing  https://en.wikipedia.org//w/index.php?title=Singapore&amp;oldid=838168836
Processing  https://en.wikipedia.org//w/index.php?title=Articles_of_Confederation&amp;oldid=838541193
Processing  https://en.wikipedia.org//w/index.php?title=Puerto_Rico&amp;oldid=822215686
Processing  https://en.wikipedia.org//w/index.php?title=Beijing&amp;oldid=807340674
Processing  https://en.wikipedia.org//w/index.php?title=Scottish_independence_referendum,_2014&amp;oldid=818291895
Processing  https://en.wikipedia.org//w/index.php?title=Wikipedia:WikiProject_Film/Recognized_content/Did_you_know&amp;oldid=835261538
Processing  https://en.wikipedia.org//w/index.php?title=Not_in_This_Lifetime..._Tour&amp;oldid=807238843
Processing  https://en.wikipedia.org//w/index.php?title=Royal_Rumble&amp;oldid=837792387
Processing  https://en.wikipedia.org//w/index.php?title=Sgt._Pepper%27s_Lonely_Hearts_Club_Band&amp;oldid=838109434
Processing  https://en.wikipedia.org//w/index.php?title=American_entry_into_World_War_I&amp;oldid=822020133
Processing  https://en.wikipedia.org//w/index.php?title=Cold_War&amp;oldid=822330569
Processing  https://en.wikipedia.org//w/index.php?title=American_Civil_War&amp;oldid=818048748
Processing  https://en.wikipedia.org//w/index.php?title=Gulf_War&amp;oldid=819431369
Processing  https://en.wikipedia.org//w/index.php?title=United_States_corporate_law&amp;oldid=816421762
Processing  https://en.wikipedia.org//w/index.php?title=On_the_Origin_of_Species&amp;oldid=836566097
Processing  https://en.wikipedia.org//w/index.php?title=History_of_evolutionary_thought&amp;oldid=836716735
Processing  https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=821291580
Processing  https://en.wikipedia.org//w/index.php?title=Panama_Canal&amp;oldid=822293104
Processing  https://en.wikipedia.org//w/index.php?title=Communist_Party_of_the_Soviet_Union&amp;oldid=838213175
Processing  https://en.wikipedia.org//w/index.php?title=RMS_Titanic&amp;oldid=838311942
Processing  https://en.wikipedia.org//w/index.php?title=United_States_Congress&amp;oldid=838397296
Processing  https://en.wikipedia.org//w/index.php?title=Oakland_Raiders&amp;oldid=807231707
Processing  https://en.wikipedia.org//w/index.php?title=United_Kingdom%E2%80%93United_States_relations&amp;oldid=838209157
Processing  https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027
Processing  https://en.wikipedia.org//w/index.php?title=Mount_Everest&amp;oldid=838344848
Processing  https://en.wikipedia.org//w/index.php?title=2017_World_Series&amp;oldid=822322227
Processing  https://en.wikipedia.org//w/index.php?title=Soviet_Union&amp;oldid=819424184
Processing  https://en.wikipedia.org//w/index.php?title=Hawaii&amp;oldid=821257022
Processing  https://en.wikipedia.org//w/index.php?title=Christmas&amp;oldid=838514133
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Dragon_Ball_Super_episodes&amp;oldid=838398340
Processing  https://en.wikipedia.org//w/index.php?title=Walmart&amp;oldid=822180680
Processing  https://en.wikipedia.org//w/index.php?title=Star_Wars:_The_Force_Awakens&amp;oldid=819455533
Processing  https://en.wikipedia.org//w/index.php?title=Super_Bowl_LII&amp;oldid=838090435
Processing  https://en.wikipedia.org//w/index.php?title=Tobacco_advertising&amp;oldid=838426645
Processing  https://en.wikipedia.org//w/index.php?title=RMS_Titanic&amp;oldid=817702208
Processing  https://en.wikipedia.org//w/index.php?title=Hellenistic_period&amp;oldid=838538324
Processing  https://en.wikipedia.org//w/index.php?title=Flag_of_the_United_States&amp;oldid=838516879
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Dragon_Ball_Super_episodes&amp;oldid=819539421
Processing  https://en.wikipedia.org//w/index.php?title=Treaty_of_Versailles&amp;oldid=838113493
Processing  https://en.wikipedia.org//w/index.php?title=East_India_Company&amp;oldid=838456009
Processing  https://en.wikipedia.org//w/index.php?title=History_of_the_United_States_Democratic_Party&amp;oldid=835692980
Processing  https://en.wikipedia.org//w/index.php?title=Michigan_Wolverines_men%27s_basketball&amp;oldid=838088704
Processing  https://en.wikipedia.org//w/index.php?title=The_Taming_of_the_Shrew&amp;oldid=837432424
Processing  https://en.wikipedia.org//w/index.php?title=Comma_Johanneum&amp;oldid=832571922
Processing  https://en.wikipedia.org//w/index.php?title=Axis_powers&amp;oldid=821485811
Processing  https://en.wikipedia.org//w/index.php?title=Manhattan_Project&amp;oldid=821380031
Processing  https://en.wikipedia.org//w/index.php?title=Sun&amp;oldid=837428242
Processing  https://en.wikipedia.org//w/index.php?title=American_Civil_War&amp;oldid=822060323
Processing  https://en.wikipedia.org//w/index.php?title=Industrial_Revolution&amp;oldid=816711474
Processing  https://en.wikipedia.org//w/index.php?title=Battle_of_Britain&amp;oldid=838541253
Processing  https://en.wikipedia.org//w/index.php?title=Statue_of_Liberty&amp;oldid=836105581
Processing  https://en.wikipedia.org//w/index.php?title=Native_Americans_in_the_United_States&amp;oldid=838207968
Processing  https://en.wikipedia.org//w/index.php?title=History_of_chemistry&amp;oldid=803775631
Processing  https://en.wikipedia.org//w/index.php?title=Fifty_Shades_of_Grey_(film)&amp;oldid=837933868
Processing  https://en.wikipedia.org//w/index.php?title=New_York_City_Subway&amp;oldid=837547834
Processing  https://en.wikipedia.org//w/index.php?title=Golden_State_Warriors&amp;oldid=838213686
Processing  https://en.wikipedia.org//w/index.php?title=Super_Bowl_XXXIX&amp;oldid=837644458
Processing  https://en.wikipedia.org//w/index.php?title=Tom_Brady&amp;oldid=837596033
Processing  https://en.wikipedia.org//w/index.php?title=Romanticism&amp;oldid=822003673
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Fairy_Tail_episodes&amp;oldid=838439987
Processing  https://en.wikipedia.org//w/index.php?title=Berlin_Wall&amp;oldid=837372486
Processing  https://en.wikipedia.org//w/index.php?title=Extinction&amp;oldid=822369329
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Olympic_Games_host_cities&amp;oldid=837813982
Processing  https://en.wikipedia.org//w/index.php?title=List_of_highest-grossing_films&amp;oldid=819523645
Processing  https://en.wikipedia.org//w/index.php?title=Roman_Empire&amp;oldid=816488049
Processing  https://en.wikipedia.org//w/index.php?title=Cristiano_Ronaldo&amp;oldid=807219735
Processing  https://en.wikipedia.org//w/index.php?title=Houston_Astros&amp;oldid=818491983
Processing  https://en.wikipedia.org//w/index.php?title=American_Revolution&amp;oldid=806857204
Processing  https://en.wikipedia.org//w/index.php?title=God_of_War_(franchise)&amp;oldid=838473441
Processing  https://en.wikipedia.org//w/index.php?title=Bay_of_Pigs_Invasion&amp;oldid=817526436
Processing  https://en.wikipedia.org//w/index.php?title=Minnesota_Vikings&amp;oldid=838154686
Processing  https://en.wikipedia.org//w/index.php?title=Macedonia_(ancient_kingdom)&amp;oldid=834198635
Processing  https://en.wikipedia.org//w/index.php?title=Republic_of_Ireland&amp;oldid=837611704
Processing  https://en.wikipedia.org//w/index.php?title=French_Revolution&amp;oldid=837799097
Processing  https://en.wikipedia.org//w/index.php?title=History_of_scientific_method&amp;oldid=838272594
Processing  https://en.wikipedia.org//w/index.php?title=Chinese_New_Year&amp;oldid=837556606
Processing  https://en.wikipedia.org//w/index.php?title=History_of_women_in_the_United_States&amp;oldid=822183230
Processing  https://en.wikipedia.org//w/index.php?title=Zimbabwe&amp;oldid=819529415
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Teenage_Mutant_Ninja_Turtles_characters&amp;oldid=817759179
Processing  https://en.wikipedia.org//w/index.php?title=Origins_of_the_American_Civil_War&amp;oldid=820272600
Processing  https://en.wikipedia.org//w/index.php?title=History_of_U.S._foreign_policy&amp;oldid=822368555
Processing  https://en.wikipedia.org//w/index.php?title=New_Deal&amp;oldid=838174796
Processing  https://en.wikipedia.org//w/index.php?title=Mount_Everest&amp;oldid=818707781
Processing  https://en.wikipedia.org//w/index.php?title=Economic_history_of_the_United_States&amp;oldid=822091932
Processing  https://en.wikipedia.org//w/index.php?title=Beauty_and_the_Beast_(2017_film)&amp;oldid=819457516
Processing  https://en.wikipedia.org//w/index.php?title=Art_Deco&amp;oldid=816580231
Processing  https://en.wikipedia.org//w/index.php?title=Australian_Army_during_World_War_II&amp;oldid=834216537
Processing  https://en.wikipedia.org//w/index.php?title=List_of_best-selling_music_artists&amp;oldid=838547572
Processing  https://en.wikipedia.org//w/index.php?title=Brown_v._Board_of_Education&amp;oldid=836852820
Processing  https://en.wikipedia.org//w/index.php?title=Alkali_metal&amp;oldid=813586499
Processing  https://en.wikipedia.org//w/index.php?title=War_of_1812&amp;oldid=817772971
Processing  https://en.wikipedia.org//w/index.php?title=French_Revolution&amp;oldid=818778645
Processing  https://en.wikipedia.org//w/index.php?title=History_of_the_Internet&amp;oldid=837160871
Processing  https://en.wikipedia.org//w/index.php?title=Stranger_Things&amp;oldid=822291943
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Olympic_medalists_in_figure_skating&amp;oldid=837025106
Processing  https://en.wikipedia.org//w/index.php?title=Acronym&amp;oldid=838325318
Processing  https://en.wikipedia.org//w/index.php?title=Harry_Potter_(film_series)&amp;oldid=836678261
Processing  https://en.wikipedia.org//w/index.php?title=Clemson_Tigers_football&amp;oldid=821890543
Processing  https://en.wikipedia.org//w/index.php?title=Lobbying_in_the_United_States&amp;oldid=818654533
Processing  https://en.wikipedia.org//w/index.php?title=The_Bronx&amp;oldid=837798422
Processing  https://en.wikipedia.org//w/index.php?title=Economy_of_the_United_States&amp;oldid=837509121
Processing  https://en.wikipedia.org//w/index.php?title=Indian_Rebellion_of_1857&amp;oldid=821933492
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Game_of_Thrones_characters&amp;oldid=838019032
Processing  https://en.wikipedia.org//w/index.php?title=Floyd_Mayweather_Jr.&amp;oldid=838403674
Processing  https://en.wikipedia.org//w/index.php?title=Hawaii&amp;oldid=819396917
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Game_of_Thrones_characters&amp;oldid=822351965
Processing  https://en.wikipedia.org//w/index.php?title=Lionel_Messi&amp;oldid=837695305
Processing  https://en.wikipedia.org//w/index.php?title=List_of_The_Flash_episodes&amp;oldid=838448447
Processing  https://en.wikipedia.org//w/index.php?title=Chloroplast&amp;oldid=837447917
Processing  https://en.wikipedia.org//w/index.php?title=Roman_Empire&amp;oldid=838251609
Processing  https://en.wikipedia.org//w/index.php?title=List_of_smoking_bans_in_the_United_States&amp;oldid=837461388
Processing  https://en.wikipedia.org//w/index.php?title=History_of_South_America&amp;oldid=819211677
Processing  https://en.wikipedia.org//w/index.php?title=Muhammad_Ali&amp;oldid=837872787
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Malcolm_in_the_Middle_episodes&amp;oldid=837972349
Processing  https://en.wikipedia.org//w/index.php?title=Eastern_Orthodox_Church&amp;oldid=838470752
Processing  https://en.wikipedia.org//w/index.php?title=Colonial_history_of_the_United_States&amp;oldid=806578243
Processing  https://en.wikipedia.org//w/index.php?title=Romanticism&amp;oldid=818798844
Processing  https://en.wikipedia.org//w/index.php?title=Game_of_Thrones&amp;oldid=806885945
Processing  https://en.wikipedia.org//w/index.php?title=Tom_Brady&amp;oldid=819498413
Processing  https://en.wikipedia.org//w/index.php?title=Indian_Rebellion_of_1857&amp;oldid=819296641
Processing  https://en.wikipedia.org//w/index.php?title=Indian_Rebellion_of_1857&amp;oldid=838494930
Processing  https://en.wikipedia.org//w/index.php?title=List_of_The_Next_Step_episodes&amp;oldid=837737769
Processing  https://en.wikipedia.org//w/index.php?title=Riverdale_(2017_TV_series)&amp;oldid=822314521
Processing  https://en.wikipedia.org//w/index.php?title=Qing_dynasty&amp;oldid=838299439
Processing  https://en.wikipedia.org//w/index.php?title=The_Haves_and_the_Have_Nots_(TV_series)&amp;oldid=837874160
Processing  https://en.wikipedia.org//w/index.php?title=Syrian_Civil_War&amp;oldid=838178617
Processing  https://en.wikipedia.org//w/index.php?title=United_States_Postal_Service&amp;oldid=838320636
Processing  https://en.wikipedia.org//w/index.php?title=National_debt_of_the_United_States&amp;oldid=806680301
Processing  https://en.wikipedia.org//w/index.php?title=Gerald_Ford&amp;oldid=807079147
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Orange_Is_the_New_Black_characters&amp;oldid=834396787
Processing  https://en.wikipedia.org//w/index.php?title=Lobbying_in_the_United_States&amp;oldid=837081139
Processing  https://en.wikipedia.org//w/index.php?title=Reconstruction_Era&amp;oldid=821997502
Processing  https://en.wikipedia.org//w/index.php?title=Photosynthesis&amp;oldid=818857447
Processing  https://en.wikipedia.org//w/index.php?title=United_States_Constitution&amp;oldid=838537837
Processing  https://en.wikipedia.org//w/index.php?title=Philadelphia_Eagles&amp;oldid=837324291
Processing  https://en.wikipedia.org//w/index.php?title=Beauty_and_the_Beast_(2017_film)&amp;oldid=822326105
Processing  https://en.wikipedia.org//w/index.php?title=Nuclear_power&amp;oldid=838546346
Processing  https://en.wikipedia.org//w/index.php?title=Kentucky_Wildcats_men%27s_basketball&amp;oldid=836618916
Processing  https://en.wikipedia.org//w/index.php?title=Miami_Hurricanes_football&amp;oldid=821320639
Processing  https://en.wikipedia.org//w/index.php?title=New_Deal&amp;oldid=806858713
Processing  https://en.wikipedia.org//w/index.php?title=Grey%27s_Anatomy&amp;oldid=819396561
Processing  https://en.wikipedia.org//w/index.php?title=Big_Sur&amp;oldid=821993565
Processing  https://en.wikipedia.org//w/index.php?title=War_of_1812&amp;oldid=837424264
Processing  https://en.wikipedia.org//w/index.php?title=It%27s_a_Wonderful_Life&amp;oldid=820263661
Processing  https://en.wikipedia.org//w/index.php?title=Europe&amp;oldid=822337708
Processing  https://en.wikipedia.org//w/index.php?title=San_Francisco_49ers&amp;oldid=819302721
Processing  https://en.wikipedia.org//w/index.php?title=War_of_1812&amp;oldid=822351702
Processing  https://en.wikipedia.org//w/index.php?title=First_Battle_of_Bull_Run&amp;oldid=836552195
Processing  https://en.wikipedia.org//w/index.php?title=Spanish_Civil_War&amp;oldid=838550545
Processing  https://en.wikipedia.org//w/index.php?title=Ric_Flair&amp;oldid=819432875
Processing  https://en.wikipedia.org//w/index.php?title=Cuba&amp;oldid=819282005
Processing  https://en.wikipedia.org//w/index.php?title=The_Phantom_of_the_Opera_(1986_musical)&amp;oldid=838349429
Processing  https://en.wikipedia.org//w/index.php?title=World_War_I&amp;oldid=838276828
Processing  https://en.wikipedia.org//w/index.php?title=Speed_limits_in_the_United_States_by_jurisdiction&amp;oldid=838079722
Processing  https://en.wikipedia.org//w/index.php?title=The_Dark_Side_of_the_Moon&amp;oldid=838533801
Processing  https://en.wikipedia.org//w/index.php?title=Chernobyl_disaster&amp;oldid=819490863
Processing  https://en.wikipedia.org//w/index.php?title=When_Calls_the_Heart&amp;oldid=838349951
Processing  https://en.wikipedia.org//w/index.php?title=Alabama&amp;oldid=806918792
Processing  https://en.wikipedia.org//w/index.php?title=New_Spain&amp;oldid=821187685
Processing  https://en.wikipedia.org//w/index.php?title=Ash_Wednesday&amp;oldid=830825344
Processing  https://en.wikipedia.org//w/index.php?title=English_contract_law&amp;oldid=814204638
Processing  https://en.wikipedia.org//w/index.php?title=World_War_I&amp;oldid=822330589
Processing  https://en.wikipedia.org//w/index.php?title=Sound_film&amp;oldid=816897569
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Miraculous:_Tales_of_Ladybug_%26_Cat_Noir_episodes&amp;oldid=838440654
Processing  https://en.wikipedia.org//w/index.php?title=Tower_of_London&amp;oldid=838206414
Processing  https://en.wikipedia.org//w/index.php?title=Second_Industrial_Revolution&amp;oldid=821743382
Processing  https://en.wikipedia.org//w/index.php?title=Superman&amp;oldid=838280019
Processing  https://en.wikipedia.org//w/index.php?title=List_of_festivals_in_the_Philippines&amp;oldid=828200892
Processing  https://en.wikipedia.org//w/index.php?title=Battles_of_Saratoga&amp;oldid=818158715
Processing  https://en.wikipedia.org//w/index.php?title=Financial_crisis_of_2007%E2%80%932008&amp;oldid=837459313
Processing  https://en.wikipedia.org//w/index.php?title=History_of_Vietnam&amp;oldid=837807502
Processing  https://en.wikipedia.org//w/index.php?title=Saudi_Arabia&amp;oldid=837987458
Processing  https://en.wikipedia.org//w/index.php?title=Supreme_Court_of_the_United_States&amp;oldid=837913212
Processing  https://en.wikipedia.org//w/index.php?title=History_of_Australia&amp;oldid=818869652
Processing  https://en.wikipedia.org//w/index.php?title=Age_of_Discovery&amp;oldid=817850695
Processing  https://en.wikipedia.org//w/index.php?title=First_Amendment_to_the_United_States_Constitution&amp;oldid=821210814
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Marvel_Comics_characters:_B&amp;oldid=818754596
Processing  https://en.wikipedia.org//w/index.php?title=International_Space_Station&amp;oldid=806438749
Processing  https://en.wikipedia.org//w/index.php?title=United_States&amp;oldid=807272487
Processing  https://en.wikipedia.org//w/index.php?title=List_of_Marvel_Cinematic_Universe_films&amp;oldid=819489006

In [17]:
selected_docs.select("document_url").to_dicts()

[{'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'},
 {'document_url': 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027'}]

In [11]:
len(chroma_client.list_collections())

3752

In [12]:
import deltalake
from deltalake.table import TableOptimizer

non_similar_samples = []

for collection_name in tqdm([x for x in chroma_client.list_collections() if "wikiqa" in x.name][:100]):
    corpus_collection = chroma_client.get_collection(name=collection_name.name)
    collection_samples = []
    corpus = get_collection_items(collection=corpus_collection)
    vals = [
        {
            "collection": collection_name.name,
            "id": id,
            "document": item["document"],
            "embedding": item["embedding"].tolist(),
        }
        for id, item in corpus.items()
    ]
    df = pl.DataFrame(
        vals, schema={"collection": pl.Utf8, "id": pl.Utf8, "document": pl.Utf8, "embedding": pl.List(pl.Float64)}
    )
    samples = df.sample(n=min(25, len(df)))
    for sample in samples.iter_rows(named=True):
        results = corpus_collection.query(query_embeddings=sample["embedding"], n_results=2)
        if results["distances"][0][1] > 0.4:
            collection_samples.append(sample)
    # logger.debug(f"Found {len(collection_samples)} non-similar samples for {collection_name.name}")
    logger.debug(f"Processing {collection_name.name}. Adding {len(collection_samples)} non-similar samples")
    # non_similar_samples.extend(collection_samples)
    # non_similar_samples_df = pl.DataFrame(non_similar_samples)
    if collection_samples:
        pl.DataFrame(collection_samples).write_delta(DATA_DIR / "processed/non_similar_samples.delta", mode="append")

# corpus = {
#     id: {"document": document, "embedding": embedding}
#     for id, document, embedding in zip(corpus_ids, corpus_documents, corpus_embeddings)
# }
# len(corpus_ids), len(corpus_documents), len(corpus_embeddings)
# non_similar_samples_df.write_parquet(DATA_DIR / "processed/non_similar_samples.parquet")

dt = deltalake.DeltaTable(DATA_DIR / "processed/non_similar_samples.delta")
to = TableOptimizer(dt).compact()

  0%|          | 0/3752 [00:00<?, ?it/s]

Processing batches: 100%|██████████| 1/1 [00:00<00:00, 110.02it/s]
2025-08-30 13:06:26.827 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Centurion_Card. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 38.60it/s]
2025-08-30 13:06:30.801 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Public_Procurement_and_Disposal_of_Public_Assets_Authority. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 105.02it/s]
2025-08-30 13:06:34.167 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Chinese_garden. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 196.46it/s]
2025-08-30 13:06:37.444 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Pay_Commission. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 229.66it/s]
2025-08-30 13:06:40.757 | DEBUG    | __main__:<module>:28 - Processing wikiqa_The_Emperor27s_New_Clothes. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 44.88it/s]
2025-08-30 13:06:44.027 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Hercules_1997_film. Adding 4 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 53.00it/s]
2025-08-30 13:06:47.255 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Party_leaders_of_the_United_States_Senate. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 194.85it/s]
2025-08-30 13:06:50.544 | DEBUG    | __main__:<module>:28 - Processing wikiqa_The_Impossible_Astronaut. Adding 4 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 166.00it/s]
2025-08-30 13:06:53.824 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Sinking_of_Prince_of_Wales_and_Repulse. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 204.71it/s]
2025-08-30 13:06:57.076 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Nondisjunction. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 293.43it/s]
2025-08-30 13:07:00.363 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Folk-Country. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 44.36it/s]
2025-08-30 13:07:03.624 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Beer_tower. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 254.79it/s]
2025-08-30 13:07:06.944 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Local_government_areas_of_Nigeria. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 55.41it/s]
2025-08-30 13:07:10.194 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Egocentrism. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 241.36it/s]
2025-08-30 13:07:13.502 | DEBUG    | __main__:<module>:28 - Processing wikiqa_The_Bootleg_Series_Vol_4_Bob_Dylan_Live_1966_The_22Royal_Albert_Hall22_Concert. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 53.36it/s]
2025-08-30 13:07:16.781 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Stevia. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 290.71it/s]
2025-08-30 13:07:20.166 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Dove27s_dung. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 241.96it/s]
2025-08-30 13:07:23.476 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Nest_learning_thermostat. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 46.72it/s]
2025-08-30 13:07:26.760 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Rockefeller_Center_Christmas_Tree. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 337.49it/s]
2025-08-30 13:07:30.137 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_state_leaders_in_1616. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 207.30it/s]
2025-08-30 13:07:33.491 | DEBUG    | __main__:<module>:28 - Processing wikiqa_WikipediaCiting_Wikipedia. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 178.41it/s]
2025-08-30 13:07:36.851 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Distribution_of_wealth. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 139.12it/s]
2025-08-30 13:07:40.297 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Evolutionary_developmental_biology. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 295.27it/s]
2025-08-30 13:07:43.648 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Steatoda_grossa. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 47.61it/s]
2025-08-30 13:07:46.956 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_places_in_County_Armagh. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 60.34it/s]
2025-08-30 13:07:50.248 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Joint_Session_of_Indian_Parliament. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 181.59it/s]
2025-08-30 13:07:53.577 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Song_of_Songs. Adding 5 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 74.85it/s]
2025-08-30 13:07:57.057 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Romeo_and_Juliet. Adding 3 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 157.95it/s]
2025-08-30 13:08:00.550 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Nationalist_faction_Spanish_Civil_War. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 223.73it/s]
2025-08-30 13:08:04.161 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Kevin_Probably_Saves_the_World. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 144.64it/s]
2025-08-30 13:08:07.615 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Wish_You_Were_Here_Pink_Floyd_album. Adding 4 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 138.89it/s]
2025-08-30 13:08:11.104 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_The_Mindy_Project_episodes. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 317.87it/s]
2025-08-30 13:08:14.450 | DEBUG    | __main__:<module>:28 - Processing wikiqa_What_Happens_to_My_Family3F. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 57.63it/s]
2025-08-30 13:08:17.878 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Shiva_Ayyadurai. Adding 3 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 50.16it/s]
2025-08-30 13:08:21.291 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_The_Lion_King_characters. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 51.77it/s]
2025-08-30 13:08:24.721 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Traveling_Wilburys. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 52.02it/s]
2025-08-30 13:08:28.141 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Neuromuscular-blocking_drug. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 67.15it/s]
2025-08-30 13:08:31.510 | DEBUG    | __main__:<module>:28 - Processing wikiqa_I_Knew_the_Bride. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 176.12it/s]
2025-08-30 13:08:34.893 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Carpenter_ant. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 34.94it/s]
2025-08-30 13:08:38.370 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Open_University. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 369.15it/s]
2025-08-30 13:08:38.501 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_Nigerian_states_by_GDP. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 162.13it/s]
2025-08-30 13:08:38.615 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Artificial_cardiac_pacemaker. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 193.84it/s]
2025-08-30 13:08:38.749 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_most_common_surnames_in_Europe. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 278.62it/s]
2025-08-30 13:08:38.864 | DEBUG    | __main__:<module>:28 - Processing wikiqa_SI_base_unit. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 258.92it/s]
2025-08-30 13:08:38.987 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Large_denominations_of_United_States_currency. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 140.69it/s]
2025-08-30 13:08:39.129 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Princes_in_the_Tower. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 337.03it/s]
2025-08-30 13:08:39.218 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Mary_Did_You_Know3F. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 205.09it/s]
2025-08-30 13:08:39.353 | DEBUG    | __main__:<module>:28 - Processing wikiqa_The_Secret_Life_of_the_American_Teenager_season_3. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 87.53it/s]
2025-08-30 13:08:39.475 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Canberra. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 101.07it/s]
2025-08-30 13:08:39.635 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Renaissance. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 178.35it/s]
2025-08-30 13:08:39.765 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Evil_eye. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 269.76it/s]
2025-08-30 13:08:39.881 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Uniform_Crime_Reports. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 346.52it/s]
2025-08-30 13:08:39.988 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Diminishing_returns. Adding 3 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 409.52it/s]
2025-08-30 13:08:40.088 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Listen_to_Love. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 202.84it/s]
2025-08-30 13:08:40.210 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Lorraine_Toussaint. Adding 3 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 145.41it/s]
2025-08-30 13:08:40.340 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Abacus. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 309.61it/s]
2025-08-30 13:08:40.431 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Silent_Witness. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 253.94it/s]
2025-08-30 13:08:40.546 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Ovulation. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 205.68it/s]
2025-08-30 13:08:40.661 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Boston_Post_Road. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 261.70it/s]
2025-08-30 13:08:40.772 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Orinoco. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 246.78it/s]
2025-08-30 13:08:40.890 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_cities_in_Texas. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 288.53it/s]
2025-08-30 13:08:41.052 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_national_independence_days. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 350.61it/s]
2025-08-30 13:08:41.165 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Tika_Sumpter. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 252.21it/s]
2025-08-30 13:08:41.290 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Baby_Please_Don27t_Go. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 88.47it/s]
2025-08-30 13:08:41.433 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Republican_Party_United_States. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 200.27it/s]
2025-08-30 13:08:41.536 | DEBUG    | __main__:<module>:28 - Processing wikiqa_South_Carolina_in_the_American_Civil_War. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 276.09it/s]
2025-08-30 13:08:41.628 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Mark_and_recapture. Adding 4 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 237.69it/s]
2025-08-30 13:08:41.751 | DEBUG    | __main__:<module>:28 - Processing wikiqa_US_Route_66_in_California. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 348.34it/s]
2025-08-30 13:08:41.927 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Holiday_Baking_Championship. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 559.24it/s]
2025-08-30 13:08:42.022 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Matilda_song. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 282.64it/s]
2025-08-30 13:08:42.126 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Youth_Day. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 310.55it/s]
2025-08-30 13:08:42.248 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Citrus_Bowl. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 182.52it/s]
2025-08-30 13:08:42.386 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Petticoat_Junction. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 123.00it/s]
2025-08-30 13:08:42.574 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Draining_and_development_of_the_Everglades. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 273.44it/s]
2025-08-30 13:08:42.662 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Dutch_colonization_of_the_Americas. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 312.91it/s]
2025-08-30 13:08:42.792 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Sue_Ane_Langdon. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 264.47it/s]
2025-08-30 13:08:42.908 | DEBUG    | __main__:<module>:28 - Processing wikiqa_The_Jacksons_An_American_Dream. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 290.18it/s]
2025-08-30 13:08:43.020 | DEBUG    | __main__:<module>:28 - Processing wikiqa_If_You_Go_Away. Adding 5 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 101.78it/s]
2025-08-30 13:08:43.164 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Mickey_Mouse. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 225.32it/s]
2025-08-30 13:08:43.269 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Gun_laws_in_New_York. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 118.80it/s]
2025-08-30 13:08:43.408 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Comanche. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 118.79it/s]
2025-08-30 13:08:46.176 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Holi. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 475.98it/s]
2025-08-30 13:08:47.172 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Back_to_the_Beach. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 182.45it/s]
2025-08-30 13:08:47.283 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Field_of_Dreams. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 171.55it/s]
2025-08-30 13:08:47.390 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Flags_of_the_Confederate_States_of_America. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 334.66it/s]
2025-08-30 13:08:47.504 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Panzer_VIII_Maus. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 272.84it/s]
2025-08-30 13:08:47.622 | DEBUG    | __main__:<module>:28 - Processing wikiqa_NOx. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 302.86it/s]
2025-08-30 13:08:47.718 | DEBUG    | __main__:<module>:28 - Processing wikiqa_The_Bob_26_Tom_Show. Adding 3 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 455.56it/s]
2025-08-30 13:08:47.816 | DEBUG    | __main__:<module>:28 - Processing wikiqa_One_of_These_Nights_song. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 330.70it/s]
2025-08-30 13:08:47.907 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Health_and_Safety_Executive. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 350.37it/s]
2025-08-30 13:08:48.016 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Indian_general_election_1951E2809352. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 208.77it/s]
2025-08-30 13:08:48.123 | DEBUG    | __main__:<module>:28 - Processing wikiqa_East_Godavari_district. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 439.19it/s]
2025-08-30 13:08:48.223 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Dem_Bones. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 87.36it/s]
2025-08-30 13:08:48.348 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Windows_10. Adding 1 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 210.93it/s]
2025-08-30 13:08:48.482 | DEBUG    | __main__:<module>:28 - Processing wikiqa_This_Is_Us_TV_series. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 210.97it/s]
2025-08-30 13:08:48.605 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Of_Course_He27s_Dead. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 420.19it/s]
2025-08-30 13:08:48.714 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Noun_adjunct. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 42.77it/s]
2025-08-30 13:08:50.784 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Google_Glass. Adding 3 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 50.57it/s]
2025-08-30 13:08:53.729 | DEBUG    | __main__:<module>:28 - Processing wikiqa_Economy_of_the_Middle_East. Adding 2 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 39.05it/s]
2025-08-30 13:08:56.706 | DEBUG    | __main__:<module>:28 - Processing wikiqa_List_of_alcohol_laws_of_the_United_States. Adding 0 non-similar samples
Processing batches: 100%|██████████| 1/1 [00:00<00:00, 34.15it/s]

KeyboardInterrupt:

In [13]:
dt = deltalake.DeltaTable(DATA_DIR / "processed/non_similar_samples.delta")
to = TableOptimizer(dt).compact()

In [4]:
sampled_delta = pl.scan_delta(DATA_DIR / "processed/non_similar_samples.delta").unique("id").collect().sample(1000)
sampled_delta.select(pl.len())

shape: (1, 1)
┌──────┐
│ len  │
│ ---  │
│ u32  │
╞══════╡
│ 1000 │
└──────┘

In [5]:
context = "We are find good RAG/LLM benchmark data, compared to long context. For this, we are interested in data that contains queryable information. If things are just chit-chat, we can drop it. The purpose is to create questions and answers that have one place in the text where they can be found."
example_queries = """
    How many movies did i watch recently?
    What is a good way to declutter my bookshelf?
    How large was the aquarium that i recently set up? 
    """
relevance = f"The document is relevant to the following context: {context}"
completeness = """The document is complete, meaning that it contains useful information to answer queries and does not 
only serve as an introduction to the main content that users may be looking for. It should also succeed if there is
self-contained information in the statement, about which we can ask factual questions."""
uniqueness = """The document is unique, meaning that it does not contain information that is already present in other documents."""

criteria = [relevance, completeness, uniqueness]
criteria_labels = ["relevance", "completeness", "uniqueness"]

### 3.2 Filter Documents

We filter our documents using gpt-4o-mini. Batching functions are also available in `llm.py`.

In [9]:
sampled_delta.head()

shape: (5, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ collection             ┆ id                     ┆ document               ┆ embedding             │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ str                    ┆ str                    ┆ str                    ┆ list[f64]             │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ wikiqa_Lost_Dutchman27 ┆ ee685ef6-ca5d-4989-ac8 ┆ Privacy policy         ┆ [0.052456, -0.017897, │
│ s_Gold_M…              ┆ 3-706035…              ┆ About Wikipedia…       ┆ … -0.047…             │
│ wikiqa_Wurtz_reaction  ┆ 78c80406-5cfc-43f9-bcf ┆ Examples and reaction  ┆ [0.012913, -0.006684, │
│                        ┆ e-c55cb7…              ┆ conditio…              ┆ … 0.0241…             │
│ wikiqa_Get_the_Party_S ┆ a9caa0cb-7262-4b94-aa8 ┆ enthusiastic R&B of    ┆ [-0.002424,           │
│ tarted                 ┆ 1-b03c75…              ┆ the origin…            ┆ -0.009661, … -0.00…   │
│ wikiqa_All_These_Thing ┆ ea58a5eb-c158-467b-9e7 ┆ Concert tours          ┆ [-0.033472,           │
│ s_That_I…              ┆ 8-461a5a…              ┆                        ┆ -0.053955, … -0.03…   │
│                        ┆                        ┆                        ┆                       │
│                        ┆                        ┆                        ┆                       │
│                        ┆                        ┆ Hot Fuss Tour…         ┆                       │
│ wikiqa_Climate_of_Sout ┆ 87336797-5260-4a5e-81a ┆ in May 1956, August    ┆ [0.001818, 0.017883,  │
│ h_Africa               ┆ a-33e73b…              ┆ 1962, June…            ┆ … -0.0131…            │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [10]:
corpus_ids = sampled_delta.select("id").to_numpy().reshape(-1).tolist()
corpus_documents = sampled_delta.select("document").to_numpy().reshape(-1).tolist()
metadatas = sampled_delta.select("collection").to_dicts()

In [11]:
from functions.llm import (
    filter_documents_nvidia,
    filter_documents_async,
    filter_documents_parallel,
    create_filter_documents_batch,
)
from openai import AsyncOpenAI, AzureOpenAI

api_key = os.getenv("ORQ_API_KEY")
base_url = "https://api.orq.ai/v2/proxy"
async_openai_client = AsyncOpenAI(api_key=api_key, base_url=base_url)

In [18]:
len(set(corpus_ids)), len(corpus_ids)

(1000, 1000)

In [19]:
duplicates = pl.Series(corpus_ids).value_counts().filter(pl.col("count") > 1)
duplicates

shape: (0, 2)
┌─────┬───────┐
│     ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
└─────┴───────┘

In [ ]:
id = create_filter_documents_batch(
    client=openai_client,
    model="azure/gpt-5-mini",
    documents=corpus_documents,
    ids=corpus_ids,
    criteria=criteria,
    criteria_labels=criteria_labels,
    max_requests_per_batch=1000,
)
id

NotFoundError: 404 Not Found

:

In [12]:
filtered_document_ids = await filter_documents_parallel(
    client=async_openai_client,
    model="azure/gpt-5-nano",
    documents=corpus_documents,
    ids=corpus_ids,
    criteria=criteria,
    criteria_labels=criteria_labels,
    tokens_per_minute=300000,
)
filtered_document_ids

2025-08-31 12:43:06.207 | INFO     | functions.llm:filter_documents_async:283 - Starting 3000 async evaluations with max 50 concurrent requests

Processing evaluations:   0%|          | 0/3000 [00:00<?, ?it/s]

2025-08-31 12:50:26.727 | INFO     | functions.llm:filter_documents_async:334 - Filtered 6 documents out of 1000 total
2025-08-31 12:50:26.730 | INFO     | functions.llm:filter_documents_parallel:382 - filter_documents_parallel returning 2 filtered IDs

(['2004ff80-60d8-4b33-9903-09cdc93c31b3',
  '29e0e032-8dc6-4fd8-845f-f5e2b5865680',
  'a77dbe29-6235-4c9d-803d-1df9c78e63a4',
  '57247594-a236-4539-b7a6-666aacbc5eb1',
  '31971364-1caf-4a6b-aecd-aedc5923b480',
  'a6d5f1e5-7c8a-40b2-9276-0c4084a0dd19'],
 {'6c86ab5f-855d-463d-845d-b28c89df0fce': {'uniqueness': False,
   'relevance': True,
   'completeness': True},
  '4710f8aa-dccf-4388-aeff-76f5074a85ea': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  'a27d736e-c72b-4b1a-a4e2-03e2b90e206f': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '06e62155-dc3a-4f7a-bc7b-4602abc04f96': {'completeness': False,
   'uniqueness': False,
   'relevance': False},
  '29876a01-8d64-4dde-983d-71b6fe368d53': {'completeness': False,
   'uniqueness': False,
   'relevance': True},
  'd3be71a6-6568-4a01-b402-7d63bf3d86f1': {'uniqueness': False,
   'completeness': False,
   'relevance': False},
  '99e462c2-18a6-4225-ab2c-828df0bc278f': {'completeness': True,
   'relevance': True,
   'uniqueness': False},
  'fa1b9300-13fb-456d-b953-ce2e5929ca94': {'uniqueness': False,
   'completeness': False,
   'relevance': True},
  'a31781fc-7ab4-43b4-91c3-a439b8c8b623': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  'ba6f1701-dc01-498f-85be-11747bccd3cb': {'completeness': False,
   'uniqueness': False,
   'relevance': False},
  '34d2f820-6525-4517-a38a-93b90eafc68f': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '2df84752-4645-499c-9937-156fc3541f39': {'uniqueness': False,
   'relevance': True,
   'completeness': False},
  '4e232a0d-fd1e-4b2e-83d7-c4d2f8c44787': {'relevance': True,
   'uniqueness': False,
   'completeness': False},
  '8fd82aa9-2d68-4524-a72d-4766e0ae2098': {'uniqueness': False,
   'relevance': True,
   'completeness': True},
  '3df9fd81-46e8-4abe-bc9f-6c48834f7283': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  '67cd5092-330f-4bd1-ba00-2158d05f771f': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '04abbf07-e7d0-42f5-8647-bba4fedee39b': {'completeness': False,
   'uniqueness': False,
   'relevance': False},
  '96f6ea26-0ab3-4e10-ba80-0ec2ed0aeea9': {'relevance': False,
   'completeness': True,
   'uniqueness': False},
  '2c63c14a-fb7d-493b-8105-f49de092e1a4': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'ad0daf6d-c37e-455f-b62f-1d7642213abb': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '42bd9622-e390-4081-8515-f744bcd416b8': {'completeness': True,
   'uniqueness': False,
   'relevance': True},
  'deceb404-c98b-40f0-a79c-5af33e07e9ab': {'relevance': False,
   'uniqueness': False,
   'completeness': False},
  'ee288e01-7141-4626-bcdd-23531254b485': {'uniqueness': False,
   'relevance': True,
   'completeness': True},
  '9e74fc1f-7785-40d1-a394-b754c157c567': {'completeness': False,
   'uniqueness': False,
   'relevance': True},
  '270db2d2-bea8-4c09-8c79-119cf9253ed2': {'uniqueness': False,
   'relevance': True,
   'completeness': True},
  'd12b5bdb-4fbc-4b09-b397-8deb63615f86': {'completeness': False,
   'uniqueness': False,
   'relevance': False},
  '6c3bfc58-f060-482b-982a-2ee609d1449b': {'uniqueness': False,
   'relevance': False,
   'completeness': False},
  '00af1ec2-8812-43ca-ad57-cf39c827bdff': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'ffdea3c1-53c4-4ec0-8c73-0b95e88d2742': {'completeness': False,
   'uniqueness': False,
   'relevance': False},
  '64f29f72-60f7-4b5a-8cdd-839746bfa1b7': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '8f7519ec-544f-4865-9001-0a884a847fb6': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'b3fa3182-6bf9-4dde-9110-93a8ba197c72': {'relevance': False,
   'uniqueness': False,
   'completeness': True},
  '5d34b903-ea67-4cab-ad36-9a9f6953ae83': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'ff787f62-540c-484d-812c-d42f0a81b0a7': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '312aaae1-459a-4536-aa97-b64d41fa0073': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '45ee68d7-931e-42d0-b66f-97d3dcd352a4': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'f52efe22-7967-48da-9ca4-6865d4580032': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'a2882c81-0ef7-4da6-8a21-34a16a3c8539': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '6ae31929-b9e9-46ab-ab34-3708a85c8bc3': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '07046488-3108-4549-b01d-7541afdbc14e': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '07efc0e2-379b-4b9f-8892-e12a0dc3d2a1': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  '919d8f55-08d6-463f-8223-f0fb34209a11': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '12026c8e-71d1-4a0d-869a-b69b908269c8': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '95e4ce52-93bb-43e7-a5f7-ade3bd13b446': {'uniqueness': False,
   'relevance': False,
   'completeness': False},
  'a4caf6b9-8b46-4fc0-be48-066db80d5633': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '908061ed-55f1-4bee-9108-019497c49d82': {'relevance': False,
   'uniqueness': False,
   'completeness': False},
  'af32c7d6-d233-46a4-a9bb-a47d3373723b': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'fab503ce-ae0b-480c-ac4b-4541a1136a8f': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '04654baa-277c-4b65-8db7-165ab0445812': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  '32a211fa-245a-4a23-8b1a-73854ead1f07': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  '8cda4b69-f84b-41f0-b612-7061b8c531d5': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  'd360bad2-449c-4c81-a69d-69349bfe4e29': {'relevance': True,
   'uniqueness': False,
   'completeness': False},
  '3aa88d93-ba95-49eb-b820-e8b1b72ec732': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '9772c94a-9379-4357-a4d6-953efa1d2dac': {'uniqueness': False,
   'completeness': False,
   'relevance': True},
  'd0b22000-41bd-494a-a0f4-8e834920cfea': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'd0c78e53-0834-448c-8312-0331956f2923': {'completeness': False,
   'uniqueness': False,
   'relevance': True},
  '6d6bf643-d1ab-4bcd-bf56-eda0847d101a': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'd0315f0c-e208-4fbc-8e7f-fb58e77baddb': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '0d99cea4-e135-415a-befc-1006fbbb85b0': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'c3d60596-28fd-4063-92a8-072a7d9a0759': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '6e4096db-50d9-45a6-82ec-9cb65aa5ed53': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '42689ab4-5ce0-4fb4-9818-39dda88853e1': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  '95235113-b149-4827-8f4a-cb4124dfc129': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  'd90381e8-445c-40cb-ba81-63595fea7716': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  '8a927a32-bdd0-401e-97cc-ecb5705c51a3': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'bf85ef4f-519b-4eb0-acce-00ba81e32d9d': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'c83801ac-33ac-4c5d-bb56-251a6e4bbefa': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '4c1b6e7a-afc6-4e7f-8e26-fa11390053fe': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'ffbe5b6c-da89-4ef1-95f2-105af5d12ddb': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '2d4d3dcf-db89-49d2-8c21-4ab328086bf8': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '8a432ec9-3b5e-44ce-b07e-6603bba78a00': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '92fe2103-cf71-4abc-90ac-4bcdf7db2528': {'uniqueness': False,
   'completeness': False,
   'relevance': False},
  'fca64f55-20ee-45b0-ba6c-98850190c1a4': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'e6af7a55-a46e-4818-8b3a-fc9f01a6c1a9': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  '23406b6a-1011-4284-b870-0f41cbce571e': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'c3e08264-aeda-4a97-8186-cb5a2bf993a2': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '6a4c5cee-1a87-426c-b9a5-4e2e86175f82': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '906192a6-4e74-4c49-b1aa-13e3d85e2a77': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '2a79bb61-d95a-4744-abcb-f72515ebe297': {'relevance': True,
   'uniqueness': False,
   'completeness': False},
  '1407ed3d-6307-4148-a7c2-25b85e132083': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '40c36a06-bb9a-43a6-ad90-6f11ea754037': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'c32075ec-4de9-48a0-8dc6-a8d443b153fc': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  '8b36b8c1-70c1-4e2c-a9ee-96b036c1aa9f': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '054799d0-2fc9-4437-bd10-70c1b8cae215': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '889e60e4-81a1-497c-bf95-c847b1ddbbce': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'dfacf7ef-bbd2-499c-9fba-d2afae71093d': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'f2c3a043-2803-4981-8551-be7bbed9c6c6': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '8e692c50-5ab6-4adb-a18c-b519374cb1ed': {'relevance': False,
   'uniqueness': False,
   'completeness': False},
  'f72a9b0d-6921-40d3-bb06-f2b068ccd51e': {'relevance': False,
   'uniqueness': False,
   'completeness': False},
  '7e0035c3-7f38-4afa-80a3-3e97af44ee3c': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  '5be90e0f-9279-4fa6-9f49-b2abe8563a3a': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  '6020441f-f039-425c-880e-3a9cde30953a': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '8f65d13c-d84a-491b-9cb8-f216921076ae': {'relevance': False,
   'uniqueness': False,
   'completeness': True},
  '54c9a299-9f5b-4bae-b802-abac24aef776': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '89dc1c43-50d3-4384-9394-07760b80acd4': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '99576b96-7372-44d1-a91f-045fdb15aadd': {'relevance': False,
   'completeness': True,
   'uniqueness': False},
  '4813d16c-4ddd-416b-a317-64af81ba9c98': {'completeness': True,
   'uniqueness': False,
   'relevance': True},
  '470e0e43-7ab7-4ffe-aac9-4504f8e8f6b7': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '0d681e03-a442-4aa8-acad-7febc18533d3': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  'd2aead94-8a33-40f5-add7-15606058172b': {'uniqueness': False,
   'completeness': True,
   'relevance': True},
  '58cfc75d-23c0-42a8-ba37-e114926af2f2': {'completeness': True,
   'uniqueness': False,
   'relevance': True},
  'f71295fd-1c15-4c71-9001-ebb086d1a9cb': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '608e0ab2-0b70-4afe-a9ef-e6b3c7fdccd5': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '63fb80c8-62a0-4af1-82d1-15e34be1396c': {'completeness': False,
   'uniqueness': False,
   'relevance': True},
  'd7b05a2d-4a8c-46aa-a468-229c973728a3': {'completeness': False,
   'uniqueness': False,
   'relevance': False},
  '4ac8e6d0-ebb1-4af9-9bb0-4b9f90c19768': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'e0139c15-823d-4855-9d9a-c127dc42f209': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'f0fac214-c3ed-4fc2-af9b-19640507ffb0': {'uniqueness': False,
   'relevance': True,
   'completeness': True},
  '3978c5ea-a874-4962-a74b-dc1577d3339b': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'a71224b3-f8e7-4d5e-b87e-8b2936f7b34e': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'cf7e0d52-cbd9-451f-88ed-558e006a17cd': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'ee229d17-6610-4e84-934e-d94474e4e8b1': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '84872c50-f204-4b96-b9fc-75e29ca43345': {'relevance': False,
   'uniqueness': False,
   'completeness': False},
  'e9e34693-afa8-47a5-85a4-ee750107a09c': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  'dca651be-c71e-4306-9579-1bdca5363d74': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'e1c573e8-3abc-45fc-98bd-36117fafdba5': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '8d8fe014-a480-4b07-baf2-d32170c6f77e': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  'bb4dd712-00a8-4f0c-9abc-10d30b9fad43': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'ee00334a-1a02-41bd-9917-b19342aa29f9': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '14b40eaf-51c7-4fd4-bf93-ab6a67ef0497': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '65550d02-452d-420f-a4a6-5a36c6e4f0c2': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '51a1ed6b-8f4a-44ba-9991-e5d905506d97': {'uniqueness': False,
   'completeness': False,
   'relevance': True},
  '3dad721a-d58b-4883-bcf1-0e310fddfc45': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  'ba2a5b3b-f6f0-4569-9e42-d9a2f1a38500': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '53521aa3-7f38-4706-93af-6dd6c5c09a88': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '60626e6b-c229-46e4-943d-ace91e573da3': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '23ddb1e6-2a8f-40cf-925e-f5dee2845517': {'relevance': False,
   'completeness': True,
   'uniqueness': False},
  '727b907a-9428-4e5e-a757-ab0c91a22a79': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '1b32fabe-7ffb-4e5a-b289-a9381234fcd2': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'ad9404c3-fe32-4504-a15a-39d5c5bd8592': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'beed1758-2223-4116-a4a2-a983532d05e9': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '011a6b13-fe26-4588-a9c9-3ac140288c3b': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'd4fbdff1-69fc-49f6-8129-c34652de73ca': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'dd94115b-a036-436c-b96b-06c12acbfa83': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '4c77917e-7936-46dc-b0a9-36c439fa25c8': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'e60d89a2-b35f-4468-a1b9-4324747ae6a1': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  '57e0a511-aa3a-45c1-a451-bbcce5356dc8': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'd404b557-1b80-444e-8a88-268a878e8542': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'bdbea4de-28e1-4de9-9229-1b2e46fdf1b7': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  '5eb86f1e-0f9d-4ba0-a20a-8492151c1107': {'relevance': False,
   'uniqueness': False,
   'completeness': True},
  '7f8a353f-1d82-4ecb-951e-a16e6411d14e': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '58c718e9-3b57-4e05-a53a-9ec92cf52107': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  'c75c73b6-dd3d-4025-865a-6893a4e98cf9': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '889ebadd-f5db-4e45-9dee-d6fb71a61a22': {'completeness': True,
   'uniqueness': False,
   'relevance': True},
  '0213f107-a6d4-41b9-86f3-9367e3776fe8': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '848d6447-8bda-472b-9f43-a0fd6be1dbdf': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '9db9ddda-95de-456a-b39a-d12bb5788956': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'b99f833c-bb33-43be-b8d1-5a8fea6f7ad0': {'uniqueness': False,
   'relevance': True,
   'completeness': True},
  'ccebff51-cd3c-4e58-9351-8c1ef744b520': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'f1c0d232-450a-43de-b131-34249c5894f4': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '81bc01da-9fab-4fb3-9f90-81ac379d49cb': {'uniqueness': False,
   'completeness': False,
   'relevance': True},
  '3cc85ed6-06bd-45fa-a945-91f4f4f89458': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'ae64351b-ab6e-4893-b08f-18ec1ba05a16': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '33245586-6a37-41b3-abda-acdc0cb64308': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  'ba34b267-058d-46a9-931c-4a3f5d5c951e': {'completeness': False,
   'uniqueness': False,
   'relevance': True},
  '2aa4cede-e8a7-4fcd-a954-8f570c40c836': {'completeness': False,
   'relevance': True,
   'uniqueness': False},
  'a6d5f1e5-7c8a-40b2-9276-0c4084a0dd19': {'relevance': True,
   'completeness': True,
   'uniqueness': True},
  'dff3ca18-fedf-4139-a27a-38fd71efcad9': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  '626f05cb-6197-4643-82d7-80dab4c4f4e4': {'relevance': False,
   'uniqueness': False,
   'completeness': True},
  'e52e6bcf-cfe2-456a-9454-ba3af1513e1a': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '4297b42c-b2e4-48f7-adc6-e8fdfe07b9f4': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '30b60d4d-913e-4e0f-a727-1d7e3f587bc6': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '160989f1-11fd-4fa1-baa9-f7bfccc1c48e': {'relevance': False,
   'completeness': True,
   'uniqueness': False},
  '752d2562-dbf0-4747-965e-03be95bcfbae': {'relevance': True,
   'completeness': True,
   'uniqueness': False},
  '548b024b-80aa-4a86-86b1-f8d48259698d': {'relevance': True,
   'uniqueness': False,
   'completeness': True},
  '1ee9a86a-3ee7-49ff-9afd-2a4ca33ae569': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '2e9b93b8-aa11-42e2-a51f-c1a4d30491ee': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'db9fc005-d35f-464f-9d1e-50e2b0d42b83': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  'a94b2da2-b96c-4171-992b-4cc88149d3c4': {'relevance': False,
   'uniqueness': False,
   'completeness': False},
  '02d14e3b-8e0c-4df1-9a57-ff842fa1beb9': {'completeness': False,
   'relevance': False,
   'uniqueness': False},
  '79d800c9-cbc3-4710-9900-16d002485e16': {'relevance': False,
   'completeness': False,
   'uniqueness': True},
  'bbbf4e2f-f663-4f82-8116-3448e268ff23': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '3e752922-65b3-4286-b491-118b3d198eb5': {'relevance': False,
   'completeness': False,
   'uniqueness': False},
  '66489c9e-256b-49d6-9922-2676356ad99d': {'relevance': True,
   'completeness': False,
   'uniqueness': False},
  '93dab494-9190-4bbd-b9cf-e37d2aeb2f81': {'relevance': True,

In [19]:
filtered_document_ids[0]

['bd61c0c1-1f28-4b07-b67f-2b555db9ab57',
 '5bd073a6-3973-414d-b9ef-5f8f36ce6c10']

In [13]:
prepped_data = []
for k, v in filtered_document_ids[1].items():
    prepped_data.append({"id": k, **v})

prepped_data[:2]

[{'id': '6c86ab5f-855d-463d-845d-b28c89df0fce',
  'uniqueness': False,
  'relevance': True,
  'completeness': True},
 {'id': '4710f8aa-dccf-4388-aeff-76f5074a85ea',
  'completeness': False,
  'relevance': False,
  'uniqueness': False}]

In [14]:
chatgpt_filters_df = pl.DataFrame(prepped_data)
chatgpt_filters_df

shape: (1_000, 4)
┌─────────────────────────────────┬────────────┬───────────┬──────────────┐
│ id                              ┆ uniqueness ┆ relevance ┆ completeness │
│ ---                             ┆ ---        ┆ ---       ┆ ---          │
│ str                             ┆ bool       ┆ bool      ┆ bool         │
╞═════════════════════════════════╪════════════╪═══════════╪══════════════╡
│ 6c86ab5f-855d-463d-845d-b28c89… ┆ false      ┆ true      ┆ true         │
│ 4710f8aa-dccf-4388-aeff-76f507… ┆ false      ┆ false     ┆ false        │
│ a27d736e-c72b-4b1a-a4e2-03e2b9… ┆ false      ┆ false     ┆ false        │
│ 06e62155-dc3a-4f7a-bc7b-4602ab… ┆ false      ┆ false     ┆ false        │
│ 29876a01-8d64-4dde-983d-71b6fe… ┆ false      ┆ true      ┆ false        │
│ …                               ┆ …          ┆ …         ┆ …            │
│ 57cca4d6-7847-486c-8d28-c6c2d2… ┆ false      ┆ false     ┆ false        │
│ 255ee098-c9e9-4166-954f-55e754… ┆ false      ┆ true      ┆ true         │
│ b12b64f4-6ba4-402c-9858-e18070… ┆ false      ┆ true      ┆ true         │
│ 2cfb372d-5f34-49d5-83e8-d9c6e0… ┆ false      ┆ true      ┆ false        │
│ 5dc9bd19-9f72-46fe-b0d8-96891c… ┆ false      ┆ false     ┆ false        │
└─────────────────────────────────┴────────────┴───────────┴──────────────┘

In [15]:
chatgpt_filters_df.join(sampled_delta, on="id", how="left").with_columns(
    pl.col("document").str.len_chars().alias("document_length")
).filter(pl.col("document_length") > 100)

shape: (749, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ uniqueness ┆ relevance ┆ completene ┆ collectio ┆ document  ┆ embedding ┆ document_ │
│ ---        ┆ ---        ┆ ---       ┆ ss         ┆ n         ┆ ---       ┆ ---       ┆ length    │
│ str        ┆ bool       ┆ bool      ┆ ---        ┆ ---       ┆ str       ┆ list[f64] ┆ ---       │
│            ┆            ┆           ┆ bool       ┆ str       ┆           ┆           ┆ u32       │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 6c86ab5f-8 ┆ false      ┆ true      ┆ true       ┆ wikiqa_Pr ┆ Numerous  ┆ [0.028962 ┆ 381       │
│ 55d-463d-8 ┆            ┆           ┆            ┆ e-Columbi ┆ pre-Colum ┆ ,         ┆           │
│ 45d-b28c89 ┆            ┆           ┆            ┆ an_era    ┆ bian      ┆ -0.02533, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ societi…  ┆ …         ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆ -0.0260…  ┆           │
│ 4710f8aa-d ┆ false      ┆ false     ┆ false      ┆ wikiqa_Th ┆ Personal  ┆ [0.00511, ┆ 1499      │
│ ccf-4388-a ┆            ┆           ┆            ┆ e_Vampire ┆ tools     ┆ 0.026274, ┆           │
│ eff-76f507 ┆            ┆           ┆            ┆ _Diaries  ┆           ┆ …         ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ Not       ┆ -0.04998… ┆           │
│            ┆            ┆           ┆            ┆           ┆ logged    ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆ inT…      ┆           ┆           │
│ a27d736e-c ┆ false      ┆ false     ┆ false      ┆ wikiqa_Po ┆ Tools     ┆ [-0.02802 ┆ 962       │
│ 72b-4b1a-a ┆            ┆           ┆            ┆ verty_thr ┆           ┆ 2,        ┆           │
│ 4e2-03e2b9 ┆            ┆           ┆            ┆ eshold    ┆ What      ┆ 0.017003, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ links her ┆ … -0.050… ┆           │
│            ┆            ┆           ┆            ┆           ┆ eRelated  ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆ …         ┆           ┆           │
│ 29876a01-8 ┆ false      ┆ true      ┆ false      ┆ wikiqa_Un ┆ Firestone ┆ [0.005641 ┆ 221       │
│ d64-4dde-9 ┆            ┆           ┆            ┆ ited_Meth ┆ Chapel    ┆ , -0.0507 ┆           │
│ 83d-71b6fe ┆            ┆           ┆            ┆ odist_Chu ┆           ┆ 96, …     ┆           │
│ …          ┆            ┆           ┆            ┆ rch…      ┆           ┆ -0.013…   ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆           │
│            ┆            ┆           ┆            ┆           ┆ The …     ┆           ┆           │
│ fa1b9300-1 ┆ false      ┆ true      ┆ false      ┆ wikiqa_Bi ┆ Jump up ^ ┆ [0.005143 ┆ 222       │
│ 3fb-456d-b ┆            ┆           ┆            ┆ as        ┆ Gross,    ┆ ,         ┆           │
│ 953-ce2e59 ┆            ┆           ┆            ┆           ┆ Neil (9   ┆ 0.042184, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ April…    ┆ …         ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆ -0.0569…  ┆           │
│ …          ┆ …          ┆ …         ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         │
│ 5b3b9096-3 ┆ false      ┆ false     ┆ true       ┆ wikiqa_Ex ┆ The first ┆ [0.001277 ┆ 385       │
│ 73b-49d5-9 ┆            ┆           ┆            ┆ treme_pro ┆ time I    ┆ ,         ┆           │
│ cc2-69094c ┆            ┆           ┆            ┆ gramming  ┆ was asked ┆ 0.024318, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ to …      ┆ …         ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆ -0.0253…  ┆           │
│ 8c456e55-2 ┆ false      ┆ true      ┆ false      ┆ wikiqa_Bo ┆ was       ┆ [-0.05356 ┆ 148       │
│ fae-4f15-b ┆            ┆           ┆            ┆ C3B6tes   ┆ Qigong,   ┆ 6,        ┆           │
│ 702-310eea ┆            ┆           ┆            ┆           ┆ the Seven ┆ 0.016452, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ Dukes, w… ┆ … -0.013… ┆           │
│ 255ee098-c ┆ false      ┆ true      ┆ true       ┆ wikiqa_Wh ┆ Episode   ┆ [0.019079 ┆ 1844      │
│ 9e9-4166-9 ┆            ┆           ┆            ┆ at_Happen ┆ Broadcast ┆ ,         ┆           │
│ 54f-55e754 ┆            ┆           ┆            ┆ s_to_My_F ┆ date      ┆ 0.009635, ┆           │
│ …          ┆            ┆           ┆            ┆ ami…      ┆ TNmS ra…  ┆ …         ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆ 0.00755…  ┆           │
│ b12b64f4-6 ┆ false      ┆ true      ┆ true       ┆ wikiqa_Da ┆ ^ Jump up ┆ [0.034335 ┆ 286       │
│ ba4-402c-9 ┆            ┆           ┆            ┆ y_of_the_ ┆ to: a b c ┆ ,         ┆           │
│ 858-e18070 ┆            ┆           ┆            ┆ Dead      ┆ d         ┆ 0.047946, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ Salvador… ┆ …         ┆           │
│            ┆            ┆           ┆            ┆           ┆           ┆ 0.01046…  ┆           │
│ 5dc9bd19-9 ┆ false      ┆ false     ┆ false      ┆ wikiqa_Co ┆ Weber,    ┆ [-0.00178 ┆ 184       │
│ f72-46fe-b ┆            ┆           ┆            ┆ ahuila_y_ ┆ David J.  ┆ 4,        ┆           │
│ 0d8-96891c ┆            ┆           ┆            ┆ Tejas     ┆ (1982),   ┆ 0.011727, ┆           │
│ …          ┆            ┆           ┆            ┆           ┆ The Me…   ┆ … -0.024… ┆           │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [5]:
corpus_ids[0]

'fcc3e290-c2b2-42a8-ad95-0f5ce05dc366'