# Simplified Stages 5 & 6: LLM Filtering + ChromaDB Ingestion

This notebook provides a minimal, functional implementation of:
- **Stage 5**: LLM-based document filtering using question generation
- **Stage 6**: ChromaDB ingestion of filtered documents

**Requirements**: Chunked documents from stage 3 (`data/processed/documents_chunked.parquet`)

## Setup

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import json
import asyncio
import textwrap
from pathlib import Path
from typing import Dict, List, Tuple
import time
import polars as pl
import chromadb
from openai import AsyncOpenAI, OpenAI
from dotenv import load_dotenv
from tqdm.asyncio import tqdm
from pydantic import BaseModel, Field
import langchain_openai
from loguru import logger
from bs4 import BeautifulSoup
from functools import reduce
from itertools import product
import sys
sys.path.append('..')
from notebook_checkpoint_integration import list_experiments
from improved_checkpoint_system import SafeCheckpointManager
from loguru_disk_setup import setup_notebook_logging, ExperimentPhaseLogger
log_info = setup_notebook_logging()
# Load environment variables
load_dotenv(override=True)

# Configuration
SAMPLE_SIZE = 100  # Limit for testing - set to None for full dataset
BATCH_SIZE = 10     # Number of chunks to process in parallel
MAX_CONCURRENT = 7 # Maximum concurrent API requests

# Paths
INPUT_FILE = Path("../data/processed/nq_question_answer_chunked_embeddings_with_suffix.parquet")
RAW_QA_DATA = Path('../data/processed/nq_question_answer.parquet')
CLEANED_NON_CHUNKED = Path('../data/processed/nq_question_answer_cleaned.parquet')
OUTPUT_FILE = Path('../data/processed/wikitext_approved_questions.json')
CHROMA_PATH = Path("../chroma_wikitext")
client = OpenAI(base_url=os.getenv('ORQ_BASE_URL'), api_key=os.getenv("ORQ_API_KEY"))
client_async = AsyncOpenAI(base_url=os.getenv('ORQ_BASE_URL'), api_key=os.getenv("ORQ_API_KEY"))

print(f"✅ Setup complete")
print(f"📂 Input: {INPUT_FILE}")
print(f"📂 Output: {OUTPUT_FILE}")
print(f"📂 Raw QA Data: {RAW_QA_DATA}")
print(f"📂 Cleaned Non-Chunked Data: {CLEANED_NON_CHUNKED}")
print(f"🗃️  ChromaDB: {CHROMA_PATH}")
print(f"ORQ API KEY: {os.getenv('ORQ_API_KEY')[-5:]}")

html_cleaned_df = pl.scan_parquet(CLEANED_NON_CHUNKED)

2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_experiment_logging:105 - Logging initialized for wikiqa_notebook
2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_experiment_logging:106 - Log directory: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/nbs/logs/wikiqa_experiments
2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_experiment_logging:107 - Log level: INFO
2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_experiment_logging:108 - Console logging: True
2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_notebook_logging:194 - ============================================================
2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_notebook_logging:195 - WikiQA Experiment Session Started
2025-09-20 15:51:22 | INFO     | loguru_disk_setup:setup_notebook_logging:196 - ============================================================

✅ Improved 400 error handling module created!

📝 Key functions provided:
  - llm_call_with_error_tracking(): Enhanced LLM call with structured error returns
  - process_question_with_error_handling(): Process results with error metadata
  - summarize_error_statistics(): Generate error statistics from results

🔧 See INTEGRATION_EXAMPLE variable for usage in notebook
✅ Fixed checkpoint integration loaded!
🔧 Usage:
   # Test the system:
   test_results = await test_checkpoint_system()

   # Run single experiment:
   results = await run_single_experiment_improved(
       qa_pairs=filtering_results,
       cleaned_df=html_cleaned_df,
       k=20, retrieval_kind='enhanced_rag', rerank=True,
       n_questions=200, force_new=False
   )

   # Run full experiment suite:
   all_results = await run_full_experiment_improved(
       clean_df=html_cleaned_df,
       k_range=[1, 5, 10, 20, 50, 100],
       n_questions=200, parallel=3, force_new=False
   )

   # Monitor experiments:
   list_experiments()
📝 Loguru disk logging setup loaded!
🔧 Usage:
   # Quick setup for notebook:
   log_info = setup_notebook_logging()

   # Use in experiments:
   logger.info('Your experiment message')

   # Use phase logging:
   with ExperimentPhaseLogger('Data Loading'):
       # your code here
       pass
✅ Setup complete
📂 Input: ../data/processed/nq_question_answer_chunked_embeddings_with_suffix.parquet
📂 Output: ../data/processed/wikitext_approved_questions.json
📂 Raw QA Data: ../data/processed/nq_question_answer.parquet
📂 Cleaned Non-Chunked Data: ../data/processed/nq_question_answer_cleaned.parquet
🗃️  ChromaDB: ../chroma_wikitext
ORQ API KEY: xF9Cs

### Create cleaned version of the dataframe

In [ ]:
# pl.scan_parquet('../data/processed/nq_question_answer.parquet').with_columns(
#         pl.col('document_html').map_elements(lambda x: BeautifulSoup(x, "html.parser").get_text(), return_dtype=pl.String).alias('document_text')
# ).sink_parquet('../data/processed/nq_question_answer_cleaned.parquet')

## Stage 5: LLM Filtering

Simple implementation of question-based filtering:
1. Group consecutive chunks (3 chunks per group)
2. Generate a question from combined text
3. Evaluate if question seems human-like
4. Keep chunks that pass evaluation

In [ ]:
class SimpleFilter:
    def __init__(self):
        self.client = client_async
        self.model = "openai/gpt-4.1"

    async def generate_question(self, text: str) -> tuple[bool, str, str, str | None, str | None]:
        """Generate a question from text and provide reasoning."""
        prompt = textwrap.dedent(f"""Generate ONE specific question that a human might ask about this text.

Format:
{{
    "question": "[question]"
    "reasoning": "[why this question is appropriate]"
}}
Text:
{text[:2000]}""")

        class AnswerModel(BaseModel):
            question: str = Field(..., description="The generated question")
            answer: str = Field(..., description="The answer to the question based on the text")
            reasoning: str = Field(..., description="The reasoning as to why this is a good questions")
            probability_human: float =  Field(..., description="0.0-1.0, how likely is it that a human would ask this question")
            main_chunk_id: str = Field(..., description="The unique_id of the chunk that is most relevant to this question")

        try:
            response = await self.client.responses.parse(
                model=self.model,
                input=[{"role": "user", "content": prompt}],
                text_format=AnswerModel,
            )
            response = response.output_parsed
            return True, response.question, response.reasoning, response.probability_human, response.main_chunk_id, response.answer

        except Exception as e:
            logger.exception(f"Error during question generation: {e}")
            return False, "", f"Generation failed: {str(e)}", None, None, None

    def group_consecutive_chunks(self, df: pl.DataFrame, chunk_count: int = 3, min_chunks: int = 100) -> List[Dict]:
        """Group consecutive chunks for processing."""
        groups = []
        for name, data in df.group_by('document_url'):
            if data.height < min_chunks:
                continue
            documents = data.to_dicts()

            for i in range(0, len(documents), chunk_count):
                end_idx = min(i + chunk_count, len(documents))
                group_docs = documents[i:end_idx]
                groups.append(
                    {
                        "docs": group_docs,
                        "combined_text": "\n\n".join([f'{doc["unique_id"]=} | {doc["collection_suffix"]}\n{doc["chunked_prompt"]=}' for doc in group_docs]),
                        "ids": [doc["unique_id"] for doc in group_docs],
                        'collection_suffix': documents[0]['collection_suffix'],
                        'document_url': name[0]
                    }
                )

        return groups

    async def process_group(self, group: Dict) -> Dict[str, Dict]:
        """Process a group of chunks through question generation and evaluation."""
        combined_text = group["combined_text"]
        chunk_ids = group["ids"]
        collection_suffix = group['collection_suffix']
        document_url = group['document_url']

        # Generate question
        status, question, q_reasoning, probability_human, main_chunk_id, answer = await self.generate_question(combined_text)

        if not status:
            # If question generation fails, mark all chunks as failed
            return {
                    "probability_human": 0.0,
                    "generated_question": "",
                    "question_reasoning": q_reasoning,
                    "main_chunk_id": None,
                    "status": "question_generation_failed",
                    "answer": None,
                    'document_url': document_url,
                    'collection_suffix': collection_suffix,
            }

        # All chunks in group get same result
        return {
                "probability_human": probability_human,
                "generated_question": question,
                "question_reasoning": q_reasoning,
                "main_chunk_id": main_chunk_id,
                "answer": answer,
                "status": "question_generation_succeeded",
                'document_url': document_url,
                'collection_suffix': collection_suffix,
            }


print("🔧 SimpleFilter class defined")
filter = SimpleFilter()
chunked_data = pl.scan_parquet(INPUT_FILE)

# await filter.generate_question("This is a test text to generate a question from.")
gs = filter.group_consecutive_chunks(chunked_data.limit(100).collect(), chunk_count=3, min_chunks=20)
await filter.process_group(gs[0])

🔧 SimpleFilter class defined

{'probability_human': 0.95,
 'generated_question': 'What was the impact of European colonisation on Indigenous Australians between 1788 and 1850?',
 'question_reasoning': "This question is appropriate because the text explicitly mentions that 'European colonisation would have a devastating effect on the pre-existing population of Indigenous Australians,' indicating that this is a significant aspect of this historical period and likely to be of high interest to readers.",
 'main_chunk_id': '203ca45d-e4fc-4666-912c-61ff83b8f960',
 'answer': '',
 'status': 'question_generation_succeeded',
 'document_url': 'https://en.wikipedia.org//w/index.php?title=History_of_Australia_(1788%E2%80%931850)&amp;oldid=819687010',
 'collection_suffix': 'History_of_Australia_1788E280931850'}

In [19]:
# Load and sample data
print("📥 Loading chunked documents...")
df = pl.read_parquet(INPUT_FILE)
print(f"📊 Loaded {len(df)} documents")

# if SAMPLE_SIZE:
#     df = df.head(1000)
#     print(f"🎯 Using sample of {len(df)} documents")

# Initialize filter
filter_engine = SimpleFilter()
print("✅ Filter initialized")

📥 Loading chunked documents...
📊 Loaded 212044 documents
✅ Filter initialized

In [23]:
document_urls = df.group_by('document_url').count().filter(pl.col('count') > 100)['document_url'].to_list()
document_urls

/var/folders/bd/lg0gz3wd5jgdrhj47_f2nfyh0000gn/T/ipykernel_2099/1368443298.py:1: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  document_urls = df.group_by('document_url').count().filter(pl.col('count') > 100)['document_url'].to_list()

['https://en.wikipedia.org//w/index.php?title=2018_NCAA_Division_I_Men%27s_Basketball_Tournament&amp;oldid=837560621',
 'https://en.wikipedia.org//w/index.php?title=Singapore&amp;oldid=838168836',
 'https://en.wikipedia.org//w/index.php?title=Beijing&amp;oldid=838137684',
 'https://en.wikipedia.org//w/index.php?title=Atomic_bombings_of_Hiroshima_and_Nagasaki&amp;oldid=838327110',
 'https://en.wikipedia.org//w/index.php?title=Rafael_Nadal&amp;oldid=838533145',
 'https://en.wikipedia.org//w/index.php?title=Bay_of_Pigs_Invasion&amp;oldid=817526436',
 'https://en.wikipedia.org//w/index.php?title=History_of_television&amp;oldid=838235565',
 'https://en.wikipedia.org//w/index.php?title=Toronto_Maple_Leafs&amp;oldid=807290929',
 'https://en.wikipedia.org//w/index.php?title=The_Phantom_of_the_Opera_(1986_musical)&amp;oldid=838349429',
 'https://en.wikipedia.org//w/index.php?title=Air_pollution&amp;oldid=822370127',
 'https://en.wikipedia.org//w/index.php?title=Guantanamo_Bay_detention_camp&amp;oldid=838450706',
 'https://en.wikipedia.org//w/index.php?title=List_of_festivals_in_the_Philippines&amp;oldid=828200892',
 'https://en.wikipedia.org//w/index.php?title=List_of_highest-grossing_films&amp;oldid=819523645',
 'https://en.wikipedia.org//w/index.php?title=American_Revolution&amp;oldid=806857204',
 'https://en.wikipedia.org//w/index.php?title=Oakland_Raiders&amp;oldid=807231707',
 'https://en.wikipedia.org//w/index.php?title=2018_Winter_Olympics&amp;oldid=838278991',
 'https://en.wikipedia.org//w/index.php?title=Comma_Johanneum&amp;oldid=832571922',
 'https://en.wikipedia.org//w/index.php?title=United_States_Constitution&amp;oldid=838537837',
 'https://en.wikipedia.org//w/index.php?title=Manhattan_Project&amp;oldid=821380031',
 'https://en.wikipedia.org//w/index.php?title=Southern_United_States&amp;oldid=822349642',
 'https://en.wikipedia.org//w/index.php?title=2017_World_Series&amp;oldid=822322227',
 'https://en.wikipedia.org//w/index.php?title=Lobbying_in_the_United_States&amp;oldid=818654533',
 'https://en.wikipedia.org//w/index.php?title=American_Revolution&amp;oldid=837206379',
 'https://en.wikipedia.org//w/index.php?title=Spanish_Civil_War&amp;oldid=838550545',
 'https://en.wikipedia.org//w/index.php?title=Austria-Hungary&amp;oldid=838532592',
 'https://en.wikipedia.org//w/index.php?title=List_of_Dragon_Ball_Super_episodes&amp;oldid=838398340',
 'https://en.wikipedia.org//w/index.php?title=Alkali_metal&amp;oldid=813586499',
 'https://en.wikipedia.org//w/index.php?title=On_the_Origin_of_Species&amp;oldid=836566097',
 'https://en.wikipedia.org//w/index.php?title=Philadelphia&amp;oldid=838254563',
 'https://en.wikipedia.org//w/index.php?title=List_of_performances_on_Top_of_the_Pops&amp;oldid=818121506',
 'https://en.wikipedia.org//w/index.php?title=Romanticism&amp;oldid=818798844',
 'https://en.wikipedia.org//w/index.php?title=Sun&amp;oldid=837428242',
 'https://en.wikipedia.org//w/index.php?title=Phonograph&amp;oldid=821767180',
 'https://en.wikipedia.org//w/index.php?title=International_Space_Station&amp;oldid=806438749',
 'https://en.wikipedia.org//w/index.php?title=Riverdale_(2017_TV_series)&amp;oldid=822314521',
 'https://en.wikipedia.org//w/index.php?title=East_India_Company&amp;oldid=838456009',
 'https://en.wikipedia.org//w/index.php?title=Gulf_War&amp;oldid=819431369',
 'https://en.wikipedia.org//w/index.php?title=War_of_1812&amp;oldid=837424264',
 'https://en.wikipedia.org//w/index.php?title=Belle_(Beauty_and_the_Beast)&amp;oldid=837869142',
 'https://en.wikipedia.org//w/index.php?title=List_of_Dragon_Ball_Super_episodes&amp;oldid=819539421',
 'https://en.wikipedia.org//w/index.php?title=List_of_best-selling_music_artists&amp;oldid=838547572',
 'https://en.wikipedia.org//w/index.php?title=Relationship_between_religion_and_science&amp;oldid=822032175',
 'https://en.wikipedia.org//w/index.php?title=Floyd_Mayweather_Jr.&amp;oldid=838403674',
 'https://en.wikipedia.org//w/index.php?title=Tom_Brady&amp;oldid=819498413',
 'https://en.wikipedia.org//w/index.php?title=FA_Cup&amp;oldid=838026457',
 'https://en.wikipedia.org//w/index.php?title=Not_in_This_Lifetime..._Tour&amp;oldid=807238843',
 'https://en.wikipedia.org//w/index.php?title=God_of_War_(franchise)&amp;oldid=838473441',
 'https://en.wikipedia.org//w/index.php?title=American_entry_into_World_War_I&amp;oldid=822020133',
 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882',
 'https://en.wikipedia.org//w/index.php?title=List_of_Teenage_Mutant_Ninja_Turtles_characters&amp;oldid=817759179',
 'https://en.wikipedia.org//w/index.php?title=United_Kingdom%E2%80%93United_States_relations&amp;oldid=838209157',
 'https://en.wikipedia.org//w/index.php?title=Chernobyl_disaster&amp;oldid=838446734',
 'https://en.wikipedia.org//w/index.php?title=History_of_the_United_States_Democratic_Party&amp;oldid=835692980',
 'https://en.wikipedia.org//w/index.php?title=Montana&amp;oldid=806930548',
 'https://en.wikipedia.org//w/index.php?title=Financial_crisis_of_2007%E2%80%932008&amp;oldid=837459313',
 'https://en.wikipedia.org//w/index.php?title=National_debt_of_the_United_States&amp;oldid=806680301',
 'https://en.wikipedia.org//w/index.php?title=Economy_of_the_United_States&amp;oldid=837509121',
 'https://en.wikipedia.org//w/index.php?title=Michigan_Wolverines_men%27s_basketball&amp;oldid=838088704',
 'https://en.wikipedia.org//w/index.php?title=World_War_II&amp;oldid=819520599',
 'https://en.wikipedia.org//w/index.php?title=Age_of_Enlightenment&amp;oldid=819535951',
 'https://en.wikipedia.org//w/index.php?title=When_Calls_the_Heart&amp;oldid=838349951',
 'https://en.wikipedia.org//w/index.php?title=Puerto_Rico&amp;oldid=822215686',
 'https://en.wikipedia.org//w/index.php?title=Roman_Empire&amp;oldid=838251609',
 'https://en.wikipedia.org//w/index.php?title=Ottoman_Empire&amp;oldid=822196022',
 'https://en.wikipedia.org//w/index.php?title=Harry_Potter_(film_series)&amp;oldid=836678261',
 'https://en.wikipedia.org//w/index.php?title=The_Deer_Hunter&amp;oldid=838182091',
 'https://en.wikipedia.org//w/index.php?title=2011_T%C5%8Dhoku_earthquake_and_tsunami&amp;oldid=834404378',
 'https://en.wikipedia.org//w/index.php?title=List_of_Miraculous:_Tales_of_Ladybug_%26_Cat_Noir_episodes&amp;oldid=838440654',
 'https://en.wikipedia.org//w/index.php?title=Masters_Tournament&amp;oldid=838020699',
 'https://en.wikipedia.org//w/index.php?title=Citizen_Kane&amp;oldid=821779511',
 'https://en.wikipedia.org//w/index.php?title=Battle_of_Britain&amp;oldid=838541253',
 'https://en.wikipedia.org//w/index.php?title=Saudi_Arabia&amp;oldid=837987458',
 'https://en.wikipedia.org//w/index.php?title=List_of_The_Flash_episodes&amp;oldid=838448447',
 'https://en.wikipedia.org//w/index.php?title=War_of_1812&amp;oldid=822351702',
 'https://en.wikipedia.org//w/index.php?title=American_Civil_War&amp;oldid=818048748',
 'https://en.wikipedia.org//w/index.php?title=Chernobyl_disaster&amp;oldid=819490863',
 'https://en.wikipedia.org//w/index.php?title=Statue_of_Liberty&amp;oldid=836105581',
 'https://en.wikipedia.org//w/index.php?title=Cuba&amp;oldid=819282005',
 'https://en.wikipedia.org//w/index.php?title=Superman&amp;oldid=838280019',
 'https://en.wikipedia.org//w/index.php?title=United_States_Postal_Service&amp;oldid=807326580',
 'https://en.wikipedia.org//w/index.php?title=Panama_Canal&amp;oldid=822293104',
 'https://en.wikipedia.org//w/index.php?title=Photosynthesis&amp;oldid=818857447',
 'https://en.wikipedia.org//w/index.php?title=List_of_smoking_bans_in_the_United_States&amp;oldid=837461388',
 'https://en.wikipedia.org//w/index.php?title=Miami_Hurricanes_football&amp;oldid=821320639',
 'https://en.wikipedia.org//w/index.php?title=Health_care_in_the_United_States&amp;oldid=836937825',
 'https://en.wikipedia.org//w/index.php?title=The_Curse_of_Oak_Island&amp;oldid=832882458',
 'https://en.wikipedia.org//w/index.php?title=Supreme_Court_of_the_United_States&amp;oldid=837913212',
 'https://en.wikipedia.org//w/index.php?title=History_of_Australia&amp;oldid=818869652',
 'https://en.wikipedia.org//w/index.php?title=List_of_Orange_Is_the_New_Black_characters&amp;oldid=834396787',
 'https://en.wikipedia.org//w/index.php?title=History_of_evolutionary_thought&amp;oldid=836716735',
 'https://en.wikipedia.org//w/index.php?title=Tom_Brady&amp;oldid=837596033',
 'https://en.wikipedia.org//w/index.php?title=Syrian_Civil_War&amp;oldid=838178617',
 'https://en.wikipedia.org//w/index.php?title=Zimbabwe&amp;oldid=819529415',
 'https://en.wikipedia.org//w/index.php?title=United_States_Postal_Service&amp;oldid=838320636',
 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=838501027',
 'https://en.wikipedia.org//w/index.php?title=History_of_chemistry&amp;oldid=803775631',
 'https://en.wikipedia.org//w/index.php?title=History_of_the_Great_Wall_of_China&amp;oldid=819047776',
 'https://en.wikipedia.org//w/index.php?title=Acronym&amp;oldid=838325318',
 'https://en.wikipedia.org//w/index.php?title=Australian_Army_during_World_War_II&amp;oldid=834216537',
 'https://en.wikipedia.org//w/index.php?title=Chloroplast&amp;oldid=837447917',
 'https://en.wikipedia.org//w/index.php?title=The_Taming_of_the_Shrew&amp;oldid=837432424',
 'https://en.wikipedia.org//w/index.php?title=Colonial_history_of_the_United_States&amp;oldid=806578243',
 'https://en.wikipedia.org//w/index.php?title=Indonesia&amp;oldid=821906047',
 'https://en.wikipedia.org//w/index.php?title=French_Revolution&amp;oldid=837799097',
 'https://en.wikipedia.org//w/index.php?title=Captain_America:_Civil_War&amp;oldid=819487324',
 'https://en.wikipedia.org//w/index.php?title=History_of_the_Byzantine_Empire&amp;oldid=820594004',
 'https://en.wikipedia.org//w/index.php?title=Battles_of_Saratoga&amp;oldid=818158715',
 'https://en.wikipedia.org//w/index.php?title=Axis_powers&amp;oldid=821485811',
 'https://en.wikipedia.org//w/index.php?title=French_Revolution&amp;oldid=818778645',
 'https://en.wikipedia.org//w/index.php?title=Indian_Rebellion_of_1857&amp;oldid=838494930',
 'https://en.wikipedia.org//w/index.php?title=The_Rolling_Stones&amp;oldid=837955424',
 'https://en.wikipedia.org//w/index.php?title=List_of_The_Next_Step_episodes&amp;oldid=837737769',
 'https://en.wikipedia.org//w/index.php?title=List_of_Olympic_medalists_in_figure_skating&amp;oldid=837025106',
 'https://en.wikipedia.org//w/index.php?title=Grey%27s_Anatomy&amp;oldid=819396561',
 'https://en.wikipedia.org//w/index.php?title=Native_Americans_in_the_United_States&amp;oldid=838207968',
 'https://en.wikipedia.org//w/index.php?title=Articles_of_Confederation&amp;oldid=838541193',
 'https://en.wikipedia.org//w/index.php?title=History_of_the_Philadelphia_Eagles&amp;oldid=833514063',
 'https://en.wikipedia.org//w/index.php?title=Alabama&amp;oldid=806918792',
 'https://en.wikipedia.org//w/index.php?title=History_of_women_in_the_United_States&amp;oldid=822183230',
 'https://en.wikipedia.org//w/index.php?title=San_Francisco_49ers&amp;oldid=819302721',
 'https://en.wikipedia.org//w/index.php?title=List_of_DreamWorks_Dragons_episodes&amp;oldid=835974760',
 'https://en.wikipedia.org//w/index.php?title=Gerald_Ford&amp;oldid=807079147',
 'https://en.wikipedia.org//w/index.php?title=Star_Trek:_Discovery&amp;oldid=838430258',
 'https://en.wikipedia.org//w/index.php?title=Flag_of_the_United_States&amp;oldid=838516879',
 'https://en.wikipedia.org//w/index.php?title=United_States_corporate_law&amp;oldid=816421762',
 'https://en.wikipedia.org//w/index.php?title=Reconstruction_Era&amp;oldid=821997502',
 'https://en.wikipedia.org//w/index.php?title=Democratic_Party_(United_States)&amp;oldid=838437825',
 'https://en.wikipedia.org//w/index.php?title=Age_of_Discovery&amp;oldid=817850695',
 'https://en.wikipedia.org//w/index.php?title=Qing_dynasty&amp;oldid=822294759',
 'https://en.wikipedia.org//w/index.php?title=List_of_Malcolm_in_the_Middle_episodes&amp;oldid=837972349',
 'https://en.wikipedia.org//w/index.php?title=Industrial_Revolution&amp;oldid=816711474',
 'https://en.wikipedia.org//w/index.php?title=List_of_Game_of_Thrones_characters&amp;oldid=822351965',
 'https://en.wikipedia.org//w/index.php?title=Lionel_Messi&amp;oldid=837695305',
 'https://en.wikipedia.org//w/index.php?title=Indian_Rebellion_of_1857&amp;oldid=821933492',
 'https://en.wikipedia.org//w/index.php?title=United_States_Congress&amp;oldid=822128562',
 'https://en.wikipedia.org//w/index.php?title=Berlin_Wall&amp;oldid=837372486',
 'https://en.wikipedia.org//w/index.php?title=American_Civil_War&amp;oldid=822060323',
 'https://en.wikipedia.org//w/index.php?title=Romanticism&amp;oldid=822003673',
 'https://en.wikipedia.org//w/index.php?title=Mount_Everest&amp;oldid=838344848',
 'https://en.wikipedia.org//w/index.php?title=Houston_Astros&amp;oldid=822155749',
 'https://en.wikipedia.org//w/index.php?title=Christmas_traditions&amp;oldid=821913308',
 'https://en.wikipedia.org//w/index.php?title=History_of_South_America&amp;oldid=819211677',
 'https://en.wikipedia.org//w/index.php?title=RMS_Titanic&amp;oldid=805999140',
 'https://en.wikipedia.org//w/index.php?title=I%27m_a_Celebrity...Get_Me_Out_of_Here!_(UK_TV_series)&amp;oldid=816633278',
 'https://en.wikipedia.org//w/index.php?title=American_Idol&amp;oldid=838111919',
 'https://en.wikipedia.org//w/index.php?title=Modern_history&amp;oldid=807203428',
 'https://en.wikipedia.org//w/index.php?title=Clemson_Tigers_football&amp;oldid=821890543',
 'https://en.wikipedia.org//w/index.php?title=Roman_Empire&amp;oldid=816488049',
 'https://en.wikipedia.org//w/index.php?title=RMS_Titanic&amp;oldid=838311942',
 'https://en.wikipedia.org//w/index.php?title=History_of_scientific_method&amp;oldid=838272594',
 'https://en.wikipedia.org//w/index.php?title=List_of_Game_of_Thrones_characters&amp;oldid=838019032',
 'https://en.wikipedia.org//w/index.php?title=United_States&amp;oldid=807272487',
 'https://en.wikipedia.org//w/index.php?title=Economic_history_of_the_United_States&amp;oldid=822091932',
 'https://en.wikipedia.org//w/index.php?title=Game_of_Thrones&amp;oldid=806885945',
 'https://en.wikipedia.org//w/index.php?title=United_States_Congress&amp;oldid=838397296',
 'https://en.wikipedia.org//w/index.php?title=Scottish_independence_referendum,_2014&amp;oldid=818291895',
 'https://en.wikipedia.org//w/index.php?title=Beauty_and_the_Beast_(2017_film)&amp;oldid=822326105',
 'https://en.wikipedia.org//w/index.php?title=Super_Bowl_XXXIX&amp;oldid=837644458',
 'https://en.wikipedia.org//w/index.php?title=The_Haves_and_the_Have_Nots_(TV_series)&amp;oldid=837874160',
 'https://en.wikipedia.org//w/index.php?title=List_of_Olympic_Games_host_cities&amp;oldid=837813982',
 'https://en.wikipedia.org//w/index.php?title=History_of_Vietnam&amp;oldid=837807502',
 'https://en.wikipedia.org//w/index.php?title=Hellenistic_period&amp;oldid=838538324',
 'https://en.wikipedia.org//w/index.php?title=English_contract_law&amp;oldid=814204638',
 'https://en.wikipedia.org//w/index.php?title=History_of_the_United_States&amp;oldid=822282210',
 'https://en.wikipedia.org//w/index.php?title=Empire_State_Building&amp;oldid=819382074',
 'https://en.wikipedia.org//w/index.php?title=Hawaii&amp;oldid=821257022',
 'https://en.wikipedia.org//w/index.php?title=The_Bronx&amp;oldid=837798422',
 'https://en.wikipedia.org//w/index.php?title=Big_Sur&amp;oldid=821993565',
 'https://en.wikipedia.org//w/index.php?title=Super_Bowl_LII&amp;oldid=838090435',
 'https://en.wikipedia.org//w/index.php?title=Beauty_and_the_Beast_(2017_film)&amp;oldid=819457516',
 'https://en.wikipedia.org//w/index.php?title=Confederate_States_of_America&amp;oldid=822320631',
 'https://en.wikipedia.org//w/index.php?title=Tobacco_advertising&amp;oldid=838426645',
 'https://en.wikipedia.org//w/index.php?title=Second_Industrial_Revolution&amp;oldid=821743382',
 'https://en.wikipedia.org//w/index.php?title=Globalization&amp;oldid=838160557',
 'https://en.wikipedia.org//w/index.php?title=Thomas_Jefferson&amp;oldid=838220532',
 'https://en.wikipedia.org//w/index.php?title=List_of_Marvel_Comics_characters:_B&amp;oldid=818754596',
 'https://en.wikipedia.org//w/index.php?title=History_of_IBM&amp;oldid=836648701',
 'https://en.wikipedia.org//w/index.php?title=Christmas&amp;oldid=838514133',
 'https://en.wikipedia.org//w/index.php?title=Communist_Party_of_the_Soviet_Union&amp;oldid=838213175',
 'https://en.wikipedia.org//w/index.php?title=Macedonia_(ancient_kingdom)&amp;oldid=834198635',
 'https://en.wikipedia.org//w/index.php?title=New_Mexico&amp;oldid=837703404',
 'https://en.wikipedia.org//w/index.php?title=Eastern_Orthodox_Church&amp;oldid=838470752',
 'https://en.wikipedia.org//w/index.php?title=Cristiano_Ronaldo&amp;oldid=807219735',
 'https://en.wikipedia.org//w/index.php?title=Hawaii&amp;oldid=819396917',
 'https://en.wikipedia.org//w/index.php?title=Indian_Rebellion_of_1857&amp;oldid=819296641',
 'https://en.wikipedia.org//w/index.php?title=List_of_Once_Upon_a_Time_characters&amp;oldid=838513914',
 'https://en.wikipedia.org//w/index.php?title=The_Dark_Side_of_the_Moon&amp;oldid=838533801',
 'https://en.wikipedia.org//w/index.php?title=Economy_of_India&amp;oldid=821291580',
 'https://en.wikipedia.org//w/index.php?title=First_Battle_of_Bull_Run&amp;oldid=836552195',
 'https://en.wikipedia.org//w/index.php?title=Sound_film&amp;oldid=816897569',
 'https://en.wikipedia.org//w/index.php?title=Extinction&amp;oldid=822369329',
 'https://en.wikipedia.org//w/index.php?title=Golden_State_Warriors&amp;oldid=838213686',
 'https://en.wikipedia.org//w/index.php?title=Lobbying_in_the_United_States&amp;oldid=837081139',
 'https://en.wikipedia.org//w/index.php?title=Kentucky_Wildcats_men%27s_basketball&amp;oldid=836618916',
 'https://en.wikipedia.org//w/index.php?title=Passengers_of_the_RMS_Titanic&amp;oldid=837548685',
 'https://en.wikipedia.org//w/index.php?title=Treaty_of_Versailles&amp;oldid=838113493',
 'https://en.wikipedia.org//w/index.php?title=I_Can_Only_Imagine_(MercyMe_song)&amp;oldid=837313786',
 'https://en.wikipedia.org//w/index.php?title=Cold_War&amp;oldid=822330569',
 'https://en.wikipedia.org//w/index.php?title=Mount_Everest&amp;oldid=818707781',
 'https://en.wikipedia.org//w/index.php?title=Philadelphia_Eagles&amp;oldid=837324291',
 'https://en.wikipedia.org//w/index.php?title=Human_evolution&amp;oldid=821005897',
 'https://en.wikipedia.org//w/index.php?title=We_Are_the_World&amp;oldid=815185445',
 'https://en.wikipedia.org//w/index.php?title=World_War_I&amp;oldid=822330589',
 'https://en.wikipedia.org//w/index.php?title=New_York_City_Subway&amp;oldid=837547834',
 'https://en.wikipedia.org//w/index.php?title=Second_Amendment_to_the_United_States_Constitution&amp;oldid=838227052',
 'https://en.wikipedia.org//w/index.php?title=New_Spain&amp;oldid=821187685',
 'https://en.wikipedia.org//w/index.php?title=Houston_Astros&amp;oldid=818491983',
 'https://en.wikipedia.org//w/index.php?title=Europe&amp;oldid=822337708',
 'https://en.wikipedia.org//w/index.php?title=Art_Deco&amp;oldid=816580231',
 'https://en.wikipedia.org//w/index.php?title=Soviet_Union&amp;oldid=819424184',
 'https://en.wikipedia.org//w/index.php?title=Rock_music&amp;oldid=821979984',
 'https://en.wikipedia.org//w/index.php?title=Walmart&amp;oldid=822180680',
 'https://en.wikipedia.org//w/index.php?title=Star_Wars:_The_Force_Awakens&amp;oldid=819455533',
 'https://en.wikipedia.org//w/index.php?title=Muhammad_Ali&amp;oldid=837872787',
 'https://en.wikipedia.org//w/index.php?title=Fifty_Shades_of_Grey_(film)&amp;oldid=837933868',
 'https://en.wikipedia.org//w/index.php?title=Ash_Wednesday&amp;oldid=830825344',
 'https://en.wikipedia.org//w/index.php?title=First_Amendment_to_the_United_States_Constitution&amp;oldid=821210814',
 'https://en.wikipedia.org//w/index.php?title=Republic_of_Ireland&amp;oldid=837611704',
 'https://en.wikipedia.org//w/index.php?title=International_relations_of_the_Great_Powers_(1814%E2%80%931919)&amp;oldid=836790376',

In [25]:
# Process filtering
async def run_filtering(df, min_chunks: int = 100, desired_nr_questions: int = 200) -> list[dict]:
    print("🔍 Starting LLM filtering...")

    # Group consecutive chunks
    groups = filter_engine.group_consecutive_chunks(df, chunk_count=3, min_chunks=min_chunks)
    print(f"📦 Created {len(groups)} chunk groups")

    # Process groups with concurrency control
    semaphore = asyncio.Semaphore(MAX_CONCURRENT)

    async def process_with_semaphore(group):
        async with semaphore:
            return await filter_engine.process_group(group)

    # Process all groups
    results = []
    for i in tqdm(range(0, len(groups), BATCH_SIZE), desc="Processing batches"):
        batch_groups = groups[i : i + BATCH_SIZE]
        batch_tasks = [process_with_semaphore(group) for group in batch_groups]
        batch_results = await asyncio.gather(*batch_tasks, return_exceptions=True)

        for result in batch_results:
            if isinstance(result, Exception):
                print(f"⚠️ Error in batch: {result}")
            else:
                results.append(result)
        if len(results) >= desired_nr_questions:
            break

    # Combine all results
    # all_results = {}
    # for result in results:
    #     all_results.update(result)

    return results


# Run the filtering
filtering_results = await run_filtering(df, min_chunks=100, desired_nr_questions=500)
print(f"✅ Filtering complete: {len(filtering_results)} chunks processed")

🔍 Starting LLM filtering...
📦 Created 13571 chunk groups

Processing batches:   4%|▎         | 49/1358 [04:49<2:09:04,  5.92s/it]

✅ Filtering complete: 500 chunks processed

In [26]:
# Filter and save results
print("📊 Processing filtering results...")

# Get chunks that passed filtering
passed_ids = [result['main_chunk_id'] for result in filtering_results 
              if result.get("probability_human", 0.0) > 0.8]

print(f"✅ {len(passed_ids)} chunks passed filtering (out of {len(filtering_results)})")
print(f"📊 Success rate: {len(passed_ids)/len(filtering_results)*100:.1f}%")

# Filter dataframe to only include passed chunks
filtered_df = df.filter(pl.col("unique_id").is_in(passed_ids))

# Add filtering metadata
metadata_rows = []
for result in filtering_results:
    metadata_rows.append({
        "unique_id": result['main_chunk_id'],
        "human_would_ask": result.get("human_would_ask", False),
        "generated_question": result.get("generated_question", ""),
        "question_reasoning": result.get("question_reasoning", ""),
        "evaluation_reasoning": result.get("evaluation_reasoning", ""),
        "main_chunk_id": result.get("main_chunk_id", None),
        'document_url': result.get('document_url', ''),
        'collection_suffix': result.get('collection_suffix', ''),
        'answer': result.get('answer', ''),
        "status": result.get("status", "unknown"),
    })

metadata_df = pl.DataFrame(metadata_rows)

# Join with original data
final_df = filtered_df.join(metadata_df, on="unique_id", how="left")

# Save filtered results
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
final_df.write_parquet(OUTPUT_FILE)

print(f"💾 Saved {len(final_df)} filtered documents to {OUTPUT_FILE}")
print(f"📝 Columns: {final_df.columns}")

📊 Processing filtering results...
✅ 396 chunks passed filtering (out of 500)
📊 Success rate: 79.2%
💾 Saved 395 filtered documents to ../data/processed/wikitext_approved_questions.json
📝 Columns: ['chunked_prompt', 'document_url', 'context_length', 'token_count', 'unique_id', 'embedding', 'collection_suffix', 'human_would_ask', 'generated_question', 'question_reasoning', 'evaluation_reasoning', 'main_chunk_id', 'document_url_right', 'collection_suffix_right', 'answer', 'status']

In [27]:
json.dump(filtering_results, open('../data/processed/wikitext_approved_questions.json', 'w+'), indent=4)

In [3]:
import json
filtering_results = json.load(open('../data/processed/wikitext_approved_questions.json'))

In [4]:
ids = [r['main_chunk_id'] for r in filtering_results if r['probability_human'] > 0.8]
print(f"✅ Loaded {len(ids)} approved question chunk IDs")

✅ Loaded 396 approved question chunk IDs

## Stage 6: ChromaDB Ingestion

Simple ChromaDB ingestion of filtered documents with OpenAI embeddings.

## Test ChromaDB Query

In [5]:
chroma_client = chromadb.PersistentClient(path=str(CHROMA_PATH))
collections = chroma_client.list_collections()
from chromadb import Collection
collections
test_collection = chroma_client.get_collection("wikiqa_The_Crossing_TV_series")

In [6]:
from context_is_king.evaluation.judge_evaluator import JudgeEvaluator
from context_is_king.models.interface import ModelInterface
from context_is_king.rag_pipeline.query_enhancement.dual_retrieval import DualRetrieval
from context_is_king.rag_pipeline.query_enhancement.query_rewriter import QueryRewriter
from context_is_king.rag_pipeline.reranking.module import RerankerModule
from context_is_king.rag_pipeline.retrieval.engine import RetrievalEngine
from context_is_king.rag_pipeline.types import PipelineConfig

model_interface = ModelInterface()
config = PipelineConfig(quiet_mode=True)
judge = JudgeEvaluator(model_interface=model_interface, judge_model=config.judge_model)
query_rewriter = QueryRewriter(pipeline_config=config)
reranker = RerankerModule(config=config)
retrieval_engine = RetrievalEngine(config=config)

dual_retrieval = DualRetrieval(retrieval_engine=retrieval_engine, query_rewriter=query_rewriter, pipeline_config=config)
EMBEDDING_DIMENSION = 1536

🔗 Initialized Model Interface
📡 API Base URL: https://api.orq.ai/v2/proxy
🤖 Available Models: 14
🔄 Rate Limiting: 5 retries, 1.0s base delay

JudgeEvaluator initialized with model: gpt-4.1

🔗 Initialized Model Interface
📡 API Base URL: https://api.orq.ai/v2/proxy
🤖 Available Models: 14
🔄 Rate Limiting: 5 retries, 1.0s base delay

QueryRewriter initialized

MPS GPU detected and available

Initializing reranker model on mps

RerankerModule initialized with cross-encoder/ms-marco-MiniLM-L-6-v2 on mps

RetrievalEngine initialized

🔗 Initialized Model Interface
📡 API Base URL: https://api.orq.ai/v2/proxy
🤖 Available Models: 14
🔄 Rate Limiting: 5 retries, 1.0s base delay

DualRetrieval initialized

In [7]:
import random

import openai
from openai import OpenAI

from context_is_king.rag_pipeline.retrieval.engine import extract_retry_delay

openai_client = OpenAI(
    base_url=os.getenv("ORQ_BASE_URL"),
    api_key=os.getenv("ORQ_API_KEY"),
)
# openai_client.embeddings.create(input='test', model='azure/text-embedding-3-small')

# Test a simple query
test_query = "What is machine learning?"
print(f"🔍 Testing query: '{test_query}'")


async def base_retrieval(
    query: str,
    collection: Collection,
    k: int = 5,
    dimensions: int = EMBEDDING_DIMENSION,
    retries: int = 4,
    *,
    shuffle: bool = False,
):
    # Generate embedding for query
    query_embedding = None
    for i in range(retries):
        try:
            query_response = await client_async.embeddings.create(
                model="azure/text-embedding-3-small",
                input=[query],
                dimensions=dimensions,
            )
            query_embedding = query_response.data[0].embedding
            break
        except openai.RateLimitError as e:
            sleep_duration = extract_retry_delay(error_message=str(e))
            logger.error(
                f"Judge evaluation attempt {i + 1} failed. Sleeping for {sleep_duration} seconds: {type(e)} - {e}"
            )
            await asyncio.sleep(sleep_duration + 1 + random.uniform(1, 10))  # Exponential backoff
        except Exception as e:
            if "400" in str(e):
                logger.error(f"Bad request error, not retrying: {e}")
                return []
            sleep_duration = 2**i
            logger.error(f"llm call iteration {i} failed. Sleeping for {sleep_duration} type={type(e)}: {e}")
            await asyncio.sleep(sleep_duration + random.uniform(1, 10))
            continue
    if query_embedding is None:
        logger.error(f'Failed to get embedding after {retries} retries')
        return []

    # Query ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding], n_results=k, include=["documents", "metadatas", "distances"]
    )
    formatted_results = retrieval_engine._convert_to_retrieval_results(chroma_results=results, query=query)
    if shuffle:
        random.shuffle(formatted_results)

    return formatted_results


results = await base_retrieval(test_query, collection=test_collection, k=3, shuffle=True)

print(results)

🔍 Testing query: 'What is machine learning?'
[RetrievalResult(chunk=DocumentChunk(content='Tools\n\nWhat links hereRelated changesUpload fileSpecial pagesPermanent linkPage informationWikidata itemCite this page \n\nPrint/export\n\nCreate a bookDownload as PDFPrintable version \n\nLanguages\n\nČeštinaFrançaisItalianoРусский \nEdit links \n\n This page was last edited on 27 April 2018, at 07:56.\nText is available under the Creative Commons Attribution-ShareAlike License;\nadditional terms may apply.  By using this site, you agree to the Terms of Use and Privacy Policy. Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a non-profit organization.\n\nPrivacy policy\nAbout Wikipedia\nDisclaimers\nContact Wikipedia\nDevelopers\nCookie statement\nMobile view\nEnable previews', doc_id='', chunk_id='286b4c85-8b81-49f2-8e2c-66c8acd70b81', start_char=0, end_char=0, metadata={'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Crossing_(TV_series)&amp;oldid=838475719', 'collection_name': 'wikiqa_The_Crossing_TV_series', 'cache_name': 'wikiqa_The_Crossing_TV_series_1'}, full_id='_286b4c85-8b81-49f2-8e2c-66c8acd70b81'), similarity_score=0.5150219820106553, rank=1, reranked=False, rerank_score=None, final_score=0.5150219820106553), RetrievalResult(chunk=DocumentChunk(content='No.\nTitle\u200a[1]\nDirected by\nWritten by\nOriginal air date\nU.S. viewers\n(millions)\n\n1\n"Pilot"\nRob Bowman\nDan Dworkin & Jay Beattie\nApril\xa02,\xa02018\xa0(2018-04-02)[a]\n5.40[19]\n\nPeople are deep underwater in the ocean. A woman pushes a child toward the surface and disappears below. Sheriff Jude Ellis is called to the beach to investigate a body that washed ashore. Upon arriving, he and his deputy discover more bodies on the beach and hundreds more in the water. There are a total of 47 survivors, all claiming to be fleeing a war 180 years in the future. They heard of a way to bend time to get to "The Long Peace". They were running from Apex, a race of more evolved humans with extraordinary abilities that took over all governments and began exterminating normal humans. FBI Agent Emma Ren takes charge and restricts the sheriff\'s access. The woman shown previously is rescued by fishermen, sees a televised report of only dead washing ashore (an FBI cover story), ambushes Jude and orders him to take her to the dead. She does not find the girl she tried to help. Jude tells her the child is alive. When armed security agents close in, the woman overpowers both of them and Jude and escapes, revealing herself to be an Apex by her incredible physical abilities. She later appears in Jude\'s home, where he learns that her name is Reece and that she is looking for her daughter, Leah. Thomas, a survivor, claims that their group was not the first to cross. He meets Ren\'s boss, Craig Lindauer, the deputy head of Homeland Security, but to his horror recognizes Lindauer as part of the earlier migration.\n\n2\n"A Shadow Out of Time"\nDavid Von Ancken\nDan Dworkin & Jay Beattie\nApril\xa09,\xa02018\xa0(2018-04-09)\n4.48[20]', doc_id='', chunk_id='9f273f14-9682-4c8c-9a99-7417fb8767aa', start_char=0, end_char=0, metadata={'cache_name': 'wikiqa_The_Crossing_TV_series_1', 'collection_name': 'wikiqa_The_Crossing_TV_series', 'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Crossing_(TV_series)&amp;oldid=838475719'}, full_id='_9f273f14-9682-4c8c-9a99-7417fb8767aa'), similarity_score=0.5097271191844058, rank=2, reranked=False, rerank_score=None, final_score=0.5097271191844058), RetrievalResult(chunk=DocumentChunk(content='2\n"A Shadow Out of Time"\nDavid Von Ancken\nDan Dworkin & Jay Beattie\nApril\xa09,\xa02018\xa0(2018-04-09)\n4.48[20]\n\nReece and Leah\'s backstory is told in a series of flashbacks. In 2187, Reece and another armed Apex agent search a building for "Commons", non-mutated humans. Inside they find a dead man, killed by the incurable disease Apex created to wipe out normal humanity. They also discover a healthy baby. Reece\'s partner prepares to shoot the infant, per standard procedure, but Reece kills him and raises the baby in secret. When Leah is a young girl, she contracts the disease. Reece buys black market medical help; the man gives Leah some of Reece\'s blood in the hope that Reece\'s Apex immunity can help Leah fight the disease. When Reece\'s superiors find out about Leah and confront Reece, she shoots them and flees. In the present, Jude makes a bargain with her: he will help her find Leah in exchange for her leaving town. He tries to arrange a meeting between Reece and Ren, but Ren notifies Lindauer, who sends heavily armed men. Reece is shot, but gets away. Meanwhile, Leah is found to have the disease and is quickly quarantined.\n\n3\n"Pax Americana"\nKen Girotti\nMichael Narducci\nApril\xa016,\xa02018\xa0(2018-04-16)\n4.09[21]', doc_id='', chunk_id='e0930351-f383-4901-af4c-7b67418aa1c6', start_char=0, end_char=0, metadata={'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Crossing_(TV_series)&amp;oldid=838475719', 'cache_name': 'wikiqa_The_Crossing_TV_series_1', 'collection_name': 'wikiqa_The_Crossing_TV_series'}, full_id='_e0930351-f383-4901-af4c-7b67418aa1c6'), similarity_score=0.5072478333174301, rank=3, reranked=False, rerank_score=None, final_score=0.5072478333174301)]

In [8]:
results = await dual_retrieval.retrieve_dual("What is machifne learning?", k=3, collection=test_collection, dimensions=EMBEDDING_DIMENSION)
results.model_dump().keys()

dict_keys(['original_query', 'rewritten_query', 'original_results', 'rewritten_results', 'combined_results', 'fusion_metadata', 'total_time_ms'])

In [9]:
from context_is_king.rag_pipeline.types import RetrievalResult

def create_rag_prompt(query: str, retrieved_contexts: list[RetrievalResult] | str) -> tuple[str, str]:

    # Format retrieved contexts
    context_section = ""
    if not isinstance(retrieved_contexts, str):
        for i, context in enumerate(retrieved_contexts, 1):
            context_section += f"<chunk {i}>\n{context.chunk.content.strip()}\n<chunk {i}>\n\n"
    else:
        context_section = retrieved_contexts

    rag_prompt_template = textwrap.dedent(f"""
You are a helpful assistant that answers questions based on the provided context information.

<context>
{context_section}
</context>

INSTRUCTIONS:
- Answer the question using ONLY the information provided in the contexts above
- If the contexts don't contain enough information to answer the question, say "I don't have enough information in the provided contexts to answer this question"
- Be specific and cite which context(s) you're drawing information from
- If contexts contradict each other, mention this explicitly
- Keep your answer concise but complete

QUESTION: {query}

ANSWER:""")
    return rag_prompt_template, context_section


print(create_rag_prompt("What is machine learning?", results.combined_results[:3])[:200])

('\nYou are a helpful assistant that answers questions based on the provided context information.\n\n<context>\n<chunk 1>\nTools\n\nWhat links hereRelated changesUpload fileSpecial pagesPermanent linkPage informationWikidata itemCite this page \n\nPrint/export\n\nCreate a bookDownload as PDFPrintable version \n\nLanguages\n\nČeštinaFrançaisItalianoРусский \nEdit links \n\n This page was last edited on 27 April 2018, at 07:56.\nText is available under the Creative Commons Attribution-ShareAlike License;\nadditional terms may apply.  By using this site, you agree to the Terms of Use and Privacy Policy. Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a non-profit organization.\n\nPrivacy policy\nAbout Wikipedia\nDisclaimers\nContact Wikipedia\nDevelopers\nCookie statement\nMobile view\nEnable previews\n<chunk 1>\n\n<chunk 2>\nExternal links[edit]\n\nOfficial website\nThe Crossing on IMDb \n\n[hide]\n\nv\nt\ne\n\nABC programming (current and upcoming)\n\nPrimetime\n\n20/20 (since 1978)\n20/20: In an Instant (since 2015)\nThe $100,000 Pyramid (since 2016)\nAgents of S.H.I.E.L.D. (since 2013)\nAlex, Inc. (since 2018)\nAmerica\'s Funniest Home Videos (since 1989)\nAmerican Housewife (since 2016)\nAmerican Idol (since 2018)\nThe Bachelor (since 2002)\nThe Bachelor Winter Games (since 2018)\nThe Bachelorette (2003–2005; since 2008)\nBachelor in Paradise (since 2014)\nBachelor in Paradise: After Paradise (since 2015)\nBattle of the Network Stars (since 2017)\nBlack-ish (since 2014)\nBoy Band (since 2017)\nCelebrity Family Feud (since 2015)\nChild Support (since 2018)\nThe Crossing (since 2018)\nDancing with the Stars (since 2005)\nDeception (since 2018)\nDesignated Survivor (since 2016)\nFor the People (since 2018)\nFresh Off the Boat (since 2015)\nThe Goldbergs (since 2013)\nThe Gong Show (since 2017)\nThe Good Doctor (since 2017)\nThe Great American Baking Show (since 2015)\nThe Great Christmas Light Fight (since 2013)\nGrey\'s Anatomy (since 2005)\nHow to Get Away with Murder (since 2014)\nInhumans (since 2017)\nKevin (Probably) Saves the World (since 2017)\nMatch Game (since 2016)\nThe Middle (since 2009)\nModern Family (since 2009)\nOnce Upon a Time (since 2011)\nQuantico (since 2015)\nRoseanne (1988–1997; since 2018)\nShark Tank (since 2009)\nSteve Harvey\'s Funderdome (since 2017)\nSomewhere Between (since 2017)\nSpeechless (since 2016)\nSplitting Up Together (since 2018)\nStation 19 (since 2018)\nThe Toy Box (since 2017)\nTo Tell the Truth (since 2016)\n\nDaytime\n\nThe Chew (since 2011)\nGeneral Hospital (since 1963)\nThe View (since 1997)\n\nLate night\n\nJimmy Kimmel Live! (since 2003)\nNightline (since 1980)\n\nNews\n<chunk 2>\n\n<chunk 3>\n3\n"Pax Americana"\nKen Girotti\nMichael Narducci\nApril\xa016,\xa02018\xa0(2018-04-16)\n4.09[21]\n\nReece is tracked in the forest by Lindauer\'s heavily armed men, but she easily neutralizes them. She kills the head of the search team when he, thinking he has her incapacitated, reveals he is an earlier migrant. Roy, a guard, is attracted to survivor Hannah. Luke threatens to expose Hannah\'s past to the others unless she cooperates with him. She sneaks out of camp in the back of Roy\'s pickup truck. At a concert, part of the town\'s "Harborfest" celebration, Hannah meets Marshall. After a while, she spots a young man who looks exactly like the guy in the photo in her lost locket. Roy finds Hannah and takes her back, with Jude\'s help. Jude is enjoying Harborfest with his son Oliver, who was dropped off by Oliver\'s mother. When Jude is called away to check out a dead body (Reece\'s victim), Oliver disappears. Lindauer recruits Thomas, then sends virologist Dr. Sophie Forbin to find out all she can about the disease, but states that saving Leah\'s life is not a priority. After speaking with Forbin, Ren starts to suspect that Lindauer has a hidden agenda. She reaches out to Jude, but he no longer trusts her.\n\n4\n"The Face of Oblivion"\nTara Nicole Weyr\nEvan Bleiweiss\nApril\xa023,\xa02018\xa0(2018-04-23)\n4.08[22]\n<chunk 3>\n\n\n</context>\n\nINSTRUCTIONS:\n- Answer the question using ONLY the information provided in the contexts above\n- If the contexts don\'t contain enough information to answer the question, say "I don\'t have enough information in the provided contexts to answer this question"\n- Be specific and cite which context(s) you\'re drawing information from\n- If contexts contradict each other, mention this explicitly\n- Keep your answer concise but complete\n\nQUESTION: What is machine learning?\n\nANSWER:', '<chunk 1>\nTools\n\nWhat links hereRelated changesUpload fileSpecial pagesPermanent linkPage informationWikidata itemCite this page \n\nPrint/export\n\nCreate a bookDownload as PDFPrintable version \n\nLanguages\n\nČeštinaFrançaisItalianoРусский \nEdit links \n\n This page was last edited on 27 April 2018, at 07:56.\nText is available under the Creative Commons Attribution-ShareAlike License;\nadditional terms may apply.  By using this site, you agree to the Terms of Use and Privacy Policy. Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a non-profit organization.\n\nPrivacy policy\nAbout Wikipedia\nDisclaimers\nContact Wikipedia\nDevelopers\nCookie statement\nMobile view\nEnable previews\n<chunk 1>\n\n<chunk 2>\nExternal links[edit]\n\nOfficial website\nThe Crossing on IMDb \n\n[hide]\n\nv\nt\ne\n\nABC programming (current and upcoming)\n\nPrimetime\n\n20/20 (since 1978)\n20/20: In an Instant (since 2015)\nThe $100,000 Pyramid (since 2016)\nAgents of S.H.I.E.L.D. (since 2013)\nAlex, Inc. (since 2018)\nAmerica\'s Funniest Home Videos (since 1989)\nAmerican Housewife (since 2016)\nAmerican Idol (since 2018)\nThe Bachelor (since 2002)\nThe Bachelor Winter Games (since 2018)\nThe Bachelorette (2003–2005; since 2008)\nBachelor in Paradise (since 2014)\nBachelor in Paradise: After Paradise (since 2015)\nBattle of the Network Stars (since 2017)\nBlack-ish (since 2014)\nBoy Band (since 2017)\nCelebrity Family Feud (since 2015)\nChild Support (since 2018)\nThe Crossing (since 2018)\nDancing with the Stars (since 2005)\nDeception (since 2018)\nDesignated Survivor (since 2016)\nFor the People (since 2018)\nFresh Off the Boat (since 2015)\nThe Goldbergs (since 2013)\nThe Gong Show (since 2017)\nThe Good Doctor (since 2017)\nThe Great American Baking Show (since 2015)\nThe Great Christmas Light Fight (since 2013)\nGrey\'s Anatomy (since 2005)\nHow to Get Away with Murder (since 2014)\nInhumans (since 2017)\nKevin (Probably) Saves the World (since 2017)\nMatch Game (since 2016)\nThe Middle (since 2009)\nModern Family (since 2009)\nOnce Upon a Time (since 2011)\nQuantico (since 2015)\nRoseanne (1988–1997; since 2018)\nShark Tank (since 2009)\nSteve Harvey\'s Funderdome (since 2017)\nSomewhere Between (since 2017)\nSpeechless (since 2016)\nSplitting Up Together (since 2018)\nStation 19 (since 2018)\nThe Toy Box (since 2017)\nTo Tell the Truth (since 2016)\n\nDaytime\n\nThe Chew (since 2011)\nGeneral Hospital (since 1963)\nThe View (since 1997)\n\nLate night\n\nJimmy Kimmel Live! (since 2003)\nNightline (since 1980)\n\nNews\n<chunk 2>\n\n<chunk 3>\n3\n"Pax Americana"\nKen Girotti\nMichael Narducci\nApril\xa016,\xa02018\xa0(2018-04-16)\n4.09[21]\n\nReece is tracked in the forest by Lindauer\'s heavily armed men, but she easily neutralizes them. She kills the head of the search team when he, thinking he has her incapacitated, reveals he is an earlier migrant. Roy, a guard, is attracted to survivor Hannah. Luke threatens to expose Hannah\'s past to the others unless she cooperates with him. She sneaks out of camp in the back of Roy\'s pickup truck. At a concert, part of the town\'s "Harborfest" celebration, Hannah meets Marshall. After a while, she spots a young man who looks exactly like the guy in the photo in her lost locket. Roy finds Hannah and takes her back, with Jude\'s help. Jude is enjoying Harborfest with his son Oliver, who was dropped off by Oliver\'s mother. When Jude is called away to check out a dead body (Reece\'s victim), Oliver disappears. Lindauer recruits Thomas, then sends virologist Dr. Sophie Forbin to find out all she can about the disease, but states that saving Leah\'s life is not a priority. After speaking with Forbin, Ren starts to suspect that Lindauer has a hidden agenda. She reaches out to Jude, but he no longer trusts her.\n\n4\n"The Face of Oblivion"\nTara Nicole Weyr\nEvan Bleiweiss\nApril\xa023,\xa02018\xa0(2018-04-23)\n4.08[22]\n<chunk 3>\n\n')

In [10]:
from typing import Any
import openai

from context_is_king.evaluation.judge_evaluator import extract_retry_delay
from improved_400_error_handling import process_question_with_error_handling, summarize_error_statistics


async def llm_call_with_error_tracking(
    prompt: str,
    client_async,
    model_interface,
    model: str = "gpt-4.1-mini",
    max_tokens: int = 1000,
    temperature: float = 0.0,
    response_model: type[BaseModel] | None = None,
    retries: int = 3,
    timeout: int = 30,
) -> tuple[str | dict[str, Any] | BaseModel, int]:
    """
    Enhanced LLM call that returns structured error information for 400 errors.

    Returns:
        Tuple of (response, token_count) where response can be:
        - String: Successful text response
        - BaseModel: Successful structured response
        - Dict: Error information with keys:
            - error: Error type (e.g., "content_policy", "rate_limit", "unknown")
            - message: Full error message
            - code: HTTP error code (e.g., 400)
            - generated_answer: None (for compatibility)
    """
    for i in range(retries):
        try:
            if response_model:
                completion = await client_async.chat.completions.parse(
                    messages=[{"role": "user", "content": prompt}],
                    response_format=response_model,
                    model=model_interface.get_model_config(model).api_name,
                    temperature=temperature,
                    timeout=timeout,
                )
                message = completion.choices[0].message
                if message.parsed:
                    return message.parsed, completion.usage.prompt_tokens
            else:
                response = await client_async.chat.completions.create(
                    model=model_interface.get_model_config(model).api_name,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=max_tokens,
                    temperature=temperature,
                    timeout=timeout,
                )
                msg = response.choices[0].message.content
                if hasattr(response, "usage") and hasattr(response.usage, "prompt_tokens"):
                    return msg, response.usage.prompt_tokens
                return msg, 0

        except openai.RateLimitError as e:  # noqa: PERF203
            # Try with fallback model for rate limits
            if i == 0 and not response_model:  # Only try fallback once
                try:
                    response = await llm_call_with_error_tracking(
                        prompt=prompt,
                        client_async=client_async,
                        model_interface=model_interface,
                        model="gemini-2.5-flash",
                        retries=1,
                        timeout=timeout,
                        response_model=response_model,
                        temperature=temperature,
                        max_tokens=max_tokens,
                    )
                    return response
                except Exception:  # noqa: S110
                    pass  # Continue with regular retry logic

            sleep_duration = extract_retry_delay(error_message=str(e))
            logger.error(f"LLM Call attempt {i + 1} failed. Sleeping for {sleep_duration} seconds: {type(e)} - {e}")
            await asyncio.sleep(sleep_duration + 1)

        except Exception as e:
            error_str = str(e)

            # Handle 400 errors (content policy violations)
            if "400" in error_str:
                logger.error(f"Bad request error (content policy), not retrying: {e}")

                # Parse error details if possible
                error_info = {
                    "error": "content_policy",
                    "message": error_str,
                    "code": 400,
                    "generated_answer": None,
                }

                # Try to extract more specific error message
                if "content management policy" in error_str or "content filtering" in error_str:
                    error_info["error"] = "content_policy"
                elif "invalid request" in error_str:
                    error_info["error"] = "invalid_request"
                else:
                    error_info["error"] = "bad_request"

                return error_info, 0

            # Other errors - retry with exponential backoff
            sleep_duration = 2**i
            logger.error(f"llm call iteration {i} failed. Sleeping for {sleep_duration} type={type(e)}: {e}")
            await asyncio.sleep(sleep_duration)

    # All retries exhausted
    logger.error(f"All {retries} retries exhausted for LLM call")
    return {
        "error": "max_retries_exceeded",
        "message": f"Failed after {retries} attempts",
        "code": None,
        "generated_answer": None,
    }, 0


# async def llm_call(
#     prompt: str,
#     model: str = "gpt-4.1-mini",
#     max_tokens: int = 1000,
#     temperature: float = 0.0,
#     response_model: type[BaseModel] | None = None,
#     retries: int = 3,
#     timeout: int = 30,
# ):
#     for i in range(retries):
#         try:
#             if response_model:
#                 completion = await client_async.chat.completions.parse(
#                     messages=[{"role": "user", "content": prompt}],
#                     response_format=response_model,
#                     model=model_interface.get_model_config(model).api_name,
#                     temperature=temperature,
#                     timeout=timeout,
#                 )
#                 message = completion.choices[0].message
#                 if message.parsed:
#                     return message.parsed, completion.usage.prompt_tokens
#             else:
#                 response = await client_async.chat.completions.create(
#                     model=model_interface.get_model_config(model).api_name,
#                     messages=[
#                         # {"role": "system", "content": "You are a helpful assistant that answers questions based on the provided context information."},
#                         {"role": "user", "content": prompt}
#                     ],
#                     max_tokens=max_tokens,
#                     temperature=temperature,
#                     timeout=timeout,
#                 )
#                 msg = response.choices[0].message.content
#                 if hasattr(response, "usage") and hasattr(response.usage, "prompt_tokens"):
#                     return msg, response.usage.prompt_tokens
#                 return msg, 0
#         except openai.RateLimitError as e:  # noqa: PERF203
#             if model == 'gpt-4.1-mini' and i == 1:
#                 logger.info('Retrying call with gemini-2.5-flash')
#                 response = llm_call(
#                     prompt=prompt,
#                     model="gemini-2.5-flash",
#                     retries=1,
#                     timeout=timeout,
#                     response_model=response_model,
#                     temperature=temperature,
#                     max_tokens=max_tokens,
#                 )
#             sleep_duration = extract_retry_delay(error_message=str(e))
#             logger.error(f"LLM Call attempt {i + 1} failed. Sleeping for {sleep_duration} seconds: {type(e)} - {e}")
#             await asyncio.sleep(sleep_duration + 1)  # Exponential backoff
#         except Exception as e:
#             if "400" in str(e):
#                 logger.error(f"Bad request error, not retrying: {e}")
#                 return "", 0
#             sleep_duration = 2**i
#             logger.error(f"llm call iteration {i} failed. Sleeping for {sleep_duration} type={type(e)}: {e}")
#             await asyncio.sleep(sleep_duration)
#     return "", 0


# await llm_call("hi whats you name?", model="gpt-4.1")


class AnswerModel(BaseModel):
    test_field: str = Field(..., description="Just a test field")


# await llm_call("hi whats you name?", model="gpt-4.1-mini", response_model=AnswerModel, retries=1, timeout=5)

await llm_call_with_error_tracking(
    "hi give me a sheep riddle",
    model="gpt-4.1-mini",
    response_model=AnswerModel,
    retries=1,
    timeout=5,
    client_async=client_async,
    model_interface=model_interface,
)

(AnswerModel(test_field="Sure! Here's a sheep riddle for you:\n\nI wander in pastures, fluffy and white,\nCounting me all day, out of sight.\nWith wool to shear and a soft bleat sound,\nWhat am I that's always around?"),
 62)

In [11]:

def extract_context_from_stage_output(stage_output):
    """Extract context text from stage output data"""
    # Handle pandas Series/NaN values properly
    if stage_output is None or stage_output == "":
        return ""

    try:
        # Parse the stage output if it's a string
        if isinstance(stage_output, str):
            stage_data = json.loads(stage_output)
        else:
            stage_data = stage_output

        # Extract content from chunks
        context_texts = []
        if isinstance(stage_data, list):
            for item in stage_data:
                content = item.chunk.content if hasattr(item, 'chunk') and hasattr(item.chunk, 'content') else None
                if content:  # Only add non-empty content
                    context_texts.append(str(content))

        return "\n".join(context_texts)
    except (json.JSONDecodeError, AttributeError, KeyError, TypeError):
        # If parsing fails, try to return the raw content as string
        try:
            return str(stage_output) if stage_output else ""
        except:
            return ""

In [12]:
from json import JSONDecodeError
from tqdm.auto import tqdm
from typing import Any
import tiktoken
import aiofiles
from collections.abc import MutableMapping

tokenizer = tiktoken.encoding_for_model("gpt-4o")


def dump_pydantic_models(obj: Any) -> Any:
    """
    Recursively converts any Pydantic models found in nested structures to dictionaries.

    Args:
        obj: Can be a dict, list, Pydantic model, or any other type

    Returns:
        The same structure but with all Pydantic models converted to dicts
    """
    if isinstance(obj, BaseModel):
        return obj.model_dump()

    elif isinstance(obj, dict):
        return {key: dump_pydantic_models(value) for key, value in obj.items()}

    elif isinstance(obj, list):
        return [dump_pydantic_models(item) for item in obj]

    elif isinstance(obj, tuple):
        return tuple(dump_pydantic_models(item) for item in obj)

    elif isinstance(obj, set):
        return {dump_pydantic_models(item) for item in obj}

    else:
        return obj


def count_tokens_approximate(text: str, tokenizer):
    """Approximate token count using tiktoken (GPT-4 tokenizer)"""
    if text is None or text == "":
        return 0

    try:
        # Use GPT-4 tokenizer for approximation
        tokens = tokenizer.encode(str(text))
        return len(tokens)
    except Exception:
        # Fallback: rough approximation (4 chars per token on average)
        text_str = str(text) if text else ""
        return max(1, len(text_str) // 4) if text_str else 0


def flatten(dictionary: dict, parent_key: str = "", separator: str = "_"):
    items = []
    for key, value in dictionary.items():
        new_key = parent_key + separator + key if parent_key else key
        if isinstance(value, MutableMapping):
            items.extend(flatten(value, new_key, separator=separator).items())
        else:
            items.append((new_key, value))
    return dict(items)


# async def run_single_experiment_improved(
#     qa_pairs,
#     cleaned_df,  # Your polars LazyFrame
#     k: int = 3,
#     iterations_per_question: int = 3,
#     retrieval_kind: str = "basic_rag",
#     *,
#     rerank: bool = True,
#     n_questions: int | None = None,
#     force_new: bool = False,
#     retries: int = 3,
# ):
#     """
#     Improved version of your run_single_experiment function with safe checkpointing.
#     Uses existing notebook variables: chroma_client, tokenizer, etc.
#     """

#     checkpoint_manager = SafeCheckpointManager()
#     n_questions = n_questions or len(qa_pairs)

#     # Start or resume experiment safely
#     experiment_id, is_resume, is_completed = await checkpoint_manager.start_experiment(
#         k=k, retrieval_kind=retrieval_kind, rerank=rerank, n_questions=n_questions, force_new=force_new
#     )

#     # If experiment is already completed, return cached results immediately
#     if is_completed:
#         logger.info(f"Experiment {experiment_id} already completed, loading cached results")
#         return await checkpoint_manager.load_completed_experiment_results(experiment_id)

#     if is_resume:
#         # Get completed questions to skip
#         completed_questions = await checkpoint_manager.get_completed_questions(experiment_id)
#         logger.info(f"Resuming experiment {experiment_id}: {len(completed_questions)} questions already completed")
#     else:
#         completed_questions = set()
#         logger.info(f"Starting new experiment {experiment_id}")

#     try:
#         # Create progress bar for questions
#         questions_to_process = [
#             (q_index, doc)
#             for q_index, doc in enumerate(qa_pairs)
#             if q_index not in completed_questions and doc.get("probability_human", 0) >= 0.8
#         ][:n_questions]

#         logger.info(f"Processing {len(questions_to_process)} questions (skipping {len(completed_questions)} completed)")

#         # Process questions with checkpoint recovery and progress bar
#         progress_bar = tqdm(
#             questions_to_process, desc=f"Experiment {experiment_id[:16]}...", unit="questions", disable=False
#         )

#         for q_index, doc in progress_bar:
#             # Update progress bar description with current question
#             progress_bar.set_postfix({"q_idx": q_index, "retrieval": retrieval_kind, "k": k, "rerank": rerank})

#             # Get collection for this document
#             collection = chroma_client.get_collection(f"wikiqa_{doc['collection_suffix']}")
#             if collection.count() == 0:
#                 logger.warning(f"Collection {collection.name} is empty, skipping question {q_index}")
#                 continue

#             question = doc["generated_question"]
#             ground_truth = doc["answer"]
#             ground_truth_chunk_id = doc["main_chunk_id"]

#             # Your existing experiment logic here
#             question_results = []

#             # Process this question with your existing logic
#             is_full_context = retrieval_kind == "full_context"

#             if is_full_context:
#                 # Full context logic
#                 stage2_output = (
#                     cleaned_df.filter(pl.col("document_url") == doc["document_url"][0])
#                     .select(pl.col("document_text"))
#                     .collect()
#                     .to_series()
#                     .to_list()[0]
#                 )
#                 context_token_count = count_tokens_approximate(stage2_output, tokenizer)
#                 retrieval_performance_results = None
#             else:
#                 # RAG logic - your existing retrieval code
#                 if retrieval_kind == "basic_rag":
#                     stage1_output = await base_retrieval(
#                         query=question, k=k, collection=collection, dimensions=EMBEDDING_DIMENSION, retries=retries
#                     )
#                 elif retrieval_kind == "enhanced_rag":
#                     stage1_output = (
#                         await dual_retrieval.retrieve_dual(
#                             question, k=k, collection=collection, use_async=True, dimensions=EMBEDDING_DIMENSION
#                         )
#                     ).combined_results

#                 if rerank:
#                     stage2_output = reranker.rerank_results(query=question, retrieval_results=stage1_output)
#                 else:
#                     stage2_output = stage1_output

#                 # Calculate retrieval metrics
#                 k_range = [x for x in [1, 5, 10, 20, 50, 100] if x <= k]
#                 retrieval_performance_results = retrieval_engine.calculate_retrieval_metrics(
#                     retrieved_chunks=stage2_output,
#                     ground_truth_chunk_ids=[ground_truth_chunk_id],
#                     k_values=k_range,
#                 )
#                 context_token_count = count_tokens_approximate(
#                     extract_context_from_stage_output(stage2_output), tokenizer
#                 )

#             # Generate answers and evaluate (your existing logic)
#             rag_prompt, context_section = create_rag_prompt(query=question, retrieved_contexts=stage2_output)

#             for i in range(iterations_per_question):
#                 generated_answer, input_tokens = await llm_call_with_error_tracking(
#                     prompt=rag_prompt,
#                     model=config.small_llm,
#                     max_tokens=2000,
#                     temperature=0.1,
#                     retries=retries,
#                     client_async=client_async,
#                     model_interface=model_interface,
#                 )

#                 judge_result = await judge.evaluate_answer(
#                     question=question,
#                     expected_answer=ground_truth,
#                     model_answer=generated_answer,
#                     context_preview=rag_prompt,
#                     max_retries=retries,
#                 )

#                 if not judge_result:
#                     logger.warning(f"Judge evaluation failed for question {q_index}, iteration {i}")
#                     continue

#                 question_results.append(
#                     {
#                         "question_index": q_index,  # Add explicit question index for tracking
#                         "k": k,
#                         "retrieval_kind": retrieval_kind,
#                         "rerank": rerank,
#                         "n_question": n_questions,
#                         "judge_result": judge_result,
#                         "retrieval_benchmarks": retrieval_performance_results,
#                         "context_token_count": context_token_count,
#                         "generated_answer": generated_answer,
#                         "stage_2_output": stage2_output if not is_full_context else "full_context_used",
#                         "iteration": i,
#                         "retrieved_chunks": len(stage2_output) if isinstance(stage2_output, list) else 1,
#                         **doc,
#                     }
#                 )

#             # Save checkpoint after each question (atomic operation)
#             if question_results:  # Only save if we have results
#                 try:
#                     await checkpoint_manager.save_question_checkpoint(experiment_id, q_index, question_results)
#                     logger.debug(f"Checkpointed question {q_index} with {len(question_results)} results")
#                 except Exception as checkpoint_error:
#                     logger.error(f"Failed to save checkpoint for question {q_index}: {checkpoint_error}")
#                     # Don't raise - continue with other questions but log the failure
#                     # The final experiment status will show if not all questions were saved

#         # Load all results and finalize experiment
#         all_results = await checkpoint_manager.load_checkpoints(experiment_id)

#         if all_results:
#             try:
#                 final_output_path = await checkpoint_manager.finalize_experiment(experiment_id, all_results)
#                 logger.info(f"Experiment completed successfully: {final_output_path}")
#             except Exception as finalize_error:
#                 logger.error(f"Failed to finalize experiment {experiment_id}: {finalize_error}")
#                 await checkpoint_manager._update_experiment_status(experiment_id, "failed")
#                 raise
#         else:
#             logger.warning(f"No results found for experiment {experiment_id}")
#             await checkpoint_manager._update_experiment_status(experiment_id, "failed")

#         return all_results

#     except Exception as e:
#         # Mark experiment as failed with proper error handling
#         try:
#             await checkpoint_manager._update_experiment_status(experiment_id, "failed")
#         except Exception as status_error:
#             logger.error(f"Failed to update experiment status to failed: {status_error}")

#         logger.error(f"Experiment {experiment_id} failed: {e}")
#         raise


# Integration function that uses your existing notebook variables
async def run_single_experiment_improved(
    qa_pairs,
    cleaned_df,  # Your polars LazyFrame
    k: int = 3,
    iterations_per_question: int = 3,
    retrieval_kind: str = "basic_rag",
    *,
    rerank: bool = True,
    n_questions: int | None = None,
    force_new: bool = False,
    retries: int = 3,
):
    """
    Improved version of your run_single_experiment function with safe checkpointing.
    Uses existing notebook variables: chroma_client, tokenizer, etc.
    """

    checkpoint_manager = SafeCheckpointManager()
    n_questions = n_questions or len(qa_pairs)

    # Start or resume experiment safely
    experiment_id, is_resume, is_completed = await checkpoint_manager.start_experiment(
        k=k, retrieval_kind=retrieval_kind, rerank=rerank, n_questions=n_questions, force_new=force_new
    )

    # If experiment is already completed, return cached results immediately
    if is_completed:
        logger.info(f"Experiment {experiment_id} already completed, loading cached results")
        return await checkpoint_manager.load_completed_experiment_results(experiment_id)

    if is_resume:
        # Get completed questions to skip
        completed_questions = await checkpoint_manager.get_completed_questions(experiment_id)
        logger.info(f"Resuming experiment {experiment_id}: {len(completed_questions)} questions already completed")
    else:
        completed_questions = set()
        logger.info(f"Starting new experiment {experiment_id}")

    try:
        # Pre-filter questions to process (more efficient than checking in loop)
        questions_to_process = [
            (q_index, doc) for q_index, doc in enumerate(qa_pairs[:n_questions])
            if q_index not in completed_questions
            and doc.get("probability_human", 0) >= 0.8
        ]

        logger.info(f"Processing {len(questions_to_process)} questions (skipping {len(completed_questions)} completed)")

        # Process questions with checkpoint recovery
        for q_index, doc in tqdm(questions_to_process):

            # Get collection for this document
            collection = chroma_client.get_collection(f"wikiqa_{doc['collection_suffix']}")
            if collection.count() == 0:
                logger.warning(f"Collection {collection.name} is empty, skipping question {q_index}")
                continue

            question = doc["generated_question"]
            ground_truth = doc["answer"]
            ground_truth_chunk_id = doc["main_chunk_id"]

            # Your existing experiment logic here
            question_results = []

            # Process this question with your existing logic
            is_full_context = retrieval_kind == "full_context"

            if is_full_context:
                # Full context logic
                stage2_output = (
                    cleaned_df.filter(pl.col("document_url") == doc["document_url"][0])
                    .select(pl.col("document_text"))
                    .collect()
                    .to_series()
                    .to_list()[0]
                )
                context_token_count = count_tokens_approximate(stage2_output, tokenizer)
                retrieval_performance_results = None
            else:
                # RAG logic - your existing retrieval code
                if retrieval_kind == "basic_rag":
                    stage1_output = await base_retrieval(
                        query=question, k=k, collection=collection, dimensions=EMBEDDING_DIMENSION, retries=retries
                    )
                elif retrieval_kind == "enhanced_rag":
                    stage1_output = (
                        await dual_retrieval.retrieve_dual(
                            question, k=k, collection=collection, use_async=True, dimensions=EMBEDDING_DIMENSION
                        )
                    ).combined_results

                if rerank:
                    stage2_output = reranker.rerank_results(query=question, retrieval_results=stage1_output)
                else:
                    stage2_output = stage1_output

                # Calculate retrieval metrics
                k_range = [x for x in [1, 5, 10, 20, 50, 100] if x <= k]
                retrieval_performance_results = retrieval_engine.calculate_retrieval_metrics(
                    retrieved_chunks=stage2_output,
                    ground_truth_chunk_ids=[ground_truth_chunk_id],
                    k_values=k_range,
                )
                context_token_count = count_tokens_approximate(
                    extract_context_from_stage_output(stage2_output), tokenizer
                )

            # Generate answers and evaluate (your existing logic)
            rag_prompt, context_section = create_rag_prompt(query=question, retrieved_contexts=stage2_output)

            for i in range(iterations_per_question):
                generated_answer, input_tokens = await llm_call_with_error_tracking(
                    prompt=rag_prompt, model=config.small_llm, max_tokens=2000, temperature=0.1, retries=retries, client_async=client_async, model_interface=model_interface
                )

                judge_result = await judge.evaluate_answer(
                    question=question,
                    expected_answer=ground_truth,
                    model_answer=generated_answer,
                    context_preview=rag_prompt,
                    max_retries=retries,
                )

                if not judge_result:
                    logger.warning(f"Judge evaluation failed for question {q_index}, iteration {i}")
                    continue

                question_results.append(
                    {
                        "question_index": q_index,  # Add explicit question index for tracking
                        "k": k,
                        "retrieval_kind": retrieval_kind,
                        "rerank": rerank,
                        "n_question": n_questions,
                        "judge_result": judge_result,
                        "retrieval_benchmarks": retrieval_performance_results,
                        "context_token_count": context_token_count,
                        "generated_answer": generated_answer,
                        "stage_2_output": stage2_output if not is_full_context else "full_context_used",
                        "iteration": i,
                        "retrieved_chunks": len(stage2_output) if isinstance(stage2_output, list) else 1,
                        **doc,
                    }
                )

            # Save checkpoint after each question (atomic operation)
            if question_results:  # Only save if we have results
                await checkpoint_manager.save_question_checkpoint(experiment_id, q_index, question_results)
                logger.debug(f"Checkpointed question {q_index} with {len(question_results)} results")

        # Load all results and finalize experiment
        all_results = await checkpoint_manager.load_checkpoints(experiment_id)

        if all_results:
            final_output_path = await checkpoint_manager.finalize_experiment(experiment_id, all_results)
            logger.info(f"Experiment completed successfully: {final_output_path}")
        else:
            logger.warning(f"No results found for experiment {experiment_id}")

        return all_results

    except Exception as e:
        # Mark experiment as failed
        await checkpoint_manager._update_experiment_status(experiment_id, "failed")
        logger.error(f"Experiment {experiment_id} failed: {e}")
        raise

async def test_checkpoint_system():
    """Quick test of the checkpoint system with your existing notebook setup."""

    # Test with just one question
    test_results = await run_single_experiment_improved(
        qa_pairs=filtering_results[:2],  # Just 2 questions for testing
        cleaned_df=html_cleaned_df,
        k=5,
        retrieval_kind="enhanced_rag",
        rerank=False,
        n_questions=2,
        force_new=False,  # Force new to test fresh creation
        iterations_per_question=1,  # Just one iteration for speed
    )

    print(f"✅ Test completed: {len(test_results)} results")
    return test_results


test_results = await test_checkpoint_system()
test_results

2025-09-20 15:51:52 | INFO     | improved_checkpoint_system:start_experiment:363 - Found completed experiment but insufficient data (0 < 1.6)
2025-09-20 15:51:52 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 5_enhanced_rag_False_2_1758376312_f6658091
2025-09-20 15:51:52 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 5_enhanced_rag_False_2_1758376312_f6658091
2025-09-20 15:51:52 | INFO     | __main__:run_single_experiment_improved:308 - Processing 2 questions (skipping 0 completed)

  0%|          | 0/2 [00:00<?, ?it/s]

2025-09-20 15:52:11 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_2_1758376312_f6658091.parquet

✅ Test completed: 2 results

[{'question_index': 0,
  'k': 5,
  'retrieval_kind': 'enhanced_rag',
  'rerank': False,
  'n_question': 2,
  'judge_result': {'absolute_assessment': {'is_correct': True,
    'confidence': 1.0,
    'reasoning': "The model's answer matches the expected answer by stating that Neil Sandilands joined the main cast of The Flash in season 4 alongside the returning principal cast members. It also names the returning cast members, which is supplementary information but does not contradict or misrepresent the core answer."},
   'context_grounded_assessment': {'is_correct_given_context': True,
    'confidence': 1.0,
    'reasoning': "The provided contexts (chunks 1, 2, and 3) clearly demonstrate that Neil Sandilands joined the principal cast, listing him alongside the returning main cast members. The model's answer accurately reflects this information, and all named cast members are explicitly listed in the 'Starring' section in the context."},
   'answer_completeness': 1.0,
   'context_utilization': 1.0},
  'retrieval_benchmarks': {'precision@1': 1.0,
   'recall@1': 1.0,
   'f1@1': 1.0,
   'precision@5': 0.2,
   'recall@5': 1.0,
   'f1@5': 0.33333333333333337,
   'mrr': 1.0,
   'hit_rate': 1.0,
   'avg_similarity': 0.025560119378535563,
   'max_similarity': 0.03278688524590164,
   'min_similarity': 0.015625},
  'context_token_count': 2277,
  'generated_answer': 'Neil Sandilands joined the main cast of The Flash in season 4 alongside the returning principal cast members Grant Gustin, Candice Patton, Danielle Panabaker, Carlos Valdes, Keiynan Lonsdale, Tom Cavanagh, and Jesse L. Martin (Contexts: chunks 1, 2, and 3).',
  'stage_2_output': [{'chunk': {'content': 'The Flash (season 4) - Wikipedia\n\n \n\nThe Flash (season 4) \nFrom Wikipedia, the free encyclopedia \n\n\t\t\t\t\tJump to:\t\t\t\t\tnavigation, \t\t\t\t\tsearch\n\nThe Flash (season\xa04)\n\nPromotional poster\n\nStarring\n\nGrant Gustin\nCandice Patton\nDanielle Panabaker\nCarlos Valdes\nKeiynan Lonsdale\nNeil Sandilands\nTom Cavanagh\nJesse L. Martin\n\nCountry of origin\nUnited States\n\nNo. of episodes\n19\n\nRelease\n\nOriginal network\nThe CW\n\nOriginal release\nOctober 10, 2017\xa0(2017-10-10)\xa0– present\xa0(present)\n\nSeason chronology\n\n←\xa0Previous\nSeason 3\n\nList of The Flash episodes\n\nThe fourth season of the American television series The Flash, which is based on the DC Comics character Barry Allen / Flash, follows a crime scene investigator with superhuman speed who fights criminals, including others who have also gained superhuman abilities. It is set in the Arrowverse, sharing continuity with the other television series of the universe, and is a spin-off of Arrow. The season is produced by Berlanti Productions, Warner Bros. Television, and DC Entertainment, with Andrew Kreisberg and Todd Helbing serving as showrunners.\nThe season was ordered in January 2017, and filming began that July. Grant Gustin stars as Barry, with principal cast members Candice Patton, Danielle Panabaker, Carlos Valdes, Keiynan Lonsdale, Tom Cavanagh, and Jesse L. Martin also returning from previous seasons, and are joined by Neil Sandilands.\nThe fourth season began airing on October 10, 2017, and is set to run for 23 episodes on The CW until May 22, 2018.[1]\n\nContents\n\xa0[hide]\xa0\n\n1 Episodes\n2 Cast and characters\n\n2.1 Main\n2.2 Recurring\n2.3 Guest\n\n3 Production\n\n3.1 Development\n3.2 Writing\n3.3 Casting\n3.4 Filming\n3.5 Music\n3.6 Arrowverse tie-ins\n\n4 Release\n\n4.1 Broadcast\n4.2 Marketing\n\n5 Reception\n\n5.1 Ratings\n5.2 Critical response\n5.3 Accolades\n\n6 References\n7 External links',
     'doc_id': '',
     'chunk_id': '88de4634-c65b-449e-8407-42920a3fba48',
     'start_char': 0,
     'end_char': 0,
     'metadata': {'collection_name': 'wikiqa_The_Flash_season_4',
      'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882',
      'cache_name': 'wikiqa_The_Flash_season_4_187'},
     'full_id': '_88de4634-c65b-449e-8407-42920a3fba48'},
    'similarity_score': 0.03278688524590164,
    'rank': 1,
    'reranked': False,
    'rerank_score': None,
    'final_score': 0.03278688524590164},
   {'chunk': {'content': 'The Flash (season 4) - Wikipedia\n\n \n\nThe Flash (season 4) \nFrom Wikipedia, the free encyclopedia \n\n\t\t\t\t\tJump to:\t\t\t\t\tnavigation, \t\t\t\t\tsearch\n\nThe Flash (season\xa04)\n\nPromotional poster\n\nStarring\n\nGrant Gustin\nCandice Patton\nDanielle Panabaker\nCarlos Valdes\nKeiynan Lonsdale\nNeil Sandilands\nTom Cavanagh\nJesse L. Martin\n\nCountry of origin\nUnited States\n\nNo. of episodes\n19\n\nRelease\n\nOriginal network\nThe CW\n\nOriginal release\nOctober 10, 2017\xa0(2017-10-10)\xa0– present\xa0(present)\n\nSeason chronology\n\n←\xa0Previous\nSeason 3\n\nList of The Flash episodes\n\nThe fourth season of the American television series The Flash, which is based on the DC Comics character Barry Allen / Flash, follows a crime scene investigator with superhuman speed who fights criminals, including others who have also gained superhuman abilities. It is set in the Arrowverse, sharing continuity with the other television series of the universe, and is a spin-off of Arrow. The season is produced by Berlanti Productions, Warner Bros. Television, and DC Entertainment, with Andrew Kreisberg and Todd Helbing serving as showrunners.\nThe season was ordered in January 2017, and filming began that July. Grant Gustin stars as Barry, with principal cast members Candice Patton, Danielle Panabaker, Carlos Valdes, Keiynan Lonsdale, Tom Cavanagh, and Jesse L. Martin also returning from previous seasons, and are joined by Neil Sandilands.\nThe fourth season began airing on October 10, 2017, and is set to run for 23 episodes on The CW until May 22, 2018.[1]\n\nContents\n\xa0[hide]\xa0\n\n1 Episodes\n2 Cast and characters\n\n2.1 Main\n2.2 Recurring\n2.3 Guest\n\n3 Production\n\n3.1 Development\n3.2 Writing\n3.3 Casting\n3.4 Filming\n3.5 Music\n3.6 Arrowverse tie-ins\n\n4 Release\n\n4.1 Broadcast\n4.2 Marketing\n\n5 Reception\n\n5.1 Ratings\n5.2 Critical response\n5.3 Accolades\n\n6 References\n7 External links',
     'doc_id': '',
     'chunk_id': '2445af72-9976-477c-8f60-df9020713eee',
     'start_char': 0,
     'end_char': 0,
     'metadata': {'cache_name': 'wikiqa_The_Flash_season_4_187',
      'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882',
      'collection_name': 'wikiqa_The_Flash_season_4'},
     'full_id': '_2445af72-9976-477c-8f60-df9020713eee'},
    'similarity_score': 0.03200204813108039,
    'rank': 2,
    'reranked': False,
    'rerank_score': None,
    'final_score': 0.03200204813108039},
   {'chunk': {'content': 'The Flash (season 4) - Wikipedia\n\n \n\nThe Flash (season 4) \nFrom Wikipedia, the free encyclopedia \n\n\t\t\t\t\tJump to:\t\t\t\t\tnavigation, \t\t\t\t\tsearch\n\nThe Flash (season\xa04)\n\nPromotional poster\n\nStarring\n\nGrant Gustin\nCandice Patton\nDanielle Panabaker\nCarlos Valdes\nKeiynan Lonsdale\nNeil Sandilands\nTom Cavanagh\nJesse L. Martin\n\nCountry of origin\nUnited States\n\nNo. of episodes\n19\n\nRelease\n\nOriginal network\nThe CW\n\nOriginal release\nOctober 10, 2017\xa0(2017-10-10)\xa0– present\xa0(present)\n\nSeason chronology\n\n←\xa0Previous\nSeason 3\n\nList of The Flash episodes\n\nThe fourth season of the American television series The Flash, which is based on the DC Comics character Barry Allen / Flash, follows a crime scene investigator with superhuman speed who fights criminals, including others who have also gained superhuman abilities. It is set in the Arrowverse, sharing continuity with the other television series of the universe, and is a spin-off of Arrow. The season is produced by Berlanti Productions, Warner Bros. Television, and DC Entertainment, with Andrew Kreisberg and Todd Helbing serving as showrunners.\nThe season was ordered in January 2017, and filming began that July. Grant Gustin stars as Barry, with principal cast members Candice Patton, Danielle Panabaker, Carlos Valdes, Keiynan Lonsdale, Tom Cavanagh, and Jesse L. Martin also returning from previous seasons, and are joined by Neil Sandilands.\nThe fourth season began airing on October 10, 2017, and is set to run for 23 episodes on The CW until May 22, 2018.[1]\n\nContents\n\xa0[hide]\xa0\n\n1 Episodes\n2 Cast and characters\n\n2.1 Main\n2.2 Recurring\n2.3 Guest\n\n3 Production\n\n3.1 Development\n3.2 Writing\n3.3 Casting\n3.4 Filming\n3.5 Music\n3.6 Arrowverse tie-ins\n\n4 Release\n\n4.1 Broadcast\n4.2 Marketing\n\n5 Reception\n\n5.1 Ratings\n5.2 Critical response\n5.3 Accolades\n\n6 References\n7 External links',
     'doc_id': '',
     'chunk_id': '8d8f00c3-9b31-466c-90b9-56c1721da84a',
     'start_char': 0,
     'end_char': 0,
     'metadata': {'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882',
      'collection_name': 'wikiqa_The_Flash_season_4',
      'cache_name': 'wikiqa_The_Flash_season_4_187'},
     'full_id': '_8d8f00c3-9b31-466c-90b9-56c1721da84a'},
    'similarity_score': 0.03125763125763126,
    'rank': 3,
    'reranked': False,
    'rerank_score': None,
    'final_score': 0.03125763125763126},
   {'chunk': {'content': 'In July 2017, Sterling Gates, DC Comics comic book writer, joined as a member of the fourth season\'s writing staff.[73] At the Television Critics Association press tour in August 2017, Pedowitz stated that the fourth season of The Flash is "going to try to find the lightness... of the Barry Allen of the first two seasons,"[74] and said that the show was likely "done with Speedster villains".[75] Later in the month, Kreisberg confirmed the return of Harry Wells from Earth-2, saying that "season 4 for Harry is really realizing what he\'s missing in his life and what it is he needs to become a better, more complete person, and so he\'s going to be going on a fairly epic emotional journey this season that is tied to the Thinker\'s plan," in addition to confirming the introduction of a new version of the Wells character.[76]\nIn September 2017, Helbing noted "There\'s a lot of love in the air this season," and compared Barry and Iris\' reunion to "somebody going off to war for six months and coming back. There\'s a lot that Iris experienced that Barry didn\'t when he was gone, and it\'s really [about] the fun and the emotional component of making up that time when they weren\'t together." Helbing also explained that the Speed Force "let [Barry] deal with all of the baggage [from the past three seasons]. When he comes out, he\'s sort of left that all behind."[77] That month, Kreisberg also confirmed that Barry and Iris will be getting married this season,[78] while also revealing that the pair will be going to couples therapy since "[they] keep comically clashing inadvertently because [both are] used to being in charge, and so they wind up going... to work through it." He added, "The two of them with the therapist is some of the funniest stuff we have ever done on this show, but it also leads to a deepening of their relationship."[79]\nCasting[edit]',
     'doc_id': '',
     'chunk_id': '971ee29c-ba80-4595-b456-6e48b202c74c',
     'start_char': 0,
     'end_char': 0,
     'metadata': {'collection_name': 'wikiqa_The_Flash_season_4',
      'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882',
      'cache_name': 'wikiqa_The_Flash_season_4_187'},
     'full_id': '_971ee29c-ba80-4595-b456-6e48b202c74c'},
    'similarity_score': 0.016129032258064516,
    'rank': 4,
    'reranked': False,
    'rerank_score': None,
    'final_score': 0.016129032258064516},
   {'chunk': {'content': 'In July 2017, Sterling Gates, DC Comics comic book writer, joined as a member of the fourth season\'s writing staff.[73] At the Television Critics Association press tour in August 2017, Pedowitz stated that the fourth season of The Flash is "going to try to find the lightness... of the Barry Allen of the first two seasons,"[74] and said that the show was likely "done with Speedster villains".[75] Later in the month, Kreisberg confirmed the return of Harry Wells from Earth-2, saying that "season 4 for Harry is really realizing what he\'s missing in his life and what it is he needs to become a better, more complete person, and so he\'s going to be going on a fairly epic emotional journey this season that is tied to the Thinker\'s plan," in addition to confirming the introduction of a new version of the Wells character.[76]\nIn September 2017, Helbing noted "There\'s a lot of love in the air this season," and compared Barry and Iris\' reunion to "somebody going off to war for six months and coming back. There\'s a lot that Iris experienced that Barry didn\'t when he was gone, and it\'s really [about] the fun and the emotional component of making up that time when they weren\'t together." Helbing also explained that the Speed Force "let [Barry] deal with all of the baggage [from the past three seasons]. When he comes out, he\'s sort of left that all behind."[77] That month, Kreisberg also confirmed that Barry and Iris will be getting married this season,[78] while also revealing that the pair will be going to couples therapy since "[they] keep comically clashing inadvertently because [both are] used to being in charge, and so they wind up going... to work through it." He added, "The two of them with the therapist is some of the funniest stuff we have ever done on this show, but it also leads to a deepening of their relationship."[79]\nCasting[edit]',
     'doc_id': '',
     'chunk_id': '31e3ec3b-6fed-473e-85bd-9b22401036b5',
     'start_char': 0,
     'end_char': 0,
     'metadata': {'cache_name': 'wikiqa_The_Flash_season_4_187',
      'collection_name': 'wikiqa_The_Flash_season_4',
      'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882'},
     'full_id': '_31e3ec3b-6fed-473e-85bd-9b22401036b5'},
    'similarity_score': 0.015625,
    'rank': 5,
    'reranked': False,
    'rerank_score': None,
    'final_score': 0.015625}],
  'iteration': 0,
  'retrieved_chunks': 5,
  'probability_human': 0.85,
  'generated_question': 'Who joined the main cast of The Flash in season 4 alongside the returning principal cast members?',
  'question_reasoning': 'The text lists the returning principal cast and specifically mentions Neil Sandilands as being joined to the main cast for this season. Curious viewers or fans often want to know about cast changes or additions between seasons.',
  'main_chunk_id': '88de4634-c65b-449e-8407-42920a3fba48',
  'answer': 'Neil Sandilands joined the main cast of The Flash in season 4 alongside the returning principal cast members.',
  'status': 'question_generation_succeeded',
  'document_url': ['https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882'],
  'collection_suffix': 'The_Flash_season_4'},
 {'question_index': 1,
  'k': 5,
  'retrieval_kind': 'enhanced_rag',
  'rerank': False,
  'n_question': 2,
  'judge_result': {'absolute_assessment': {'is_correct': False,
    'confidence': 0.85,
    'reasoning': "The model's answer nearly matches the ground truth, accurately describing that Becky Sharpe obtained her powers from exposure to transformative dark matter on a bus affected by Barry's escape from the Speed Force and that her powers give her favorable luck while causing misfortune to others. However, it omits the important consequence that her powers 'eventually impacted a wide area and led to dangerous consequences like reactivating the particle accelerator,' which is a key point in the expected answer."},
   'context_grounded_assessment': {'is_correct_given_context': True,
    'confidence': 1.0,
    'reasoning': "Using the provided context, the model accurately restates all critical information found in the chunks: Becky was exposed to transformative dark matter as one of the bus passengers during Barry's escape from the Speed Force, and her powers resulted in favorable luck for herself and misfortune for others. While the context does mention that her powers expanded out of control and reactivated the particle accelerator, the model's omission of that final consequence is minor and does not alter the correctness relative to what is directly asked by the user."},
   'answer_completeness': 0.85,
   'context_utilization': 1.0},
  'retrieval_benchmarks': {'precision@1': 1.0,
   'recall@1': 1.0,
   'f1@1': 1.0,
   'precision@5': 0.2,
   'recall@5': 1.0,
   'f1@5': 0.33333333333333337,
   'mrr': 1.0,
   'hit_rate': 1.0,
   'avg_similarity': 0.03176204245545864,
   'max_similarity': 0.03278688524590164,
   'min_similarity': 0.03076923076923077},
  'context_token_count': 1820,
  'generated_answer': 'Becky Sharpe obtained her metahuman powers after being exposed to transformative dark matter from a busload of people affected by the portal Barry used to escape the Speed Force (Context: chunk 1). Her powers gave her the ability of favorable luck for herself while inducing misfortune to others (Context: chunk 1).',
  'stage_2_output': [{'chunk': {'content': '72\n3\n"Luck Be a Lady"\nArmen V. Kevorkian\nSam Chalsen & Judalina Neira\nOctober\xa024,\xa02017\xa0(2017-10-24)\nT27.13403\n2.62[4]\n\nIn flashbacks, the Thinker observes Becky Sharpe, a woman with seemingly unending bad luck, and determines that she will be easily manipulated. In the present, Becky robs a bank and gets away when Barry slips on marbles. Harry arrives from Earth-2 and tells Wally that Jesse has decided to break up with him in order to focus on her vigilantism. Cisco deduces that Becky is a metahuman with the power of favorable luck while inducing misfortune to others. Barry realizes that the portal he used to escape the Speed Force exposed an entire busload of people, including Becky and Deacon, to transformative dark matter. Harry informs Cisco that Jesse has expelled him from her crime-fighting team due to his attitude. Becky\'s powers expand out of control, reactivating the particle accelerator, which Harry deliberately allows, nullifying Becky\'s powers and leading to her incarceration. Cisco and Harry identify twelve new metahumans created on the bus and the latter suspects that an unknown party has manipulated the events surrounding Barry\'s return. Wally decides to leave on a journey to find himself. The Thinker is revealed to be spying on S.T.A.R. Labs through the "Samuroid" helmet. Joe learns Cecile is pregnant.\n\n73\n4\n"Elongated Journey Into Night"\nTom Cavanagh\nSterling Gates & Thomas Pound\nOctober\xa031,\xa02017\xa0(2017-10-31)\nT27.13404\n1.99[5]',
     'doc_id': '',
     'chunk_id': '2c0c46b8-034d-4819-8807-501c6492c1c4',
     'start_char': 0,
     'end_char': 0,
     'metadata': {'document_url': 'https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882',
      'cache_name': 'wikiqa_The_Flash_season_4_187',
      'collection_name': 'wikiqa_The_Flash_season_4'},
     'full_id': '_2c0c46b8-034d-4819-8807-501c6492c1c4'},
    'similarity_score': 0.03278688524590164,
    'rank': 1,
    'reranked': False,
    'rerank_score': None,
    'final_score': 0.03278688524590164},

In [62]:

async def run_full_experiment_improved(
    clean_df,
    k_range: list[int] | None = None,
    n_questions: int | None = None,
    parallel: int = 3,  # Reduced from 10 to prevent overwhelming the system
    iterations_per_question: int = 3,
    retries: int = 3,
    *,
    force_new: bool = False,
):
    """
    Improved version of your run_full_experiment with better parallelism and checkpointing.
    """
    from functools import reduce
    from itertools import product

    sem = asyncio.Semaphore(parallel)
    k_range = k_range or [1, 5, 10, 50, 100]
    n_questions = n_questions or len(filtering_results)

    # Generate all experiment combinations
    all_combinations = list(product(k_range, ["basic_rag", "enhanced_rag"], [True, False]))
    all_combinations.append((1, "full_context", False))  # Add full context experiment

    async def run_with_semaphore(k, retrieval_kind, rerank):
        async with sem:
            return await run_single_experiment_improved(
                qa_pairs=filtering_results,
                cleaned_df=clean_df,
                k=k,
                retrieval_kind=retrieval_kind,
                rerank=rerank,
                n_questions=n_questions,
                iterations_per_question=iterations_per_question,
                retries=retries,
                force_new=force_new,
            )

    # Create tasks for all experiments
    tasks = []
    # incomplete_experiments = [
    #     # K=1 configurations
    #     (1, "basic_rag", False),
    #     (1, "basic_rag", True),
    #     (1, "enhanced_rag", False),
    #     (1, "enhanced_rag", True),

    #     # K=5 configurations  
    #     (5, "basic_rag", False),
    #     (5, "basic_rag", True),
    #     (5, "enhanced_rag", False),
    #     (5, "enhanced_rag", True),

    #     # K=10 configurations
    #     (10, "basic_rag", False),
    #     (10, "basic_rag", True),
    #     (10, "enhanced_rag", False),
    #     (10, "enhanced_rag", True),

    #     # K=50 configurations
    #     (50, "basic_rag", False),
    #     (50, "basic_rag", True),
    #     (50, "enhanced_rag", False),

    #     # K=100 configuration
    #     (100, "enhanced_rag", True),
    # ]
    # incomplete_experiments = [
    #     # Full context experiments (context window vs RAG comparison)
    #     (1, "full_context", False),
    #     (5, "full_context", False),
    #     (10, "full_context", False),
    #     (20, "full_context", False),
    #     (50, "full_context", False),

    #     # K=20 moderate retrieval experiments
    #     # (20, "basic_rag", False),
    #     (20, "basic_rag", True),
    #     (20, "enhanced_rag", False),
    #     (20, "enhanced_rag", True),

    #     # K=50 high retrieval experiments
    #     (50, "basic_rag", True),
    #     (50, "enhanced_rag", False),
    # ]
    # all_combinations = [
    #     # Full context experiments (context window vs RAG comparison)
    #     (5, "enhanced_rag", False),
    # ]


    logger.info(f"Running {len(all_combinations)} experiments with {n_questions} questions each")
    logger.info(f"Parallelism: {parallel}, Total expected results: {len(all_combinations) * n_questions}")

    for k, retrieval_kind, rerank in all_combinations:
        logger.info(f"Queuing experiment: k={k}, retrieval_kind={retrieval_kind}, rerank={rerank}, n_questions={n_questions}")
        tasks.append(run_with_semaphore(k, retrieval_kind, rerank))

    # Run all experiments with progress tracking
    from tqdm.asyncio import tqdm_asyncio

    results = await tqdm_asyncio.gather(*tasks, desc="Running experiments")

    # Combine all results
    all_results = []
    for result in results:
        if result:  # Skip empty results
            all_results.extend(result)

    logger.info(f"All experiments completed: {len(all_results)} total results")
    return all_results

results = await run_full_experiment_improved(
    clean_df=html_cleaned_df,
    k_range=[100, 200],
    n_questions=200,
    parallel=5,
    retries=6,
)
# results = await run_full_experiment_improved(k_range=[5], n_questions=200, parallel=7, retries=5, clean_df=html_cleaned_df)
# dumped_results = [flatten(x) for x in dump_pydantic_models(results)]
# json.dump(dumped_results, open('../results/reranking_value/wikitext_rag_experiments_results.json', 'w+'), indent=4)
error_summary = summarize_error_statistics(results)
results

2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:92 - Running 9 experiments with 200 questions each
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:93 - Parallelism: 5, Total expected results: 1800
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=100, retrieval_kind=basic_rag, rerank=True, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=100, retrieval_kind=basic_rag, rerank=False, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=100, retrieval_kind=enhanced_rag, rerank=True, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=100, retrieval_kind=enhanced_rag, rerank=False, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=200, retrieval_kind=basic_rag, rerank=True, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=200, retrieval_kind=basic_rag, rerank=False, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=200, retrieval_kind=enhanced_rag, rerank=True, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=200, retrieval_kind=enhanced_rag, rerank=False, n_questions=200
2025-09-21 11:04:57 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=1, retrieval_kind=full_context, rerank=False, n_questions=200
Running experiments:   0%|          | 0/9 [00:00<?, ?it/s]2025-09-21 11:04:57 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 200_basic_rag_False_200_1758445497_55e29069
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 200_basic_rag_False_200_1758445497_55e29069
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 11:04:57 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 100_enhanced_rag_False_200_1758445497_1c9aee1a
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 100_enhanced_rag_False_200_1758445497_1c9aee1a
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 11:04:57 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 100_enhanced_rag_True_200_1758445497_944c4f4e
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 100_enhanced_rag_True_200_1758445497_944c4f4e
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 11:04:57 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 200_enhanced_rag_True_200_1758445497_e365b325
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 200_enhanced_rag_True_200_1758445497_e365b325
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 11:04:57 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 200_basic_rag_True_200_1758445497_cb098fca
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 200_basic_rag_True_200_1758445497_cb098fca
2025-09-21 11:04:57 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 11:05:34 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:05:35 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:05:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:05:46 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:05:48 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:05:51 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:05:52 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:06:02 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:06:02 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:06:07 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:06:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:06:58 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:07:10 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:07:13 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:07:14 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:08:05 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:08:10 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:08:12 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:08:24 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:09:16 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:09:24 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:09:40 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:09:48 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:10:26 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:10:28 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:11:04 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:11:25 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:11:36 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:11:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:12:09 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:12:29 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:12:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:13:13 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:13:31 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:13:46 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:14:12 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:14:17 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:14:23 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:14:53 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:15:22 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:15:22 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:16:22 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:16:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:16:55 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 11:17:22 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:17:24 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:17:26 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:17:47 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:18:27 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:18:36 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:18:43 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:19:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:19:40 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:19:50 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:19:58 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:20:16 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:20:42 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:20:53 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:21:24 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:21:42 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:21:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:22:25 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:22:32 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:22:58 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:23:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:23:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:24:05 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:24:42 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:24:44 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:25:11 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:25:21 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:25:42 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:25:43 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:26:13 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:26:19 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:26:25 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:26:35 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:27:39 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:27:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:27:52 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:28:26 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:28:43 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:28:58 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:29:00 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:29:08 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:29:33 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:29:37 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:30:14 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:30:37 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:30:44 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:31:26 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:31:49 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:31:53 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:32:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:32:40 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:32:50 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:33:09 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:33:39 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:33:47 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:34:00 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:34:03 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:34:50 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:35:17 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:35:36 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:35:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:35:56 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:36:15 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:36:17 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:36:42 | ERROR    | context_is_king.models.interface:query_model_async:401 - ⚠️  Rate limit hit for gpt-4.1-mini, API requested 2.0s wait (attempt 1/6)
2025-09-21 11:37:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:37:38 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:37:39 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:38:07 | ERROR    | context_is_king.models.interface:query_model_async:401 - ⚠️  Rate limit hit for gpt-4.1-mini, API requested 11.0s wait (attempt 1/6)
2025-09-21 11:38:42 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:39:18 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:39:29 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:39:31 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:39:31 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:39:32 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:39:47 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 11:40:31 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:40:33 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:40:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:40:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:41:22 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:41:40 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:41:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:42:13 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:42:24 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:42:43 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:43:37 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:43:49 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:44:06 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:44:25 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:44:48 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:44:49 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:45:54 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:45:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:45:57 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:46:09 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:46:24 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:46:58 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:46:59 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:47:09 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:47:30 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:47:31 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:48:06 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:48:09 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:48:33 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:49:14 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:49:19 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:49:22 | ERROR    | context_is_king.evaluation.judge_evaluator:evaluate_answer:225 - Judge evaluation attempt 1 failed. Sleeping for 2 seconds: <class 'openai.InternalServerError'> - upstream connect error or disconnect/reset before headers. reset reason: connection termination
2025-09-21 11:49:59 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:50:00 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:50:05 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:50:05 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:50:30 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:50:59 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:51:16 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:51:19 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 11:51:25 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 13:04:10 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:05:15 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/100_enhanced_rag_True_200_1758445497_944c4f4e.parquet
2025-09-21 13:05:15 | INFO     | improved_checkpoint_system:start_experiment:363 - Found completed experiment but insufficient data (0 < 160.0)
Running experiments:  22%|██▏       | 2/9 [2:00:18<5:48:24, 2986.30s/it] 2025-09-21 13:05:15 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 1_full_context_False_200_1758452715_9f4dffa3
2025-09-21 13:05:15 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 1_full_context_False_200_1758452715_9f4dffa3
2025-09-21 13:05:15 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 13:05:18 | ERROR    | __main__:llm_call_with_error_tracking:108 - llm call iteration 0 failed. Sleeping for 1 type=<class 'openai.InternalServerError'>: upstream connect error or disconnect/reset before headers. reset reason: connection termination
2025-09-21 13:05:18 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:06:48 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:07:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:14:51 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:15:10 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 13:16:12 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:19:28 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:20:33 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/200_basic_rag_False_200_1758445497_55e29069.parquet
Running experiments:  33%|███▎      | 3/9 [2:15:36<3:24:11, 2041.84s/it]2025-09-21 13:20:33 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 200_enhanced_rag_False_200_1758453633_ae4aad2e
2025-09-21 13:20:33 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 200_enhanced_rag_False_200_1758453633_ae4aad2e
2025-09-21 13:20:33 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 13:20:33 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:20:42 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:21:40 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:22:05 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:22:30 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/200_basic_rag_True_200_1758445497_cb098fca.parquet
Running experiments:  44%|████▍     | 4/9 [2:17:33<1:46:50, 1282.18s/it]2025-09-21 13:22:30 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 100_basic_rag_True_200_1758453750_8ec58f45
2025-09-21 13:22:30 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 100_basic_rag_True_200_1758453750_8ec58f45
2025-09-21 13:22:30 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 13:23:28 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:23:29 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:24:10 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:24:29 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:24:30 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:25:32 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:25:32 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:25:41 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:29:19 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:29:52 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:29:53 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:29:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:29:56 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:30:25 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:30:36 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/200_enhanced_rag_True_200_1758445497_e365b325.parquet
Running experiments:  56%|█████▌    | 5/9 [2:25:38<1:06:19, 994.79s/it] 2025-09-21 13:32:26 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:33:37 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:35:57 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:38:47 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:39:45 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:40:23 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:42:18 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:42:19 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:45:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:45:57 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:47:30 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:48:34 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:50:49 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:56:52 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:57:07 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:59:43 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 13:59:44 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 14:01:43 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 14:02:57 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 14:04:55 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 14:07:01 | WARNING  | __main__:run_single_experiment_improved:386 - Judge evaluation failed for question 119, iteration 2
2025-09-21 14:25:06 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 14:25:17 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 14:25:27 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 14:33:18 | WARNING  | __main__:run_single_experiment_improved:386 - Judge evaluation failed for question 119, iteration 2
2025-09-21 14:35:54 | INFO     | context_is_king.evaluation.judge_evaluator:evaluate_answer:202 - Trying call with OpenAI
2025-09-21 14:36:47 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_full_context_False_200_1758452715_9f4dffa3.parquet
Running experiments:  67%|██████▋   | 6/9 [3:31:49<1:40:20, 2006.69s/it]2025-09-21 14:47:04 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 14:47:14 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 14:47:26 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 14:51:03 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/100_basic_rag_False_200_1758452635_575c411f.parquet
Running experiments:  78%|███████▊  | 7/9 [3:46:06<54:21, 1630.58s/it]  2025-09-21 15:04:10 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 15:04:39 | WARNING  | __main__:run_single_experiment_improved:386 - Judge evaluation failed for question 119, iteration 2
2025-09-21 15:08:47 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 15:15:22 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/100_basic_rag_True_200_1758453750_8ec58f45.parquet
Running experiments:  89%|████████▉ | 8/9 [4:10:25<26:16, 1576.16s/it]2025-09-21 15:19:59 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 15:20:09 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 15:20:14 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 15:49:17 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/200_enhanced_rag_False_200_1758453633_ae4aad2e.parquet
Running experiments: 100%|██████████| 9/9 [4:44:20<00:00, 1895.63s/it]
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:110 - All experiments completed: 5099 total results
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:92 - Running 5 experiments with 200 questions each
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:93 - Parallelism: 7, Total expected results: 1000
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=5, retrieval_kind=basic_rag, rerank=True, n_questions=200
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=5, retrieval_kind=basic_rag, rerank=False, n_questions=200
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=5, retrieval_kind=enhanced_rag, rerank=True, n_questions=200
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=5, retrieval_kind=enhanced_rag, rerank=False, n_questions=200
2025-09-21 15:49:18 | INFO     | __main__:run_full_experiment_improved:96 - Queuing experiment: k=1, retrieval_kind=full_context, rerank=False, n_questions=200
Running experiments:   0%|          | 0/5 [00:00<?, ?it/s]2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:363 - Found completed experiment but insufficient data (0 < 160.0)
2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:363 - Found completed experiment but insufficient data (0 < 160.0)
2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:363 - Found completed experiment but insufficient data (0 < 160.0)
2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:363 - Found completed experiment but insufficient data (0 < 160.0)
2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:340 - Resuming experiment with 33 questions completed: 5_enhanced_rag_True_200_1758029362_32fd4aaf
2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 5_basic_rag_True_200_1758462558_3337baf8
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 5_basic_rag_True_200_1758462558_3337baf8
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 1_full_context_False_200_1758462558_fb542f42
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 1_full_context_False_200_1758462558_fb542f42
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 5_enhanced_rag_False_200_1758462558_9224b4b9
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 5_enhanced_rag_False_200_1758462558_9224b4b9
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 15:49:18 | INFO     | improved_checkpoint_system:start_experiment:376 - Started new experiment: 5_basic_rag_False_200_1758462558_8f4b051b
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:298 - Starting new experiment 5_basic_rag_False_200_1758462558_8f4b051b
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:308 - Processing 189 questions (skipping 0 completed)

  0%|          | 0/189 [00:00<?, ?it/s]

2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:295 - Resuming experiment 5_enhanced_rag_True_200_1758029362_32fd4aaf: 32 questions already completed
2025-09-21 15:49:18 | INFO     | __main__:run_single_experiment_improved:308 - Processing 157 questions (skipping 32 completed)

  0%|          | 0/157 [00:00<?, ?it/s]

Running experiments:   0%|          | 0/5 [22:21<?, ?it/s]

CancelledError:

2025-09-21 16:14:32 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 16:17:19 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 16:22:35 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:22:40 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:22:42 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 16:22:43 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:22:53 | WARNING  | __main__:run_single_experiment_improved:386 - Judge evaluation failed for question 119, iteration 1
2025-09-21 16:25:53 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:26:00 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:26:05 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:29:33 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:29:37 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:29:43 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:31:00 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:31:05 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:31:10 | ERROR    | __main__:llm_call_with_error_tracking:86 - Bad request error (content policy), not retrying: Error code: 400 - {'code': 400, 'error': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'source': 'provider'}
2025-09-21 16:31:15 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 16:39:24 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_True_200_1758029362_32fd4aaf.parquet
2025-09-21 16:39:30 | WARNING  | context_is_king.rag_pipeline.query_enhancement.dual_retrieval:generate_hypothetical_answer:66 - Hypothetical answer generation failed
2025-09-21 16:40:45 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_True_200_1758462558_3337baf8.parquet
2025-09-21 16:44:05 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_False_200_1758462558_8f4b051b.parquet
2025-09-21 16:47:23 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758462558_9224b4b9.parquet
2025-09-21 17:37:50 | INFO     | __main__:run_single_experiment_improved:417 - Experiment completed successfully: /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_full_context_False_200_1758462558_fb542f42.parquet

In [63]:
tmp = pl.read_parquet('/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/100_enhanced_rag_False_200_1758445497_1c9aee1a.parquet')
tmp.shape

(567, 49)

In [64]:
tmp.select(pl.col('k').value_counts())

shape: (1, 1)
┌───────────┐
│ k         │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {100,567} │
└───────────┘

In [22]:
from context_is_king import DATA_DIR
tmpdf = pl.DataFrame(results).unique()
print(f'Loaded {len(tmpdf)} datapoints from results')
tmpdf.write_parquet(DATA_DIR / '5_enhanced_rag_200_results.parquet')

Loaded 566 datapoints from results

In [57]:
schema = {
      'question_index': pl.Int64,
      'k': pl.Int64,
      'retrieval_kind': pl.String,
      'rerank': pl.Boolean,
      'n_question': pl.Int64,
      'judge_result_absolute_assessment_is_correct': pl.Boolean,
      'judge_result_absolute_assessment_confidence': pl.Float64,
      'judge_result_absolute_assessment_reasoning': pl.String,
      'judge_result_context_grounded_assessment_is_correct_given_context': pl.Boolean,
      'judge_result_context_grounded_assessment_confidence': pl.Float64,
      'judge_result_context_grounded_assessment_reasoning': pl.String,
      'judge_result_answer_completeness': pl.Float64,
      'judge_result_context_utilization': pl.Float64,
      'retrieval_benchmarks_precision@1': pl.Float64,
      'retrieval_benchmarks_recall@1': pl.Float64,
      'retrieval_benchmarks_f1@1': pl.Float64,
      'retrieval_benchmarks_precision@5': pl.Float64,
      'retrieval_benchmarks_recall@5': pl.Float64,
      'retrieval_benchmarks_f1@5': pl.Float64,
      'retrieval_benchmarks_precision@10': pl.Float64,
      'retrieval_benchmarks_recall@10': pl.Float64,
      'retrieval_benchmarks_f1@10': pl.Float64,
      'retrieval_benchmarks_mrr': pl.Float64,
      'retrieval_benchmarks_hit_rate': pl.Float64,
      'retrieval_benchmarks_avg_similarity': pl.Float64,
      'retrieval_benchmarks_max_similarity': pl.Float64,
      'retrieval_benchmarks_min_similarity': pl.Float64,
      'context_token_count': pl.Int64,
      'generated_answer': pl.String,
      'stage_2_output': pl.List(pl.Struct({
          'chunk': pl.Struct({
              'content': pl.String,
              'doc_id': pl.String,
              'chunk_id': pl.String,
              'start_char': pl.Int64,
              'end_char': pl.Int64,
              'metadata': pl.Struct({
                  'document_url': pl.String,
                  'collection_name': pl.String,
                  'cache_name': pl.String
              }),
              'full_id': pl.String
          }),
          'similarity_score': pl.Float64,
          'rank': pl.Int64,
          'reranked': pl.Boolean,
          'rerank_score': pl.Float64,
          'final_score': pl.Float64
      })),
      'iteration': pl.Int64,
      'retrieved_chunks': pl.Int64,
      'probability_human': pl.Float64,
      'generated_question': pl.String,
      'question_reasoning': pl.String,
      'main_chunk_id': pl.String,
      'answer': pl.String,
      'status': pl.String,
      'document_url': pl.List(pl.String),
      'collection_suffix': pl.String,
      'error_occurred': pl.Boolean,
      'error_type': pl.String,
      'error_message': pl.String,
      'error_code': pl.String,
      'content_policy_violation': pl.Boolean,
      'input_tokens': pl.Int64,
  }

In [60]:
from pathlib import Path

wiki_folder = (DATA_DIR / '.cache/wikiqa')
wiki_files = list(wiki_folder.iterdir())
for f in tqdm(wiki_files):
    if f.is_dir():
        jsons_in_dir = list(f.glob('*.json'))
        if len(jsons_in_dir) < 5:
            for file_path in jsons_in_dir:
                file_path.unlink()
            f.rmdir()
        print(f'Found {len(jsons_in_dir)} files for {f}')
        target_path = f / 'total_experiment_output.parquet'
        # print(pl.read_json(jsons_in_dir[0]).schema)
        if len(jsons_in_dir) > 50 and '_200_' in f.name:
            data = [json.load(x.open()) for x in jsons_in_dir if x.suffix == '.json']
            data = [flatten(x) for y in data for x in y]
            for x in data:
                x.pop('stage_2_output')
            dir_df = pl.DataFrame(data, schema=schema).with_columns(pl.col('document_url').list.first())
            # dir_df = pl.concat([pl.read_json(x) for x in jsons_in_dir if x.suffix == '.json'])
            print(f'Loaded {len(dir_df)} rows from jsons.')
            # if len(dir_df) != 3*len(jsons_in_dir):
            #     choice = input(f'{len(dir_df)=} != {len(jsons_in_dir)}. Continue writing to disk?')
            #     if 'y' in choice.lower():
            #         dir_df.write_parquet(f / 'total_experiment_output.parquet')
            #     continue
            print(f'Writing output to {target_path}')
            dir_df.write_parquet(target_path)
        else: 
            target_path.unlink()

  0%|          | 0/234 [00:00<?, ?it/s]

Found 186 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_True_200_1758019334_3c586b8a_checkpoints
Loaded 558 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_True_200_1758019334_3c586b8a_checkpoints/total_experiment_output.parquet
Found 156 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_enhanced_rag_False_200_1758048375_0ebff9c0_checkpoints
Loaded 468 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_enhanced_rag_False_200_1758048375_0ebff9c0_checkpoints/total_experiment_output.parquet
Found 28 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_basic_rag_True_200_1758048508_49d6068b_checkpoints
Found 103 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758024496_fa1ac147_checkpoints
Loaded 309 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758024496_fa1ac147_checkpoints/total_experiment_output.parquet
Found 95 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/20_basic_rag_True_200_1758060730_4813b71d_checkpoints
Loaded 285 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/20_basic_rag_True_200_1758060730_4813b71d_checkpoints/total_experiment_output.parquet
Found 17 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_False_200_1758026502_1ec401c8_checkpoints
Found 13 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_basic_rag_False_200_1758027528_81fd5cdd_checkpoints
Found 19 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_enhanced_rag_True_200_1758029790_84003b09_checkpoints
Found 29 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_full_context_False_200_1758048508_dffe0f4c_checkpoints
Found 35 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_True_200_1758027528_5623daec_checkpoints
Found 21 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_True_200_1758029574_11d00888_checkpoints
Found 80 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_True_200_1758025028_1d953614_checkpoints
Loaded 240 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_True_200_1758025028_1d953614_checkpoints/total_experiment_output.parquet
Found 98 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_enhanced_rag_False_200_1758011666_f27a5058_checkpoints
Loaded 294 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_enhanced_rag_False_200_1758011666_f27a5058_checkpoints/total_experiment_output.parquet
Found 12 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_False_200_1758029790_b47c1b9b_checkpoints
Found 189 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758376416_7a8fad71_checkpoints
Loaded 566 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758376416_7a8fad71_checkpoints/total_experiment_output.parquet
Found 72 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_basic_rag_False_200_1758026451_57f6c47d_checkpoints
Loaded 216 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_basic_rag_False_200_1758026451_57f6c47d_checkpoints/total_experiment_output.parquet
Found 190 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_basic_rag_False_200_1758012107_0dc382cd_checkpoints
Loaded 569 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_basic_rag_False_200_1758012107_0dc382cd_checkpoints/total_experiment_output.parquet
Found 5 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_enhanced_rag_False_200_1758028430_bb62eef4_checkpoints
Found 35 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_True_200_1758029377_adc37348_checkpoints
Found 16 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_basic_rag_False_200_1758027099_58630d27_checkpoints
Found 112 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_True_200_1758019383_c3b2d8d5_checkpoints
Loaded 336 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_True_200_1758019383_c3b2d8d5_checkpoints/total_experiment_output.parquet
Found 5 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_basic_rag_True_200_1758027096_14aa6c76_checkpoints
Found 20 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_True_200_1758015640_4a51660a_checkpoints
Found 96 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_False_200_1758017042_525183dd_checkpoints
Loaded 288 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_False_200_1758017042_525183dd_checkpoints/total_experiment_output.parquet
Found 38 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/20_enhanced_rag_False_200_1758048375_1bff2099_checkpoints
Found 32 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/50_basic_rag_True_200_1758048375_bff3a35a_checkpoints
Found 137 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_basic_rag_False_200_1758012107_69f243e9_checkpoints
Loaded 411 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_basic_rag_False_200_1758012107_69f243e9_checkpoints/total_experiment_output.parquet
Found 185 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_True_200_1758011666_2e442efa_checkpoints
Loaded 555 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_True_200_1758011666_2e442efa_checkpoints/total_experiment_output.parquet
Found 32 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_True_200_1758029362_32fd4aaf_checkpoints
Found 28 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_full_context_False_200_1758048508_fb05a454_checkpoints
Found 82 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/20_full_context_False_200_1758060706_1eff7064_checkpoints
Loaded 246 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/20_full_context_False_200_1758060706_1eff7064_checkpoints/total_experiment_output.parquet
Found 42 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/100_enhanced_rag_True_200_1758017042_9ec7f148_checkpoints
Found 28 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_False_200_1758027529_5a138117_checkpoints
Found 22 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_basic_rag_False_200_1758029790_966fbcd0_checkpoints
Found 33 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_full_context_False_200_1758048375_41d8f555_checkpoints
Found 120 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_basic_rag_True_200_1758017042_16982916_checkpoints
Loaded 360 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/1_basic_rag_True_200_1758017042_16982916_checkpoints/total_experiment_output.parquet
Found 82 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758017042_2eb5b58d_checkpoints
Loaded 246 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_enhanced_rag_False_200_1758017042_2eb5b58d_checkpoints/total_experiment_output.parquet
Found 154 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_True_200_1758011666_4ba34175_checkpoints
Loaded 462 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/5_basic_rag_True_200_1758011666_4ba34175_checkpoints/total_experiment_output.parquet
Found 42 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/20_basic_rag_True_200_1758048375_f04305eb_checkpoints
Found 137 files for /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_False_200_1758011666_16cdffde_checkpoints
Loaded 410 rows from jsons.
Writing output to /Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/10_enhanced_rag_False_200_1758011666_16cdffde_checkpoints/total_experiment_output.parquet

In [61]:
pl.scan_parquet(DATA_DIR / '**/total_experiment_output.parquet').select(pl.len()).collect()

shape: (1, 1)
┌──────┐
│ len  │
│ ---  │
│ u32  │
╞══════╡
│ 6819 │
└──────┘

In [20]:
tmpdf['iteration'].value_counts()

shape: (3, 2)
┌───────────┬───────┐
│ iteration ┆ count │
│ ---       ┆ ---   │
│ i64       ┆ u32   │
╞═══════════╪═══════╡
│ 1         ┆ 189   │
│ 2         ┆ 188   │
│ 0         ┆ 189   │
└───────────┴───────┘

In [23]:
Path('../data/.cache/wikiqa/batch2_results.json').resolve()

PosixPath('/Users/baukebrenninkmeijer/Developer/pydata-2025-context-is-king/data/.cache/wikiqa/batch2_results.json')

In [28]:
Path('../data/.cache/wikiqa').resolve().exists()

True

In [29]:
json.dump(results, open('../data/.cache/wikiqa/batch2_results.json', 'w+'), )

In [20]:
import pandas as pd
pd.DataFrame(results).to_parquet('../data/.cache/wikiqa/batch2results.parquet')

ArrowTypeError: ("Expected bytes, got a 'list' object", 'Conversion failed for column stage_2_output with type object')

In [30]:
pl.DataFrame(results, infer_schema_length=1000, strict=False)

ComputeError: could not append value: [{{"The Flash (season 4) - Wikipedia



The Flash (season 4)
From Wikipedia, the free encyclopedia

					Jump to:					navigation, 					search

The Flash (season 4)

Promotional poster

Starring

Grant Gustin
Candice Patton
Danielle Panabaker
Carlos Valdes
Keiynan Lonsdale
Neil Sandilands
Tom Cavanagh
Jesse L. Martin

Country of origin
United States

No. of episodes
19

Release

Original network
The CW

Original release
October 10, 2017 (2017-10-10) – present (present)

Season chronology

← Previous
Season 3

List of The Flash episodes

The fourth season of the American television series The Flash, which is based on the DC Comics character Barry Allen / Flash, follows a crime scene investigator with superhuman speed who fights criminals, including others who have also gained superhuman abilities. It is set in the Arrowverse, sharing continuity with the other television series of the universe, and is a spin-off of Arrow. The season is produced by Berlanti Productions, Warner Bros. Television, and DC Entertainment, with Andrew Kreisberg and Todd Helbing serving as showrunners.
The season was ordered in January 2017, and filming began that July. Grant Gustin stars as Barry, with principal cast members Candice Patton, Danielle Panabaker, Carlos Valdes, Keiynan Lonsdale, Tom Cavanagh, and Jesse L. Martin also returning from previous seasons, and are joined by Neil Sandilands.
The fourth season began airing on October 10, 2017, and is set to run for 23 episodes on The CW until May 22, 2018.[1]

Contents
 [hide]

1 Episodes
2 Cast and characters

2.1 Main
2.2 Recurring
2.3 Guest

3 Production

3.1 Development
3.2 Writing
3.3 Casting
3.4 Filming
3.5 Music
3.6 Arrowverse tie-ins

4 Release

4.1 Broadcast
4.2 Marketing

5 Reception

5.1 Ratings
5.2 Critical response
5.3 Accolades

6 References
7 External links","","88de4634-c65b-449e-8407-42920a3fba48",0,0,{"wikiqa_The_Flash_season_4_187","https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882","wikiqa_The_Flash_season_4"},"_88de4634-c65b-449e-8407-42920a3fba48"},0.789087,1,true,6.012993,6.012993}, {{"The Flash (season 4) - Wikipedia



The Flash (season 4)
From Wikipedia, the free encyclopedia

					Jump to:					navigation, 					search

The Flash (season 4)

Promotional poster

Starring

Grant Gustin
Candice Patton
Danielle Panabaker
Carlos Valdes
Keiynan Lonsdale
Neil Sandilands
Tom Cavanagh
Jesse L. Martin

Country of origin
United States

No. of episodes
19

Release

Original network
The CW

Original release
October 10, 2017 (2017-10-10) – present (present)

Season chronology

← Previous
Season 3

List of The Flash episodes

The fourth season of the American television series The Flash, which is based on the DC Comics character Barry Allen / Flash, follows a crime scene investigator with superhuman speed who fights criminals, including others who have also gained superhuman abilities. It is set in the Arrowverse, sharing continuity with the other television series of the universe, and is a spin-off of Arrow. The season is produced by Berlanti Productions, Warner Bros. Television, and DC Entertainment, with Andrew Kreisberg and Todd Helbing serving as showrunners.
The season was ordered in January 2017, and filming began that July. Grant Gustin stars as Barry, with principal cast members Candice Patton, Danielle Panabaker, Carlos Valdes, Keiynan Lonsdale, Tom Cavanagh, and Jesse L. Martin also returning from previous seasons, and are joined by Neil Sandilands.
The fourth season began airing on October 10, 2017, and is set to run for 23 episodes on The CW until May 22, 2018.[1]

Contents
 [hide]

1 Episodes
2 Cast and characters

2.1 Main
2.2 Recurring
2.3 Guest

3 Production

3.1 Development
3.2 Writing
3.3 Casting
3.4 Filming
3.5 Music
3.6 Arrowverse tie-ins

4 Release

4.1 Broadcast
4.2 Marketing

5 Reception

5.1 Ratings
5.2 Critical response
5.3 Accolades

6 References
7 External links","","2445af72-9976-477c-8f60-df9020713eee",0,0,{"wikiqa_The_Flash_season_4_187","https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882","wikiqa_The_Flash_season_4"},"_2445af72-9976-477c-8f60-df9020713eee"},0.789087,2,true,6.012993,6.012993}, … {{"General references

"The Flash Season 4 Episode Guide". TV Guide. Retrieved August 13, 2017.
"Shows A-Z – The Flash on CW". The Futon Critic. Retrieved August 13, 2017.

External links[edit]

Official website
List of The Flash episodes on IMDb
List of The Flash season 4 episodes at TV.com

[show]

v
t
e

The Flash

Creators

Gardner Fox
Harry Lampert (Jay Garrick)
Bob Kanigher
Carmine Infantino
John Broome (Barry Allen)
John Broome
Carmine Infantino (Wally West)
Mark Waid
Mike Wieringo (Bart Allen)

The Flash Family

The Flash

Jay Garrick
Barry Allen
Wally West
Bart Allen

Kid Flash

Wally West
Bart Allen
Iris West II
Wally West II

Associates

Iris West
Jesse Chambers
Impulse
Johnny Quick
Max Mercury
Linda Park
Tornado Twins
XS

Supporting characters

Argus
David Singh
Green Lantern (Hal Jordan)
Green Lantern (Kyle Rayner)
Elongated Man
Paul Gambi
Patty Spivot
Más y Menos
Pied Piper
Red Trinity
Solovar
Tina McGee
Valerie Perez
Winky, Blinky, and Noddy

Enemies

General

Big Sir
Doctor Alchemy
Fiddler
Godspeed
Gorilla Grodd
Peek-a-Boo
Rag Doll
Rainbow Raider
Savitar
Shade
Thinker
Turtle / Turtle Man
T. O. Morrow

Reverse-Flashes

Rival (Edward Clariss)
Professor Zoom (Eobard Thawne)
Zoom (Hunter Zolomon)
Inertia (Thaddeus Thawne)
Reverse-Flash (Danny West)

Rogues

Abra Kadabra
Captain Boomerang
Captain Cold
Golden Glider
Heat Wave
Mirror Master
Pied Piper
Top
Trickster
Weather Wizard

Publications

Flash Comics
All-Flash
Comic Cavalcade
The Flash
The Flash: Rebirth (2009)
Flashpoint
Flashpoint (Elseworlds)
The Flash Chronicles

Locations

Blue Valley
Central City (Central City Police Department)
Flash Museum
Gorilla City
Iron Heights Penitentiary
Keystone City
S.T.A.R. Labs

In other media

Film","","d41dc68c-741e-4a83-af62-58395550c155",0,0,{"wikiqa_The_Flash_season_4_187","https://en.wikipedia.org//w/index.php?title=The_Flash_(season_4)&amp;oldid=838436882","wikiqa_The_Flash_season_4"},"_d41dc68c-741e-4a83-af62-58395550c155"},0.769476,20,true,1.235848,1.235848}] of type: list[struct[6]] to the builder; make sure that all rows have the same schema or consider increasing `infer_schema_length`

it might also be that a value overflows the data-type's capacity

In [50]:
list(Path('../data/.cache/wikiqa').glob('*.parquet'))

[PosixPath('../data/.cache/wikiqa/50_enhanced_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/50_enhanced_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/5_basic_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/5_enhanced_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/20_enhanced_rag_True_1.parquet'),
 PosixPath('../data/.cache/wikiqa/5_enhanced_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/20_basic_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/20_enhanced_rag_True_20.parquet'),
 PosixPath('../data/.cache/wikiqa/20_enhanced_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/1_basic_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/10_basic_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/5_basic_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/20_basic_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/50_basic_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/100_basic_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/1_enhanced_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/10_enhanced_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/20_enhanced_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/2_enhanced_rag_True_3.parquet'),
 PosixPath('../data/.cache/wikiqa/100_enhanced_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/10_basic_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/10_enhanced_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/1_full_context_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/100_basic_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/100_enhanced_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/50_basic_rag_False_200.parquet'),
 PosixPath('../data/.cache/wikiqa/1_basic_rag_True_200.parquet'),
 PosixPath('../data/.cache/wikiqa/1_enhanced_rag_True_200.parquet')]

In [75]:
import glob


target_struct = pl.Struct(
    {
        "chunk": pl.Struct(
            {
                "content": pl.String,
                "doc_id": pl.String,
                "chunk_id": pl.String,
                "start_char": pl.Int64,
                "end_char": pl.Int64,
                "metadata": pl.Struct(
                    {"document_url": pl.String, "cache_name": pl.String, "collection_name": pl.String}
                ),
                "full_id": pl.String,
            }
        ),
        "similarity_score": pl.Float64,
        "rank": pl.Int64,
        "reranked": pl.Boolean,
        "rerank_score": pl.Float64,
        "final_score": pl.Float64,
    }
)

dfs = []
cast_cols = ["retrieval_benchmarks_f1@5"]
for file in glob.glob("../data/.cache/wikiqa/*.parquet"):
    df = pl.scan_parquet(file)
    # print(file)
    schema = df.collect_schema()
    for c in cast_cols:
        if c in schema.names():
            df = df.with_columns(pl.col(c).cast(pl.Float64))
    if 'stage_2_output' in schema:
        if schema['stage_2_output'] == pl.String:
            # Only strings get converted to empty lists
            df = df.with_columns(
                pl.lit([]).cast(pl.List(target_struct)).alias('stage_2_output')
            )
    # df = df.with_columns(
    #     pl.when(pl.col("stage_2_output") == "full_context_used")
    #     .then(pl.lit([]).cast(pl.List(pl.Struct)))
    #     .otherwise(pl.col("stage_2_output"))
    #     .alias("stage3")
    # )
    dfs.append(df)
    # break
    # df = df.with_columns(pl.col('stage2_output').replace())
results_df = pl.concat(dfs, how="diagonal")

# results_df.sink_parquet('../data/processed/wikiqa/wikiqa_full_results.parquet', mkdir=True)
results_df

InvalidOperationError: 'union'/'concat' inputs should all have the same schema,got
Schema:
name: k, field: Int64
name: retrieval_kind, field: String
name: rerank, field: Boolean
name: n_question, field: Int64
name: judge_result_absolute_assessment_is_correct, field: Boolean
name: judge_result_absolute_assessment_confidence, field: Float64
name: judge_result_absolute_assessment_reasoning, field: String
name: judge_result_context_grounded_assessment_is_correct_given_context, field: Boolean
name: judge_result_context_grounded_assessment_confidence, field: Float64
name: judge_result_context_grounded_assessment_reasoning, field: String
name: judge_result_answer_completeness, field: Float64
name: judge_result_context_utilization, field: Float64
name: retrieval_benchmarks_precision@1, field: Float64
name: retrieval_benchmarks_recall@1, field: Float64
name: retrieval_benchmarks_f1@1, field: Int64
name: retrieval_benchmarks_precision@5, field: Float64
name: retrieval_benchmarks_recall@5, field: Float64
name: retrieval_benchmarks_f1@5, field: Float64
name: retrieval_benchmarks_precision@10, field: Float64
name: retrieval_benchmarks_recall@10, field: Float64
name: retrieval_benchmarks_f1@10, field: Int64
name: retrieval_benchmarks_precision@20, field: Float64
name: retrieval_benchmarks_recall@20, field: Float64
name: retrieval_benchmarks_f1@20, field: Int64
name: retrieval_benchmarks_precision@50, field: Float64
name: retrieval_benchmarks_recall@50, field: Float64
name: retrieval_benchmarks_f1@50, field: Int64
name: retrieval_benchmarks_mrr, field: Float64
name: retrieval_benchmarks_hit_rate, field: Float64
name: retrieval_benchmarks_avg_similarity, field: Float64
name: retrieval_benchmarks_max_similarity, field: Float64
name: retrieval_benchmarks_min_similarity, field: Float64
name: context_token_count, field: Int64
name: generated_answer, field: String
name: stage_2_output, field: List(Struct([Field { name: "chunk", dtype: Struct([Field { name: "content", dtype: String }, Field { name: "doc_id", dtype: String }, Field { name: "chunk_id", dtype: String }, Field { name: "start_char", dtype: Int64 }, Field { name: "end_char", dtype: Int64 }, Field { name: "metadata", dtype: Struct([Field { name: "document_url", dtype: String }, Field { name: "cache_name", dtype: String }, Field { name: "collection_name", dtype: String }]) }, Field { name: "full_id", dtype: String }]) }, Field { name: "similarity_score", dtype: Float64 }, Field { name: "rank", dtype: Int64 }, Field { name: "reranked", dtype: Boolean }, Field { name: "rerank_score", dtype: Null }, Field { name: "final_score", dtype: Float64 }]))
name: iteration, field: Int64
name: retrieved_chunks, field: Int64
name: probability_human, field: Float64
name: generated_question, field: String
name: question_reasoning, field: String
name: main_chunk_id, field: String
name: answer, field: String
name: status, field: String
name: document_url, field: String
name: collection_suffix, field: String
name: retrieval_benchmarks_precision@100, field: Float64
name: retrieval_benchmarks_recall@100, field: Float64
name: retrieval_benchmarks_f1@100, field: Float64
name: retrieval_benchmarks, field: Null
 and
Schema:
name: k, field: Int64
name: retrieval_kind, field: String
name: rerank, field: Boolean
name: n_question, field: Int64
name: judge_result_absolute_assessment_is_correct, field: Boolean
name: judge_result_absolute_assessment_confidence, field: Float64
name: judge_result_absolute_assessment_reasoning, field: String
name: judge_result_context_grounded_assessment_is_correct_given_context, field: Boolean
name: judge_result_context_grounded_assessment_confidence, field: Float64
name: judge_result_context_grounded_assessment_reasoning, field: String
name: judge_result_answer_completeness, field: Float64
name: judge_result_context_utilization, field: Float64
name: retrieval_benchmarks_precision@1, field: Float64
name: retrieval_benchmarks_recall@1, field: Float64
name: retrieval_benchmarks_f1@1, field: Float64
name: retrieval_benchmarks_precision@5, field: Float64
name: retrieval_benchmarks_recall@5, field: Float64
name: retrieval_benchmarks_f1@5, field: Float64
name: retrieval_benchmarks_precision@10, field: Float64
name: retrieval_benchmarks_recall@10, field: Float64
name: retrieval_benchmarks_f1@10, field: Float64
name: retrieval_benchmarks_precision@20, field: Float64
name: retrieval_benchmarks_recall@20, field: Float64
name: retrieval_benchmarks_f1@20, field: Float64
name: retrieval_benchmarks_precision@50, field: Float64
name: retrieval_benchmarks_recall@50, field: Float64
name: retrieval_benchmarks_f1@50, field: Float64
name: retrieval_benchmarks_mrr, field: Float64
name: retrieval_benchmarks_hit_rate, field: Float64
name: retrieval_benchmarks_avg_similarity, field: Float64
name: retrieval_benchmarks_max_similarity, field: Float64
name: retrieval_benchmarks_min_similarity, field: Float64
name: context_token_count, field: Int64
name: generated_answer, field: String
name: stage_2_output, field: List(Struct([Field { name: "chunk", dtype: Struct([Field { name: "content", dtype: String }, Field { name: "doc_id", dtype: String }, Field { name: "chunk_id", dtype: String }, Field { name: "start_char", dtype: Int64 }, Field { name: "end_char", dtype: Int64 }, Field { name: "metadata", dtype: Struct([Field { name: "cache_name", dtype: String }, Field { name: "document_url", dtype: String }, Field { name: "collection_name", dtype: String }]) }, Field { name: "full_id", dtype: String }]) }, Field { name: "similarity_score", dtype: Float64 }, Field { name: "rank", dtype: Int64 }, Field { name: "reranked", dtype: Boolean }, Field { name: "rerank_score", dtype: Float64 }, Field { name: "final_score", dtype: Float64 }]))
name: iteration, field: Int64
name: retrieved_chunks, field: Int64
name: probability_human, field: Float64
name: generated_question, field: String
name: question_reasoning, field: String
name: main_chunk_id, field: String
name: answer, field: String
name: status, field: String
name: document_url, field: String
name: collection_suffix, field: String
name: retrieval_benchmarks_precision@100, field: Float64
name: retrieval_benchmarks_recall@100, field: Float64
name: retrieval_benchmarks_f1@100, field: Float64
name: retrieval_benchmarks, field: Null


Resolved plan until failure:

	---> FAILED HERE RESOLVING THIS_NODE <---
simple π 49/49 ["k", "retrieval_kind", ... 47 other columns]
   WITH_COLUMNS:
   [null.alias("retrieval_benchmarks_precision@5"), null.alias("retrieval_benchmarks_recall@5"), null.alias("retrieval_benchmarks_f1@5"), null.alias("retrieval_benchmarks_precision@10"), null.alias("retrieval_benchmarks_recall@10"), null.alias("retrieval_benchmarks_f1@10"), null.alias("retrieval_benchmarks_precision@20"), null.alias("retrieval_benchmarks_recall@20"), null.alias("retrieval_benchmarks_f1@20"), null.alias("retrieval_benchmarks_precision@50"), null.alias("retrieval_benchmarks_recall@50"), null.alias("retrieval_benchmarks_f1@50"), null.alias("retrieval_benchmarks_precision@100"), null.alias("retrieval_benchmarks_recall@100"), null.alias("retrieval_benchmarks_f1@100"), null.alias("retrieval_benchmarks")]
    Parquet SCAN [../data/.cache/wikiqa/1_enhanced_rag_True_200.parquet]
    PROJECT */33 COLUMNS

In [79]:
results_df = pl.read_parquet('../data/processed/wikiqa/wikiqa_full_results.parquet')
results_df

shape: (6_911, 50)
┌─────┬─────────────┬────────┬────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ k   ┆ retrieval_k ┆ rerank ┆ n_question ┆ … ┆ retrieval_b ┆ retrieval_ ┆ retrieval_ ┆ stage_2_ou │
│ --- ┆ ind         ┆ ---    ┆ ---        ┆   ┆ enchmarks_r ┆ benchmarks ┆ benchmarks ┆ tput       │
│ i64 ┆ ---         ┆ bool   ┆ i64        ┆   ┆ ecall@10…   ┆ _f1@100    ┆ ---        ┆ ---        │
│     ┆ str         ┆        ┆            ┆   ┆ ---         ┆ ---        ┆ null       ┆ str        │
│     ┆             ┆        ┆            ┆   ┆ f64         ┆ f64        ┆            ┆            │
╞═════╪═════════════╪════════╪════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 50  ┆ enhanced_ra ┆ false  ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 50  ┆ enhanced_ra ┆ false  ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 50  ┆ enhanced_ra ┆ false  ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 50  ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 50  ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ …   ┆ …           ┆ …      ┆ …          ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 1   ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 1   ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 1   ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 1   ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
│ 1   ┆ enhanced_ra ┆ true   ┆ 200        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│     ┆ g           ┆        ┆            ┆   ┆             ┆            ┆            ┆            │
└─────┴─────────────┴────────┴────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [18]:
import altair as alt
import polars as pl

In [20]:
results_df.columns

['k',
 'enhanced_rag',
 'rerank',
 'n_question',
 'judge_result_absolute_assessment_is_correct',
 'judge_result_absolute_assessment_confidence',
 'judge_result_absolute_assessment_reasoning',
 'judge_result_context_grounded_assessment_is_correct_given_context',
 'judge_result_context_grounded_assessment_confidence',
 'judge_result_context_grounded_assessment_reasoning',
 'judge_result_answer_completeness',
 'judge_result_context_utilization',
 'retrieval_benchmarks_precision@1',
 'retrieval_benchmarks_recall@1',
 'retrieval_benchmarks_f1@1',
 'retrieval_benchmarks_mrr',
 'retrieval_benchmarks_hit_rate',
 'retrieval_benchmarks_avg_similarity',
 'retrieval_benchmarks_max_similarity',
 'retrieval_benchmarks_min_similarity',
 'generated_answer',
 'stage_1_output',
 'stage_2_output',
 'iteration',
 'human_would_ask',
 'generated_question',
 'question_reasoning',
 'main_chunk_id',
 'answer',
 'status',
 'document_url',
 'collection_suffix']

In [22]:
results_df.schema

Schema([('k', Int64),
        ('enhanced_rag', Boolean),
        ('rerank', Boolean),
        ('n_question', Int64),
        ('judge_result_absolute_assessment_is_correct', Boolean),
        ('judge_result_absolute_assessment_confidence', Float64),
        ('judge_result_absolute_assessment_reasoning', String),
        ('judge_result_context_grounded_assessment_is_correct_given_context',
         Boolean),
        ('judge_result_context_grounded_assessment_confidence', Float64),
        ('judge_result_context_grounded_assessment_reasoning', String),
        ('judge_result_answer_completeness', Float64),
        ('judge_result_context_utilization', Float64),
        ('retrieval_benchmarks_precision@1', Float64),
        ('retrieval_benchmarks_recall@1', Float64),
        ('retrieval_benchmarks_f1@1', Float64),
        ('retrieval_benchmarks_mrr', Float64),
        ('retrieval_benchmarks_hit_rate', Float64),
        ('retrieval_benchmarks_avg_similarity', Float64),
        ('retrieval_benchmarks_max_similarity', Float64),
        ('retrieval_benchmarks_min_similarity', Float64),
        ('generated_answer', String),
        ('stage_1_output',
         List(Struct({'chunk': Struct({'content': String, 'doc_id': String, 'chunk_id': String, 'start_char': Int64, 'end_char': Int64, 'metadata': Struct({'collection_name': String, 'document_url': String, 'cache_name': String}), 'full_id': String}), 'similarity_score': Float64, 'rank': Int64, 'reranked': Boolean, 'rerank_score': Null, 'final_score': Float64}))),
        ('stage_2_output',
         List(Struct({'chunk': Struct({'content': String, 'doc_id': String, 'chunk_id': String, 'start_char': Int64, 'end_char': Int64, 'metadata': Struct({'collection_name': String, 'document_url': String, 'cache_name': String}), 'full_id': String}), 'similarity_score': Float64, 'rank': Int64, 'reranked': Boolean, 'rerank_score': Float64, 'final_score': Float64}))),
        ('iteration', Int64),
        ('human_would_ask', Boolean),
        ('generated_question', String),
        ('question_reasoning', String),
        ('main_chunk_id', String),
        ('answer', String),
        ('status', String),
        ('document_url', List(String)),
        ('collection_suffix', String)])

In [71]:
results